import type { Repositories } from './index.ts';

/**
 * The complete method surface of the `Repositories` bundle, as a runtime table.
 *
 * The compiler already forces every implementation to satisfy the contracts; what it cannot do is
 * hand that surface to code that needs it as *data* — the test-harness stub factory that builds a
 * fully-shaped bundle, and the drift check that notices a contract grew a method nobody implemented.
 * This table is the human-maintained side of that, in one place for all twenty-two repositories.
 *
 * Two guards keep it honest:
 *
 * - **compile time** — `satisfies` proves every listed name is a real method of the contract it is
 *   listed under, so a contract rename or removal fails the typecheck here;
 * - **runtime** — `repository-surface.test.ts` builds the api bundle and asserts each repository
 *   exposes exactly these names, so an *added* contract method that nobody recorded fails there.
 */

/** Function-valued keys of a contract interface. */
type MethodsOf<T> = {
    [K in keyof T]-?: T[K] extends (...args: never[]) => unknown ? K : never;
}[keyof T];

/** Every repository field of the bundle — everything except the `kind` discriminant. */
export type RepositorySurfaceKey = Exclude<keyof Repositories, 'kind'>;

export const REPOSITORY_SURFACE = {
    auth: [
        'challengeTwoFactor',
        'confirmPassword',
        'confirmTwoFactor',
        'enableTwoFactor',
        'login',
        'logout',
        'register',
        'requestPasswordReset',
        'resendVerification',
        'resetPassword',
        'verifyEmailStatus',
    ],
    session: ['me'],
    context: ['setContext'],
    devices: ['list', 'revoke'],
    verification: [
        'addContactPoint',
        'getChallenge',
        'issueChallenge',
        'listContactPoints',
        'removeContactPoint',
        'resendChallenge',
        'setPrimaryContactPoint',
        'verifyChallenge',
    ],
    account: [
        'addAddress',
        'cancelClosure',
        'getChecklist',
        'getClosurePreconditions',
        'getDietaryProfile',
        'getLiveClosureRequest',
        'getOverview',
        'listAddresses',
        'listConsents',
        'listServiceAreas',
        'removeAddress',
        'requestClosure',
        'saveDietaryProfile',
        'setConsent',
        'updateAddress',
        'verifyClosure',
    ],
    guest: [
        'confirmContact',
        'confirmDeletion',
        'convert',
        'getChallenge',
        'getConversionPrefill',
        'getOrder',
        'getSession',
        'placeOrder',
        'requestDeletion',
        'resendChallenge',
        'startSession',
        'updateContact',
    ],
    b2bApplication: [
        'getAgreement',
        'getApplication',
        'getDocumentDownload',
        'getOffboarding',
        'issueSignoffChallenge',
        'removeDocument',
        'runSettlementChecks',
        'saveSection',
        'signAgreement',
        'signOffOffboarding',
        'startApplication',
        'submitApplication',
        'uploadDocument',
        'withdrawApplication',
    ],
    marketplace: [
        'getDietitian',
        'getKitchen',
        'getMeal',
        'getPlan',
        'listDietCategories',
        'listDietitians',
        'listKitchens',
        'listMeals',
        'listPlans',
    ],
    nutrition: ['calculateTargets', 'getCurrentTargets', 'requestReview', 'updateCurrentTargets'],
    planner: [
        'addEntry',
        'adjustPortion',
        'duplicate',
        'generate',
        'getCurrentPlan',
        'getDay',
        'getNotes',
        'getWeek',
        'history',
        'listPlans',
        'lockEntry',
        'regenerateDay',
        'regenerateEntry',
        'regenerateWeek',
        'removeEntry',
        'repeatMeal',
        'replaceEntry',
        'saveAsTemplate',
        'setNotes',
        'unlockEntry',
    ],
    foods: ['getGroceryList', 'getPantry', 'getRecipe', 'listRecipes', 'searchFoods'],
    virtualDietitian: [
        'acceptProposal',
        'createSession',
        'generateDraft',
        'getSession',
        'listSessions',
        'overrideProposal',
        'requestReview',
        'sendMessage',
    ],
    commerce: [
        'addCartItem',
        'cancelSubscription',
        'changeAddress',
        'changeSlot',
        'createSubscription',
        'getCart',
        'getSubscription',
        'getSubscriptionBalance',
        'getSubscriptionQuote',
        'listSubscriptionDeliveries',
        'listSubscriptions',
        'pause',
        'placeOrder',
        'previewCheckout',
        'previewSubscription',
        'removeCartItem',
        'resume',
        'setSubscriptionMealChoices',
        'setSubscriptionWeekdays',
        'skipDay',
    ],
    business: [
        'acceptQuotation',
        'declineQuotation',
        'getCatalogueItem',
        'getCorporateProgramme',
        'listCatalogue',
        'listCorporateProgrammes',
        'listQuotations',
        'requestQuotation',
    ],
    professional: [
        'approve',
        'getClientPlan',
        'getReview',
        'listReviewQueue',
        'requestChanges',
        'setDietitianNote',
        'setOverride',
    ],
    kitchenAdmin: [
        'archiveIngredient',
        'archiveProduct',
        'archiveZone',
        'createIngredient',
        'createMeal',
        'createPlan',
        'createProduct',
        'createRecipe',
        'createZone',
        'forkIngredient',
        'getBranchOperating',
        'getIngredient',
        'getMeal',
        'getPlan',
        'getPlanMenu',
        'getPriceList',
        'getProduct',
        'getRecipe',
        'getRecipeTechnicalSheet',
        'getZone',
        'listAllergenClasses',
        'listIngredientCategories',
        'listIngredients',
        'listMeals',
        'listPlans',
        'listPriceLists',
        'listProducts',
        'listRecipes',
        'listServiceAreas',
        'listZones',
        'nextReference',
        'previewRecipeRollup',
        'publishMeal',
        'publishPlan',
        'publishPriceList',
        'publishRecipe',
        'replacePlanMenu',
        'retireMeal',
        'retirePlan',
        'retireRecipe',
        'setBranchOperating',
        'setDeliveryWindows',
        'setIngredientAllergens',
        'setMealAvailability',
        'setPlanCombinations',
        'setPlanDurations',
        'setPlanVariants',
        'setPriceListEntries',
        'setProductChannelAvailability',
        'setRecipeLines',
        'setRecipePackaging',
        'setRecipeOutputs',
        'setRecipeSteps',
        'setZoneAreas',
        'updateIngredient',
        'updateMeal',
        'updatePlan',
        'updateProduct',
        'updateRecipe',
        'updateZone',
    ],
    kitchenOps: [
        'archiveSupplier',
        'cancelPurchaseOrder',
        'completeProductionOrder',
        'completeReceiptPrices',
        'countLowStockLevels',
        'countSupplyNeeds',
        'countUnresolvedConsumptionExceptions',
        'createProductionOrder',
        'createPurchaseOrders',
        'createQualityCheck',
        'createSupplier',
        'deleteSupplierLink',
        'getGoodsReceipt',
        'getOrderProposal',
        'getProcurementReference',
        'getPurchaseOrder',
        'getSpendSummary',
        'getSupplier',
        'holdQualityCheck',
        'issuePurchaseOrder',
        'listConsumptionExceptions',
        'listCostReport',
        'listGoodsReceipts',
        'listItemLatestPurchases',
        'listProductionOrders',
        'listPurchaseOrders',
        'listPurchasesLedger',
        'listQualityChecks',
        'listReceivableOrders',
        'listStockItems',
        'listStockLevels',
        'listSuppliers',
        'listUnpricedReceipts',
        'postGoodsReceipt',
        'recordStockAdjustment',
        'recordStockWaste',
        'releaseQualityCheck',
        'replaceSupplierContacts',
        'resolveConsumptionException',
        'restoreSupplier',
        'retryConsumptionException',
        'setStockThreshold',
        'updatePurchaseOrder',
        'updateSupplier',
        'upsertSupplierLink',
    ],
    kitchenOrders: [
        'cancelOrder',
        'confirmOrder',
        'fulfilOrder',
        'getOrder',
        'listOrders',
        'recordPayment',
    ],
    orderDesk: [
        'addCustomerAddress',
        'assignDeliveryJob',
        'countRequirementShortfalls',
        'createCustomer',
        'getCashReport',
        'listCalendar',
        'listDrivers',
        'listQueue',
        'listRequirements',
        'placeSale',
        'quoteSale',
        'searchCustomers',
    ],
    kitchenQuotations: ['getQuotation', 'listQuotations', 'quoteQuotation'],
    driverJobs: ['deliverJob', 'listJobs'],
    platformAdmin: [
        'createKitchen',
        'getKitchen',
        'inviteOwner',
        'listKitchens',
        'reactivateKitchen',
        'revokeOwner',
        'suspendKitchen',
    ],
    invitations: ['acceptInvitation', 'getInvitation'],
} as const satisfies {
    readonly [K in RepositorySurfaceKey]: readonly MethodsOf<Repositories[K]>[];
};

export const REPOSITORY_SURFACE_KEYS = Object.keys(
    REPOSITORY_SURFACE,
) as readonly RepositorySurfaceKey[];

export const REPOSITORY_SURFACE_METHOD_COUNT = REPOSITORY_SURFACE_KEYS.reduce(
    (total, key) => total + REPOSITORY_SURFACE[key].length,
    0,
);
