<?php

declare(strict_types=1);

namespace Healthy360\Support\Correlation;

use Healthy360\Support\Identifiers\IdentifierService;

/**
 * Request-scoped holder of the server-generated correlation identifier and
 * the optional client-supplied request identifier (docs/api/conventions.md).
 *
 * The correlation identifier is always generated by the server; a client may
 * send X-Client-Request-Id for its own support correlation, but that value is
 * only ever logged and echoed — never promoted to the correlation identifier.
 *
 * A value is generated lazily so that responses rendered outside the HTTP
 * middleware stack (console, early boot failures) still carry one.
 */
final class CorrelationContext
{
    private ?string $correlationId = null;

    private ?string $clientRequestId = null;

    public function __construct(private readonly IdentifierService $identifiers) {}

    public function correlationId(): string
    {
        return $this->correlationId ??= $this->identifiers->generate();
    }

    public function assign(string $correlationId): void
    {
        $this->correlationId = $correlationId;
    }

    public function clientRequestId(): ?string
    {
        return $this->clientRequestId;
    }

    public function setClientRequestId(?string $clientRequestId): void
    {
        $this->clientRequestId = $clientRequestId;
    }
}
