import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { NUTRITION_LEVELS, SEMANTIC_ROLES, themes } from '../colour.ts';
import { renderTokensCss } from './css.ts';
import { renderTokensNative } from './native.ts';
import { renderTailwindPreset } from './tailwind-preset.ts';
import { CSS_VARIABLE_PREFIX, kebab, themeColourVariables, toRgbTriplet } from './shared.ts';

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

describe('shared helpers', () => {
    it('converts hex to the space-separated triplet Tailwind alpha syntax needs', () => {
        expect(toRgbTriplet('#2f6157')).toBe('47 97 87');
        expect(toRgbTriplet('#fff')).toBe('255 255 255');
    });

    it('kebab-cases token names', () => {
        expect(kebab('surfaceBase')).toBe('surface-base');
        expect(kebab('onBrandSurfaceSubtle')).toBe('on-brand-surface-subtle');
        expect(kebab('subtle')).toBe('subtle');
    });

    it('declares a variable for every theme-dependent colour and nothing else', () => {
        const variables = themeColourVariables();
        const expected =
            Object.keys(themes.light.colours).length +
            SEMANTIC_ROLES.length * Object.keys(themes.light.semantic.success).length +
            NUTRITION_LEVELS.length * 2;
        expect(variables).toHaveLength(expected);
        expect(new Set(variables.map((v) => v.name)).size).toBe(variables.length);
        for (const variable of variables) {
            expect(variable.name.startsWith(`${CSS_VARIABLE_PREFIX}-color-`)).toBe(true);
        }
    });

    it('uses the alpha-aware reference form for opaque colours only', () => {
        const variables = themeColourVariables();
        const surface = variables.find((v) => v.name.endsWith('-surface-base'));
        const overlay = variables.find((v) => v.name.endsWith('-overlay'));
        expect(surface?.reference).toBe(`rgb(var(${surface?.name}) / <alpha-value>)`);
        expect(overlay?.opaque).toBe(false);
        expect(overlay?.reference).toBe(`var(${overlay?.name})`);
    });
});

describe('renderTailwindPreset', () => {
    const output = renderTailwindPreset();

    it('is a CommonJS module that only extends the theme', () => {
        expect(output).toContain('module.exports = {');
        expect(output).toContain('AUTOGENERATED');
        const preset = JSON.parse(
            output.slice(output.indexOf('{'), output.lastIndexOf('}') + 1),
        ) as {
            theme: { extend: Record<string, unknown> };
        };
        expect(Object.keys(preset.theme)).toEqual(['extend']);
    });

    const preset = JSON.parse(output.slice(output.indexOf('{'), output.lastIndexOf('}') + 1)) as {
        theme: {
            extend: {
                colors: Record<string, unknown>;
                spacing: Record<string, string>;
                screens: Record<string, string>;
                boxShadow: Record<string, string>;
                letterSpacing: Record<string, string>;
                fontSize: Record<string, [string, string] | [string, Record<string, string>]>;
                lineHeight: Record<string, string>;
                height: Record<string, string>;
                width: Record<string, string>;
                minHeight: Record<string, string>;
                minWidth: Record<string, string>;
                padding: Record<string, string>;
                gap: Record<string, string>;
                fontFamily: Record<string, readonly string[]>;
            };
        };
    };

    it('exposes the raw ramps as literal hex values', () => {
        expect(preset.theme.extend.colors.brand).toMatchObject({ 600: '#158043' });
    });

    it('routes every theme-dependent colour through a CSS variable', () => {
        const surface = preset.theme.extend.colors.surface as Record<string, string>;
        expect(surface.base).toBe(
            `rgb(var(${CSS_VARIABLE_PREFIX}-color-surface-base) / <alpha-value>)`,
        );
        for (const role of SEMANTIC_ROLES) {
            const set = preset.theme.extend.colors[role] as Record<string, string>;
            expect(Object.keys(set)).toEqual([
                'subtle',
                'on-subtle',
                'DEFAULT',
                'on-default',
                'strong',
                'on-strong',
                'border',
            ]);
            for (const value of Object.values(set)) {
                expect(value).toContain('var(--h360-color-');
            }
        }
    });

    it('emits pixel units everywhere (React Native cannot resolve rem)', () => {
        for (const value of Object.values(preset.theme.extend.spacing)) {
            expect(value).toMatch(/^\d+px$/);
        }
        for (const value of Object.values(preset.theme.extend.screens)) {
            expect(value).toMatch(/^\d+px$/);
        }
    });

    it('omits the zero-width xs breakpoint, which is the default rather than a query', () => {
        expect(preset.theme.extend.screens).not.toHaveProperty('xs');
        expect(preset.theme.extend.screens.sm).toBe('480px');
    });

    it('pairs each font size with its Latin line height and exposes Arabic separately', () => {
        expect(preset.theme.extend.fontSize.base).toEqual(['16px', '24px']);
        expect(preset.theme.extend.lineHeight['arabic-base']).toBe('28px');
        expect(preset.theme.extend.lineHeight['latin-base']).toBe('24px');
    });

    it('turns the control ladders into utilities a component can name', () => {
        expect(preset.theme.extend.height['control-sm']).toBe('28px');
        expect(preset.theme.extend.height['row-md']).toBe('32px');
        expect(preset.theme.extend.padding['control-sm']).toBe('8px');
        expect(preset.theme.extend.gap['control-sm']).toBe('6px');
        expect(preset.theme.extend.width.field).toBe('280px');
    });

    /**
     * `MIN_TOUCH_TARGET` is retired, and `min-h-touch` is not — see the note on
     * `DEPRECATED_TOUCH_TARGET_PX`. Two dozen customer call sites still apply these classes, and a
     * utility the preset stops defining fails silently: NativeWind emits nothing and the minimum
     * disappears with no error. This test is what keeps the shim from being tidied away early.
     */
    it('keeps emitting the touch utilities the customer surfaces still apply', () => {
        expect(preset.theme.extend.minHeight.touch).toBe('44px');
        expect(preset.theme.extend.minWidth.touch).toBe('44px');
    });

    /**
     * `min-h-control-*` and `min-h-row-*` are the ladder as a *floor*, for a box that must clear the
     * control height but may grow past it — a dropdown option is one line at 28px and two when it
     * carries a description, which `h-control-sm` would clip.
     *
     * What was retired is the *coarse-pointer* ladder: `controlHeightTouch` and `rowHeightTouch`,
     * which existed only to hold 44px up while the brief asked for 32. So the invariant is about
     * the value, not the key — these minimums must be the ladder's own, and 44px must reach the
     * preset only through `touch`, which the customer surfaces still apply.
     */
    it('floors the control ladder at its own heights, never at the touch target', () => {
        expect(preset.theme.extend.minHeight['control-md']).toBe('32px');
        expect(preset.theme.extend.minHeight['row-md']).toBe('32px');

        const laddered = Object.entries(preset.theme.extend.minHeight).filter(
            ([key]) => key !== 'touch',
        );
        expect(laddered).not.toHaveLength(0);
        for (const [, value] of laddered) {
            expect(value).not.toBe('44px');
        }
    });

    it('prefixes the Catalogue ramp so it cannot shadow the numeric scale', () => {
        expect(preset.theme.extend.fontSize['role-micro']).toEqual([
            '10px',
            { lineHeight: '14px', letterSpacing: '0px', fontWeight: '600' },
        ]);
        expect(preset.theme.extend.fontSize.xs).toEqual(['12px', '18px']);
    });

    /**
     * One Latin family across every key, and no `admin` key at all.
     *
     * `display` and `mono` stay as *roles* so a caller can still say "this is display type" or
     * "this is a figure", but both resolve to the body stack. `admin` is gone: it existed only to
     * scope Schibsted Grotesk to the Catalogue while the customer surfaces were still on Inter.
     */
    it('resolves every Latin family key to the one face', () => {
        for (const key of ['latin', 'display', 'mono'] as const) {
            expect(preset.theme.extend.fontFamily[key]?.[0]).toContain('SchibstedGrotesk');
        }
        expect(preset.theme.extend.fontFamily.arabic?.[0]).toContain('IBMPlexSansArabic');
        expect(preset.theme.extend.fontFamily.admin).toBeUndefined();
    });

    it('exposes the six ramp elevations plus the two named ones as box shadows', () => {
        expect(Object.keys(preset.theme.extend.boxShadow)).toEqual([
            'elevation-0',
            'elevation-1',
            'elevation-2',
            'elevation-3',
            'elevation-4',
            'elevation-5',
            'elevation-card',
            'elevation-card-hover',
        ]);
    });

    it('gives the named card elevations two layers and a canopy-tinted cast', () => {
        // The two-layer shape is the point: a 1px contact shadow for the edge and a wide offset
        // cast for the lift. A single-layer value here would silently be a ramp step by another
        // name, which is what the named tokens exist to not be.
        for (const name of ['elevation-card', 'elevation-card-hover'] as const) {
            const value = preset.theme.extend.boxShadow[name] ?? '';
            expect(value.split('),').length).toBe(2);
            expect(value).toContain('rgb(11 59 38 /');
        }
    });

    it('carries the display tracking in em, not px — it has to scale with the type', () => {
        expect(preset.theme.extend.letterSpacing.display).toBe('-0.02em');
        expect(preset.theme.extend.letterSpacing.tight).toBe('-0.4px');
    });

    it('contains no physical direction keys — the RTL policy applies to tokens too', () => {
        expect(output).not.toMatch(/"(marginLeft|marginRight|paddingLeft|paddingRight)"/);
    });
});

describe('renderTokensCss', () => {
    const output = renderTokensCss();

    it('emits a :root block and a .dark block', () => {
        expect(output).toContain(':root {');
        expect(output).toContain('.dark {');
        expect(output).toContain('@media (prefers-color-scheme: dark)');
        expect(output).toContain('@media (prefers-reduced-motion: reduce)');
    });

    it('defines every theme colour in both blocks', () => {
        const [, rootBlock = '', darkBlock = ''] =
            /:root \{([\s\S]*?)\n\}[\s\S]*?\.dark \{([\s\S]*?)\n\}/.exec(output) ?? [];
        for (const variable of themeColourVariables()) {
            expect(rootBlock, variable.name).toContain(
                `${variable.name}: ${variable.values.light};`,
            );
            expect(darkBlock, variable.name).toContain(
                `${variable.name}: ${variable.values.dark};`,
            );
        }
    });

    it('writes opaque colours as RGB triplets so `<alpha-value>` works', () => {
        expect(output).toContain(`${CSS_VARIABLE_PREFIX}-color-surface-base: 247 252 249;`);
    });

    it('zeroes durations under prefers-reduced-motion', () => {
        const reduced = output.slice(output.indexOf('prefers-reduced-motion'));
        expect(reduced).toContain(`${CSS_VARIABLE_PREFIX}-duration-normal: 0ms;`);
        expect(reduced).not.toMatch(/duration-\w+: [1-9]/);
    });

    it('includes theme-independent scales once, in :root only', () => {
        expect(output.match(/--h360-space-4:/g)).toHaveLength(1);
        expect(output).toContain(`${CSS_VARIABLE_PREFIX}-space-snug: 12px;`);
    });

    it('carries the control geometry and the Catalogue ramp', () => {
        expect(output).toContain(`${CSS_VARIABLE_PREFIX}-control-height-sm: 28px;`);
        expect(output).toContain(`${CSS_VARIABLE_PREFIX}-row-height-md: 32px;`);
        expect(output).toContain(`${CSS_VARIABLE_PREFIX}-field-width: 280px;`);
        expect(output).toContain(`${CSS_VARIABLE_PREFIX}-text-micro-size: 10px;`);
        expect(output).toContain(`${CSS_VARIABLE_PREFIX}-text-micro-line-height-latin: 14px;`);
        expect(output).toContain(`${CSS_VARIABLE_PREFIX}-text-micro-tracking-arabic: 0px;`);
    });

    /**
     * The admin family is declared here and bound in no rule, which is the point: `global.css`
     * applies `--h360-font-family-latin` to `html`, so a surface opts into Schibsted Grotesk and
     * the customer app keeps the face it has.
     */
    /**
     * Two families, one per script, and no `admin` variable at all — it existed only to scope
     * Schibsted Grotesk to the Catalogue while the customer surfaces were still on Inter. `mono` is
     * still declared because it is a role a caller can name; it is never *bound* to an element,
     * because a figure takes `tabular-nums` inside the one family rather than a mono face.
     */
    it('declares the mono role without binding it, and no admin family', () => {
        expect(output).toContain(`${CSS_VARIABLE_PREFIX}-font-family-latin`);
        expect(output).toContain(`${CSS_VARIABLE_PREFIX}-font-family-arabic`);
        expect(output).toContain(`${CSS_VARIABLE_PREFIX}-font-family-mono`);
        expect(output).not.toContain(`${CSS_VARIABLE_PREFIX}-font-family-admin`);
        expect(output).not.toMatch(/font-family:\s*var\(--h360-font-family-mono\)/);
    });
});

describe('renderTokensNative', () => {
    const output = renderTokensNative();

    it('exports a const-asserted token object plus its types', () => {
        expect(output).toContain('export const nativeTokens = {');
        expect(output).toContain('} as const;');
        expect(output).toContain('export type NativeTokens = typeof nativeTokens;');
        expect(output).toContain('export default nativeTokens;');
    });

    it('carries React Native shadow objects rather than CSS strings', () => {
        expect(output).toContain('"shadowOpacity"');
        expect(output).toContain('"shadowRadius"');
        expect(output).not.toContain('box-shadow');
    });

    it('carries the control geometry and the per-script ramp metrics', () => {
        expect(output).toContain('"fieldWidth": 280');
        expect(output).toContain('"textRoleMetrics"');
        expect(output).not.toContain('"minTouchTarget"');
    });

    it('includes both themes with their nutrition patterns', () => {
        expect(output).toContain('"light"');
        expect(output).toContain('"dark"');
        expect(output).toContain('"diagonal-sparse"');
    });
});

/**
 * Drift detection: the committed artefacts must match what the source renders right now. This is
 * what makes "generated output is committed" safe.
 */
describe('committed artefacts are up to date', () => {
    it.each([
        ['generated/tailwind-preset.cjs', renderTailwindPreset],
        ['generated/tokens.css', renderTokensCss],
        ['generated/tokens.native.ts', renderTokensNative],
    ])('%s', async (relativePath, render) => {
        const onDisk = await readFile(join(packageRoot, relativePath), 'utf8');
        expect(
            onDisk,
            `${relativePath} is stale — run: pnpm --filter @healthy360/design-tokens build:tokens`,
        ).toBe(render());
    });
});
