import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { NUTRITION_LEVELS, SEMANTIC_ROLES, themes } from '../colour.ts';
import { renderTokensCss } from './css.ts';
import { renderTokensNative } from './native.ts';
import { renderTailwindPreset } from './tailwind-preset.ts';
import { CSS_VARIABLE_PREFIX, kebab, themeColourVariables, toRgbTriplet } from './shared.ts';

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

describe('shared helpers', () => {
    it('converts hex to the space-separated triplet Tailwind alpha syntax needs', () => {
        expect(toRgbTriplet('#2f6157')).toBe('47 97 87');
        expect(toRgbTriplet('#fff')).toBe('255 255 255');
    });

    it('kebab-cases token names', () => {
        expect(kebab('surfaceBase')).toBe('surface-base');
        expect(kebab('onBrandSurfaceSubtle')).toBe('on-brand-surface-subtle');
        expect(kebab('subtle')).toBe('subtle');
    });

    it('declares a variable for every theme-dependent colour and nothing else', () => {
        const variables = themeColourVariables();
        const expected =
            Object.keys(themes.light.colours).length +
            SEMANTIC_ROLES.length * Object.keys(themes.light.semantic.success).length +
            NUTRITION_LEVELS.length * 2;
        expect(variables).toHaveLength(expected);
        expect(new Set(variables.map((v) => v.name)).size).toBe(variables.length);
        for (const variable of variables) {
            expect(variable.name.startsWith(`${CSS_VARIABLE_PREFIX}-color-`)).toBe(true);
        }
    });

    it('uses the alpha-aware reference form for opaque colours only', () => {
        const variables = themeColourVariables();
        const surface = variables.find((v) => v.name.endsWith('-surface-base'));
        const overlay = variables.find((v) => v.name.endsWith('-overlay'));
        expect(surface?.reference).toBe(`rgb(var(${surface?.name}) / <alpha-value>)`);
        expect(overlay?.opaque).toBe(false);
        expect(overlay?.reference).toBe(`var(${overlay?.name})`);
    });
});

describe('renderTailwindPreset', () => {
    const output = renderTailwindPreset();

    it('is a CommonJS module that only extends the theme', () => {
        expect(output).toContain('module.exports = {');
        expect(output).toContain('AUTOGENERATED');
        const preset = JSON.parse(
            output.slice(output.indexOf('{'), output.lastIndexOf('}') + 1),
        ) as {
            theme: { extend: Record<string, unknown> };
        };
        expect(Object.keys(preset.theme)).toEqual(['extend']);
    });

    const preset = JSON.parse(output.slice(output.indexOf('{'), output.lastIndexOf('}') + 1)) as {
        theme: {
            extend: {
                colors: Record<string, unknown>;
                spacing: Record<string, string>;
                screens: Record<string, string>;
                boxShadow: Record<string, string>;
                fontSize: Record<string, [string, string]>;
                lineHeight: Record<string, string>;
            };
        };
    };

    it('exposes the raw ramps as literal hex values', () => {
        expect(preset.theme.extend.colors.brand).toMatchObject({ 600: '#2d6f39' });
    });

    it('routes every theme-dependent colour through a CSS variable', () => {
        const surface = preset.theme.extend.colors.surface as Record<string, string>;
        expect(surface.base).toBe(
            `rgb(var(${CSS_VARIABLE_PREFIX}-color-surface-base) / <alpha-value>)`,
        );
        for (const role of SEMANTIC_ROLES) {
            const set = preset.theme.extend.colors[role] as Record<string, string>;
            expect(Object.keys(set)).toEqual([
                'subtle',
                'on-subtle',
                'DEFAULT',
                'on-default',
                'strong',
                'on-strong',
                'border',
            ]);
            for (const value of Object.values(set)) {
                expect(value).toContain('var(--h360-color-');
            }
        }
    });

    it('emits pixel units everywhere (React Native cannot resolve rem)', () => {
        for (const value of Object.values(preset.theme.extend.spacing)) {
            expect(value).toMatch(/^\d+px$/);
        }
        for (const value of Object.values(preset.theme.extend.screens)) {
            expect(value).toMatch(/^\d+px$/);
        }
    });

    it('omits the zero-width xs breakpoint, which is the default rather than a query', () => {
        expect(preset.theme.extend.screens).not.toHaveProperty('xs');
        expect(preset.theme.extend.screens.sm).toBe('480px');
    });

    it('pairs each font size with its Latin line height and exposes Arabic separately', () => {
        expect(preset.theme.extend.fontSize.base).toEqual(['16px', '24px']);
        expect(preset.theme.extend.lineHeight['arabic-base']).toBe('28px');
        expect(preset.theme.extend.lineHeight['latin-base']).toBe('24px');
    });

    it('exposes all six elevations as box shadows', () => {
        expect(Object.keys(preset.theme.extend.boxShadow)).toEqual([
            'elevation-0',
            'elevation-1',
            'elevation-2',
            'elevation-3',
            'elevation-4',
            'elevation-5',
        ]);
    });

    it('contains no physical direction keys — the RTL policy applies to tokens too', () => {
        expect(output).not.toMatch(/"(marginLeft|marginRight|paddingLeft|paddingRight)"/);
    });
});

describe('renderTokensCss', () => {
    const output = renderTokensCss();

    it('emits a :root block and a .dark block', () => {
        expect(output).toContain(':root {');
        expect(output).toContain('.dark {');
        expect(output).toContain('@media (prefers-color-scheme: dark)');
        expect(output).toContain('@media (prefers-reduced-motion: reduce)');
    });

    it('defines every theme colour in both blocks', () => {
        const [, rootBlock = '', darkBlock = ''] =
            /:root \{([\s\S]*?)\n\}[\s\S]*?\.dark \{([\s\S]*?)\n\}/.exec(output) ?? [];
        for (const variable of themeColourVariables()) {
            expect(rootBlock, variable.name).toContain(
                `${variable.name}: ${variable.values.light};`,
            );
            expect(darkBlock, variable.name).toContain(
                `${variable.name}: ${variable.values.dark};`,
            );
        }
    });

    it('writes opaque colours as RGB triplets so `<alpha-value>` works', () => {
        expect(output).toContain(`${CSS_VARIABLE_PREFIX}-color-surface-base: 255 255 255;`);
    });

    it('zeroes durations under prefers-reduced-motion', () => {
        const reduced = output.slice(output.indexOf('prefers-reduced-motion'));
        expect(reduced).toContain(`${CSS_VARIABLE_PREFIX}-duration-normal: 0ms;`);
        expect(reduced).not.toMatch(/duration-\w+: [1-9]/);
    });

    it('includes theme-independent scales once, in :root only', () => {
        expect(output.match(/--h360-space-4:/g)).toHaveLength(1);
        expect(output).toContain(`${CSS_VARIABLE_PREFIX}-min-touch-target: 44px;`);
    });
});

describe('renderTokensNative', () => {
    const output = renderTokensNative();

    it('exports a const-asserted token object plus its types', () => {
        expect(output).toContain('export const nativeTokens = {');
        expect(output).toContain('} as const;');
        expect(output).toContain('export type NativeTokens = typeof nativeTokens;');
        expect(output).toContain('export default nativeTokens;');
    });

    it('carries React Native shadow objects rather than CSS strings', () => {
        expect(output).toContain('"shadowOpacity"');
        expect(output).toContain('"shadowRadius"');
        expect(output).not.toContain('box-shadow');
    });

    it('includes both themes with their nutrition patterns', () => {
        expect(output).toContain('"light"');
        expect(output).toContain('"dark"');
        expect(output).toContain('"diagonal-sparse"');
    });
});

/**
 * Drift detection: the committed artefacts must match what the source renders right now. This is
 * what makes "generated output is committed" safe.
 */
describe('committed artefacts are up to date', () => {
    it.each([
        ['generated/tailwind-preset.cjs', renderTailwindPreset],
        ['generated/tokens.css', renderTokensCss],
        ['generated/tokens.native.ts', renderTokensNative],
    ])('%s', async (relativePath, render) => {
        const onDisk = await readFile(join(packageRoot, relativePath), 'utf8');
        expect(
            onDisk,
            `${relativePath} is stale — run: pnpm --filter @healthy360/design-tokens build:tokens`,
        ).toBe(render());
    });
});
