import { hexToRgb, isHexColour } from '../contrast.ts';
import { NUTRITION_LEVELS, SEMANTIC_ROLES, themes } from '../colour.ts';
import type { ThemeName } from '../colour.ts';

export const GENERATED_BANNER = [
    '/*',
    ' * AUTOGENERATED by @healthy360/design-tokens — do not edit by hand.',
    ' * Source: packages/design-tokens/src/*.ts',
    ' * Regenerate: pnpm --filter @healthy360/design-tokens build:tokens',
    ' * The output is committed so consumers need no build step; a drift test fails the build if',
    ' * this file and the TypeScript source disagree.',
    ' */',
].join('\n');

export const CSS_VARIABLE_PREFIX = '--h360';

/** `#2f6157` -> `47 97 87`, the space-separated form Tailwind's `<alpha-value>` syntax needs. */
export function toRgbTriplet(hex: string): string {
    const { r, g, b } = hexToRgb(hex);
    return `${r} ${g} ${b}`;
}

/** camelCase / PascalCase -> kebab-case, for CSS custom property names. */
export function kebab(value: string): string {
    return value
        .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
        .replace(/[_\s]+/g, '-')
        .toLowerCase();
}

export interface ThemeColourVariable {
    /** Full custom property name, e.g. `--h360-color-surface-base`. */
    readonly name: string;
    /** Tailwind-facing reference, e.g. `rgb(var(--h360-color-surface-base) / <alpha-value>)`. */
    readonly reference: string;
    /** Per-theme value. Opaque colours are RGB triplets; anything with alpha stays verbatim. */
    readonly values: Readonly<Record<ThemeName, string>>;
    readonly opaque: boolean;
}

function variable(path: string, light: string, dark: string): ThemeColourVariable {
    const name = `${CSS_VARIABLE_PREFIX}-color-${path}`;
    const opaque = isHexColour(light) && isHexColour(dark);
    return {
        name,
        reference: opaque ? `rgb(var(${name}) / <alpha-value>)` : `var(${name})`,
        values: {
            light: opaque ? toRgbTriplet(light) : light,
            dark: opaque ? toRgbTriplet(dark) : dark,
        },
        opaque,
    };
}

/**
 * Every theme-dependent colour, as a CSS custom property.
 *
 * Theme-dependent colours go through variables (one class swap re-themes the whole tree, on web and
 * under NativeWind); the raw ramps do not, because `brand-600` means the same thing in both themes
 * and indirection there would only obscure it.
 */
export function themeColourVariables(): readonly ThemeColourVariable[] {
    const light = themes.light;
    const dark = themes.dark;
    const variables: ThemeColourVariable[] = [];

    for (const key of Object.keys(light.colours) as Array<keyof typeof light.colours>) {
        variables.push(variable(kebab(key), light.colours[key], dark.colours[key]));
    }

    for (const role of SEMANTIC_ROLES) {
        for (const slot of Object.keys(light.semantic[role]) as Array<
            keyof (typeof light.semantic)[typeof role]
        >) {
            variables.push(
                variable(
                    `${role}-${kebab(slot)}`,
                    light.semantic[role][slot],
                    dark.semantic[role][slot],
                ),
            );
        }
    }

    for (const level of NUTRITION_LEVELS) {
        variables.push(
            variable(
                `nutrition-${level}`,
                light.nutrition[level].colour,
                dark.nutrition[level].colour,
            ),
        );
        variables.push(
            variable(`nutrition-${level}-on`, light.nutrition[level].on, dark.nutrition[level].on),
        );
    }

    return variables;
}

/** Looks a variable up by its dotted token path, e.g. `surface-base`. */
export function variableReference(path: string): string {
    const found = themeColourVariables().find(
        (item) => item.name === `${CSS_VARIABLE_PREFIX}-color-${path}`,
    );
    if (found === undefined) throw new Error(`Unknown theme colour variable: ${path}`);
    return found.reference;
}
