import type {
    GroceryListItem,
    MarketplaceMeal,
    MealPlanEntry,
    Recipe,
} from '@healthy360/api-client/contracts';
import { MEAL_TYPES, minorUnitExponent } from '@healthy360/domain-types';
import type { AllergenCode, MealType, Money } from '@healthy360/domain-types';
import { amountValue, nutritionLevelForAmount, scaleFacts } from '@healthy360/nutrition';
import type { NutrientTarget, NutritionFacts, NutritionLevel } from '@healthy360/nutrition';
import type { RangeValue } from '@healthy360/design-system';

/**
 * The planner's presentation arithmetic — calendar, differences and entry classification.
 *
 * Everything here is pure and has no React in it, so the parts that are easy to get subtly wrong can
 * be tested as arithmetic rather than through a render. Three families live here.
 *
 * **Calendar.** UTC-only, `YYYY-MM-DD` in and out. A planner that shifted a week by a timezone would
 * put Monday's dinner on Sunday for anybody east of Greenwich, and the fixture world is pinned to
 * UTC (`mock/prototype/constants.ts`) precisely so this can be checked.
 *
 * **Differences.** The replacement drawer's whole reason to exist is the *difference* between what
 * is planned and what is being considered (doc 17, PLN-15 — no precedent in either reference). A
 * difference is three separate comparisons: nutrition, cost and allergens. They are computed here,
 * once, and every one of them is signed — a preview that shows "820 kcal" beside "640 kcal" and
 * leaves the reader to subtract is not a preview.
 *
 * **Entry classification.** Which badges an entry earns, and which of its warnings are safety
 * warnings rather than nutrition warnings. The distinction matters: an allergen conflict is a hard
 * constraint (doc 10, REQ-10) and an energy overshoot is not, and rendering them with one tone would
 * teach people to dismiss both.
 */

/* ── calendar ────────────────────────────────────────────────────────────────────────────────── */

const MILLISECONDS_PER_DAY = 86_400_000;
const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

/** True for a well-formed, real `YYYY-MM-DD` date. `2026-02-31` is well-formed and not real. */
export function isPlannerDate(value: string | undefined): value is string {
    if (value === undefined || !ISO_DATE.test(value)) return false;
    const parsed = Date.parse(`${value}T00:00:00.000Z`);
    if (Number.isNaN(parsed)) return false;
    return new Date(parsed).toISOString().slice(0, 10) === value;
}

export function addDays(date: string, days: number): string {
    const parsed = Date.parse(`${date}T00:00:00.000Z`);
    return new Date(parsed + days * MILLISECONDS_PER_DAY).toISOString().slice(0, 10);
}

/** ISO weekday: `1` Monday through `7` Sunday. */
export function isoWeekday(date: string): number {
    const day = new Date(`${date}T00:00:00.000Z`).getUTCDay();
    return day === 0 ? 7 : day;
}

/**
 * The Monday of the week `date` falls in.
 *
 * Deep links are typed by people and generated by other screens, and both produce mid-week dates.
 * Normalising here rather than rejecting means `/planner/week/2026-07-30` shows the week containing
 * that Thursday instead of a not-found page for a date that is perfectly valid.
 */
export function mondayOf(date: string): string {
    return addDays(date, -(isoWeekday(date) - 1));
}

/** The seven dates of the week starting at `weekStart`. */
export function weekDates(weekStart: string): readonly string[] {
    return [0, 1, 2, 3, 4, 5, 6].map((offset) => addDays(weekStart, offset));
}

/** Midday of a date, as the instant a formatter should render. */
export function dateInstant(date: string): string {
    return `${date}T12:00:00.000Z`;
}

/**
 * Today, in UTC.
 *
 * Read once per render rather than per cell, and used only to mark the current day column. Nothing
 * in the planner *behaves* differently on today — a highlight that turned into a rule about which
 * days can be edited would be a clock deciding what a person may plan.
 */
export function todayIso(): string {
    return new Date().toISOString().slice(0, 10);
}

/* ── meal types ──────────────────────────────────────────────────────────────────────────────── */

/**
 * The order a day is read in, which is not the order the enum declares.
 *
 * `MEAL_TYPES` is `breakfast, lunch, dinner, snack` — a vocabulary, not a timetable. A day reads
 * breakfast, lunch, snack, dinner, and the planner grid's rows are a timetable.
 */
export const PLANNER_MEAL_TYPES: readonly MealType[] = ['breakfast', 'lunch', 'snack', 'dinner'];

const MEAL_TYPE_RANK: Readonly<Record<MealType, number>> = {
    breakfast: 0,
    lunch: 1,
    snack: 2,
    dinner: 3,
};

/** Stable order within a day: meal type, then position, then identifier. Mirrors the store's. */
export function compareEntries(left: MealPlanEntry, right: MealPlanEntry): number {
    const byType = MEAL_TYPE_RANK[left.mealType] - MEAL_TYPE_RANK[right.mealType];
    if (byType !== 0) return byType;
    if (left.position !== right.position) return left.position - right.position;
    return left.id < right.id ? -1 : left.id > right.id ? 1 : 0;
}

export function entriesForSlot(
    entries: readonly MealPlanEntry[],
    date: string,
    mealType: MealType,
): readonly MealPlanEntry[] {
    return entries
        .filter((entry) => entry.date === date && entry.mealType === mealType)
        .slice()
        .sort(compareEntries);
}

/** Guards a route or form value into a `MealType`. */
export function toMealType(value: string | undefined): MealType | null {
    return value !== undefined && (MEAL_TYPES as readonly string[]).includes(value)
        ? (value as MealType)
        : null;
}

/* ── warnings ────────────────────────────────────────────────────────────────────────────────── */

/**
 * The warning codes the fixture store derives, split by what they mean.
 *
 * `planner.allergen_conflict` is a *safety* warning: the entry contains something the person has
 * declared an allergy to, it is a hard constraint (doc 10, REQ-10), and `ReplaceEntryRequest`
 * deliberately refuses to let it be confirmed away (`mock/prototype/store.ts`). Everything else is a
 * nutrition warning — worth saying, never blocking.
 */
export const ALLERGEN_WARNING_CODE = 'planner.allergen_conflict';

export function safetyWarnings(entry: MealPlanEntry): readonly string[] {
    return entry.warnings.filter((code) => code === ALLERGEN_WARNING_CODE);
}

export function nutritionWarnings(entry: MealPlanEntry): readonly string[] {
    return entry.warnings.filter((code) => code !== ALLERGEN_WARNING_CODE);
}

export function hasSafetyWarning(entry: MealPlanEntry): boolean {
    return safetyWarnings(entry).length > 0;
}

/* ── entry badges ────────────────────────────────────────────────────────────────────────────── */

export const PLANNER_BADGE_KINDS = [
    'kitchen',
    'home_prepared',
    'restaurant',
    'food',
    'dietitian_approved',
    'leftover',
    'locked',
] as const;
export type PlannerBadgeKind = (typeof PLANNER_BADGE_KINDS)[number];

/**
 * The badges an entry earns, derived from the entry rather than configured per card.
 *
 * Source first (where the food comes from), then provenance (who signed it off), then planning state
 * (leftover, locked). The order is fixed so two cards never disagree about which badge comes first,
 * and it is the order a person asks the questions in.
 */
export function badgesFor(entry: MealPlanEntry): readonly PlannerBadgeKind[] {
    const badges: PlannerBadgeKind[] = [];

    if (entry.kind === 'kitchen_meal') badges.push('kitchen');
    else if (entry.kind === 'recipe') badges.push('home_prepared');
    else if (entry.kind === 'restaurant') badges.push('restaurant');
    else badges.push('food');

    if (entry.approvedBy !== null) badges.push('dietitian_approved');
    if (entry.isLeftover) badges.push('leftover');
    if (entry.locked) badges.push('locked');

    return badges;
}

/** Where "open detail" goes for an entry, or `null` when the entry has no record behind it. */
export function detailHrefFor(entry: MealPlanEntry): string | null {
    if (entry.kind === 'recipe' && entry.recipeId !== null) {
        return `/customer/recipes/${String(entry.recipeId)}`;
    }
    if (entry.kind === 'kitchen_meal' && entry.mealId !== null) {
        return `/meals/${String(entry.mealId)}`;
    }
    return null;
}

/* ── nutrition differences ───────────────────────────────────────────────────────────────────── */

/** The four figures a replacement preview compares, in label order. */
export const DIFFERENCE_NUTRIENT_IDS: readonly string[] = [
    'energy',
    'protein',
    'carbohydrate',
    'fat',
];

export type DeltaSign = 'up' | 'down' | 'same';

export interface NutrientDifference {
    readonly nutrientId: string;
    readonly before: number;
    readonly after: number;
    /** `after - before`, rounded to the precision the figure is displayed at. */
    readonly delta: number;
    readonly sign: DeltaSign;
}

/**
 * Rounds before subtracting, deliberately.
 *
 * The two figures on screen are rounded, and a difference computed from the unrounded values can
 * disagree with them by a unit — "640 kcal → 700 kcal, +59" is the kind of arithmetic error that
 * makes a reader distrust every other number on the page.
 */
export function nutrientDifference(
    before: NutritionFacts,
    after: NutritionFacts,
    nutrientId: string,
): NutrientDifference {
    const from = Math.round(amountValue(before, nutrientId));
    const to = Math.round(amountValue(after, nutrientId));
    const delta = to - from;
    return {
        nutrientId,
        before: from,
        after: to,
        delta,
        sign: delta > 0 ? 'up' : delta < 0 ? 'down' : 'same',
    };
}

export function nutritionDifference(
    before: NutritionFacts,
    after: NutritionFacts,
    nutrientIds: readonly string[] = DIFFERENCE_NUTRIENT_IDS,
): readonly NutrientDifference[] {
    return nutrientIds.map((nutrientId) => nutrientDifference(before, after, nutrientId));
}

export interface MoneyDifference {
    readonly before: Money | null;
    readonly after: Money | null;
    /** `null` when either side has no price at all — an unknown is not a zero. */
    readonly delta: Money | null;
    readonly sign: DeltaSign;
    /** True when one side carries a price and the other does not. */
    readonly incomparable: boolean;
}

/**
 * The cost difference.
 *
 * A missing price is *unknown*, never zero. A planned restaurant meal has no estimate at all
 * (`contracts/planner.ts`), and reporting "−34.00 AED" for swapping it out would invent a saving
 * that nobody can bank. Currencies that differ are equally incomparable rather than silently added.
 */
export function moneyDifference(before: Money | null, after: Money | null): MoneyDifference {
    if (before === null || after === null || before.currency !== after.currency) {
        return {
            before,
            after,
            delta: null,
            sign: 'same',
            incomparable: before !== null || after !== null,
        };
    }
    const amount = after.amount - before.amount;
    return {
        before,
        after,
        delta: { amount, currency: after.currency },
        sign: amount > 0 ? 'up' : amount < 0 ? 'down' : 'same',
        incomparable: false,
    };
}

/** Money in its major unit, for a formatter. Integer minor units in, decimal out. */
export function majorUnits(value: Money): number {
    return value.amount / 10 ** minorUnitExponent(value.currency);
}

export interface AllergenDifference {
    /** Present in the candidate and absent from the entry being replaced. The dangerous half. */
    readonly introduced: readonly AllergenCode[];
    /** Present in the entry and absent from the candidate. */
    readonly removed: readonly AllergenCode[];
    readonly unchanged: readonly AllergenCode[];
}

export function allergenDifference(
    before: readonly AllergenCode[],
    after: readonly AllergenCode[],
): AllergenDifference {
    const had = new Set<string>(before);
    const has = new Set<string>(after);
    return {
        introduced: after.filter((code) => !had.has(code)),
        removed: before.filter((code) => !has.has(code)),
        unchanged: after.filter((code) => had.has(code)),
    };
}

/* ── replacement compatibility ───────────────────────────────────────────────────────────────── */

export const COMPATIBILITY_LEVELS = ['fits', 'check', 'conflict'] as const;
export type CompatibilityLevel = (typeof COMPATIBILITY_LEVELS)[number];

export interface CompatibilityInput {
    readonly entry: MealPlanEntry;
    readonly candidateFacts: NutritionFacts;
    readonly candidateAllergens: readonly AllergenCode[];
    /** Meal types the candidate is offered for. Empty means "the source does not say". */
    readonly candidateMealTypes: readonly MealType[];
    /** The day's planned facts before the swap, when the calling screen holds them. */
    readonly dayPlanned?: NutritionFacts | undefined;
    readonly targets?: readonly NutrientTarget[] | undefined;
}

export interface Compatibility {
    readonly level: CompatibilityLevel;
    /** Reason codes, translated by the caller. Ordered worst first. */
    readonly reasons: readonly string[];
}

/**
 * How well a candidate fits the slot it would go into.
 *
 * Three questions, and each one is answerable from data the client actually holds:
 *
 * 1. **Does it introduce an allergen the current entry does not carry?** That is a `conflict`. Note
 *    what this does *not* claim: the consumer contracts publish no list of the person's declared
 *    allergies, so this cannot say "you are allergic to this" — only that the swap brings something
 *    new in. The recorded gap is in the wave report; the drawer's allergen-exclusion filter is the
 *    real defence, and the store re-derives the true warning on the entry that comes back.
 * 2. **Is it offered for this meal type?** A dinner in a breakfast slot is a `check`, not a block —
 *    people eat what they like when they like.
 * 3. **Does the day's energy stay inside the target's tolerance after the swap?** Only asked when
 *    the caller passes the day and the targets, because guessing at either would be worse than
 *    staying quiet.
 */
export function replacementCompatibility(input: CompatibilityInput): Compatibility {
    const reasons: string[] = [];
    let level: CompatibilityLevel = 'fits';

    const allergens = allergenDifference(input.entry.allergens, input.candidateAllergens);
    if (allergens.introduced.length > 0) {
        reasons.push('newAllergens');
        level = 'conflict';
    }

    if (
        input.candidateMealTypes.length > 0 &&
        !input.candidateMealTypes.includes(input.entry.mealType)
    ) {
        reasons.push('otherMealType');
        if (level === 'fits') level = 'check';
    }

    const energyTarget = input.targets?.find((target) => target.nutrientId === 'energy');
    if (input.dayPlanned !== undefined && energyTarget !== undefined && energyTarget.value > 0) {
        const projected =
            amountValue(input.dayPlanned, 'energy') -
            amountValue(input.entry.nutrition, 'energy') +
            amountValue(input.candidateFacts, 'energy');
        const projectedLevel = nutritionLevelForAmount(projected, energyTarget);
        if (projectedLevel === 'high' || projectedLevel === 'excessive') {
            reasons.push('dayEnergyOutOfRange');
            if (level === 'fits') level = 'check';
        }
    }

    return { level, reasons };
}

/* ── summaries ───────────────────────────────────────────────────────────────────────────────── */

export interface SummaryReading {
    readonly nutrientId: string;
    readonly planned: number;
    readonly target: number;
    readonly unit: string;
    readonly level: NutritionLevel;
    readonly tolerance: { readonly min: number; readonly max: number };
}

/**
 * A summary's planned figures read against the targets.
 *
 * Reads `planned`, never `actual`. They are different facts on `DailyNutritionSummary`
 * (`@healthy360/nutrition`): `planned` is what the plan intends and `actual` is what was logged,
 * and `actual` is `null` until something is recorded. Substituting one for the other is the exact
 * defect doc 17, PLN-02 forbids — it would turn a planning surface into a consumption claim.
 */
export function summaryReadings(
    planned: NutritionFacts,
    targets: readonly NutrientTarget[],
    nutrientIds: readonly string[] = DIFFERENCE_NUTRIENT_IDS,
): readonly SummaryReading[] {
    return nutrientIds.flatMap((nutrientId) => {
        const target = targets.find((candidate) => candidate.nutrientId === nutrientId);
        if (target === undefined) return [];
        const value = Math.round(amountValue(planned, nutrientId));
        return [
            {
                nutrientId,
                planned: value,
                target: Math.round(target.value),
                unit: target.unit,
                level: nutritionLevelForAmount(value, target),
                tolerance: {
                    min: Math.round(target.tolerance.min),
                    max: Math.round(target.tolerance.max),
                },
            },
        ];
    });
}

/** Sum of every entry's estimated cost, or `null` when nothing in the set carries one. */
export function totalCost(entries: readonly MealPlanEntry[]): Money | null {
    const priced = entries.flatMap((entry) =>
        entry.estimatedCost === null ? [] : [entry.estimatedCost],
    );
    const first = priced[0];
    if (first === undefined) return null;
    return {
        amount: priced
            .filter((cost) => cost.currency === first.currency)
            .reduce<number>((sum, cost) => sum + cost.amount, 0),
        currency: first.currency,
    };
}

/** Entries whose cost is unknown, so a total can say what it is missing rather than under-reporting. */
export function unpricedCount(entries: readonly MealPlanEntry[]): number {
    return entries.filter((entry) => entry.estimatedCost === null).length;
}

/** Longest preparation time in a set, in minutes. `null` when nothing declares one. */
export function preparationMinutes(entries: readonly MealPlanEntry[]): number | null {
    const declared = entries.flatMap((entry) =>
        entry.preparationMinutes === null ? [] : [entry.preparationMinutes],
    );
    return declared.length === 0 ? null : Math.max(...declared);
}

/* ── replacement candidates ──────────────────────────────────────────────────────────────────── */

/**
 * A marketplace meal and a home-prepared recipe, reduced to the same shape.
 *
 * The two arrive from different repositories with different fields — a meal has a kitchen and a
 * price, a recipe has servings and a cook time — and the difference arithmetic does not care about
 * either. Normalising here is what lets one comparison serve both tabs of the replacement drawer,
 * and it is why these functions are pure and live beside the arithmetic rather than inside the
 * component that renders them.
 */
export type ReplacementSource = 'kitchen_meal' | 'recipe';

/** The six numeric bands the replacement search offers, on both of its tabs. */
export const REPLACEMENT_RANGE_KEYS = [
    'energy',
    'protein',
    'carbohydrate',
    'fat',
    'price',
    'preparationMinutes',
] as const;
export type ReplacementRangeKey = (typeof REPLACEMENT_RANGE_KEYS)[number];

const EMPTY_RANGE: RangeValue = { min: null, max: null };

/** Every band open. Shared so "cleared" is one object rather than six literals per call site. */
export const EMPTY_RANGES: Readonly<Record<ReplacementRangeKey, RangeValue>> = {
    energy: EMPTY_RANGE,
    protein: EMPTY_RANGE,
    carbohydrate: EMPTY_RANGE,
    fat: EMPTY_RANGE,
    price: EMPTY_RANGE,
    preparationMinutes: EMPTY_RANGE,
};

/** One candidate, reduced to the four facts a comparison needs, whatever it came from. */
export interface ReplacementCandidate {
    readonly key: string;
    readonly source: ReplacementSource;
    readonly name: string;
    readonly description: string;
    /** Facts already scaled to the portion the replacement entry would carry. */
    readonly facts: NutritionFacts;
    readonly allergens: readonly AllergenCode[];
    readonly mealTypes: readonly MealType[];
    readonly estimatedCost: Money | null;
    readonly preparationMinutes: number | null;
    readonly kitchenName: string | null;
    readonly mealId?: MarketplaceMeal['id'] | undefined;
    readonly recipeId?: Recipe['id'] | undefined;
}

function withinRange(value: number | null, range: RangeValue): boolean {
    if (value === null) return range.min === null && range.max === null;
    if (range.min !== null && value < range.min) return false;
    if (range.max !== null && value > range.max) return false;
    return true;
}

/** Marketplace meals to candidates, scaled to the entry's portion. */
export function mealCandidates(
    meals: readonly MarketplaceMeal[],
    portionFactor: number,
): readonly ReplacementCandidate[] {
    return meals.map((meal) => ({
        key: String(meal.id),
        source: 'kitchen_meal' as const,
        name: meal.name,
        description: meal.description,
        facts: scaleFacts(meal.nutrition, portionFactor, {
            basis: 'per_meal',
            method: 'planner.replacement_preview',
        }),
        allergens: meal.allergens,
        mealTypes: meal.mealTypes,
        estimatedCost: {
            amount: Math.round(meal.price.amount * portionFactor),
            currency: meal.price.currency,
        },
        preparationMinutes: meal.preparationMinutes,
        kitchenName: meal.kitchenName,
        mealId: meal.id,
    }));
}

/** Recipes to candidates. A recipe's cost is per recipe, so the per-serving share is taken first. */
export function recipeCandidates(
    recipes: readonly Recipe[],
    portionFactor: number,
): readonly ReplacementCandidate[] {
    return recipes.map((recipe) => ({
        key: String(recipe.id),
        source: 'recipe' as const,
        name: recipe.name,
        description: recipe.description,
        facts: scaleFacts(recipe.nutrition.perServing, portionFactor, {
            basis: 'per_meal',
            method: 'planner.replacement_preview',
        }),
        allergens: recipe.allergens,
        mealTypes: recipe.mealTypes,
        estimatedCost:
            recipe.estimatedCost === null
                ? null
                : {
                      amount: Math.round(
                          (recipe.estimatedCost.amount / recipe.servings) * portionFactor,
                      ),
                      currency: recipe.estimatedCost.currency,
                  },
        preparationMinutes: recipe.preparationMinutes + recipe.cookingMinutes,
        kitchenName: null,
        recipeId: recipe.id,
    }));
}

/**
 * The bands `RecipeFilter` cannot express, applied here.
 *
 * Exported so the arithmetic is testable without a render — it is the one place in the drawer where
 * a wrong comparison silently returns the wrong candidates rather than throwing.
 */
export function applyClientRanges(
    candidates: readonly ReplacementCandidate[],
    ranges: Readonly<Record<ReplacementRangeKey, RangeValue>>,
    priceScale: number,
): readonly ReplacementCandidate[] {
    return candidates.filter((candidate) => {
        if (
            !withinRange(
                Math.round(amountValue(candidate.facts, 'carbohydrate')),
                ranges.carbohydrate,
            )
        ) {
            return false;
        }
        if (!withinRange(Math.round(amountValue(candidate.facts, 'fat')), ranges.fat)) return false;
        if (ranges.price.min !== null || ranges.price.max !== null) {
            const price =
                candidate.estimatedCost === null
                    ? null
                    : candidate.estimatedCost.amount / priceScale;
            if (!withinRange(price, ranges.price)) return false;
        }
        if (ranges.preparationMinutes.min !== null || ranges.preparationMinutes.max !== null) {
            if (!withinRange(candidate.preparationMinutes, ranges.preparationMinutes)) return false;
        }
        return true;
    });
}

/* ── grocery grouping ────────────────────────────────────────────────────────────────────────── */

export interface AisleGroup {
    readonly aisle: string;
    readonly items: readonly GroceryListItem[];
}

/**
 * Items grouped by aisle, in the order the repository returned them.
 *
 * The repository already sorts by aisle then name (`mock/prototype/planner.ts`), so grouping in
 * arrival order preserves that ordering without re-sorting — and a client that re-sorted would
 * disagree with a server that changed its mind about aisle order.
 */
export function groupByAisle(
    items: readonly GroceryListItem[],
    unsortedLabel: string,
): readonly AisleGroup[] {
    const groups = new Map<string, GroceryListItem[]>();
    for (const item of items) {
        const aisle = item.aisle ?? unsortedLabel;
        const existing = groups.get(aisle);
        if (existing === undefined) groups.set(aisle, [item]);
        else existing.push(item);
    }
    return [...groups.entries()].map(([aisle, grouped]) => ({ aisle, items: grouped }));
}
