/*
 * AUTOGENERATED by scripts/build-image-manifest.mjs — do not edit by hand.
 * Source: apps/universal/assets/images/<family>/*.webp
 * Regenerate: pnpm --filter universal build:images
 * Bundled, same-origin assets only — the no-external-requests e2e gate forbids any other kind.
 */

import type { ImageRequireSource } from 'react-native';

import img0 from '../../assets/images/dietitians/hala-rizk.portrait.webp';
import img1 from '../../assets/images/dietitians/karim-nassar.portrait.webp';
import img2 from '../../assets/images/dietitians/layla-haddad.portrait.webp';
import img3 from '../../assets/images/dietitians/maya-darwish.portrait.webp';
import img4 from '../../assets/images/dietitians/tarek-shammas.portrait.webp';
import img5 from '../../assets/images/diets/balanced.hero.webp';
import img6 from '../../assets/images/diets/dairy-free.hero.webp';
import img7 from '../../assets/images/diets/family.hero.webp';
import img8 from '../../assets/images/diets/gluten-free.hero.webp';
import img9 from '../../assets/images/diets/high-protein.hero.webp';
import img10 from '../../assets/images/diets/low-carb.hero.webp';
import img11 from '../../assets/images/diets/mediterranean.hero.webp';
import img12 from '../../assets/images/diets/muscle-gain.hero.webp';
import img13 from '../../assets/images/diets/office.hero.webp';
import img14 from '../../assets/images/diets/pescatarian.hero.webp';
import img15 from '../../assets/images/diets/plant-based.hero.webp';
import img16 from '../../assets/images/diets/vegetarian.hero.webp';
import img17 from '../../assets/images/diets/weight-management.hero.webp';
import img18 from '../../assets/images/discover/diets.tile.webp';
import img19 from '../../assets/images/discover/meals.tile.webp';
import img20 from '../../assets/images/discover/plans.tile.webp';
import img21 from '../../assets/images/discover/tools.tile.webp';
import img22 from '../../assets/images/dishes/calamari-rocket-salad.card.webp';
import img23 from '../../assets/images/dishes/calamari-rocket-salad.detail.webp';
import img24 from '../../assets/images/dishes/charred-aubergine-chickpea.card.webp';
import img25 from '../../assets/images/dishes/charred-aubergine-chickpea.detail.webp';
import img26 from '../../assets/images/dishes/citrus-sea-bass-green-beans.card.webp';
import img27 from '../../assets/images/dishes/citrus-sea-bass-green-beans.detail.webp';
import img28 from '../../assets/images/dishes/courgette-walnut-pasta.card.webp';
import img29 from '../../assets/images/dishes/courgette-walnut-pasta.detail.webp';
import img30 from '../../assets/images/dishes/garden-omelette-spinach.card.webp';
import img31 from '../../assets/images/dishes/garden-omelette-spinach.detail.webp';
import img32 from '../../assets/images/dishes/grilled-halloumi-rocket.card.webp';
import img33 from '../../assets/images/dishes/grilled-halloumi-rocket.detail.webp';
import img34 from '../../assets/images/dishes/harbour-prawn-quinoa.card.webp';
import img35 from '../../assets/images/dishes/harbour-prawn-quinoa.detail.webp';
import img36 from '../../assets/images/dishes/herbed-chicken-freekeh.card.webp';
import img37 from '../../assets/images/dishes/herbed-chicken-freekeh.detail.webp';
import img38 from '../../assets/images/dishes/lemon-tahini-salmon.card.webp';
import img39 from '../../assets/images/dishes/lemon-tahini-salmon.detail.webp';
import img40 from '../../assets/images/dishes/mint-yoghurt-chicken-skewers.card.webp';
import img41 from '../../assets/images/dishes/mint-yoghurt-chicken-skewers.detail.webp';
import img42 from '../../assets/images/dishes/morning-oats-dates-almonds.card.webp';
import img43 from '../../assets/images/dishes/morning-oats-dates-almonds.detail.webp';
import img44 from '../../assets/images/dishes/pistachio-pomegranate-bowl.card.webp';
import img45 from '../../assets/images/dishes/pistachio-pomegranate-bowl.detail.webp';
import img46 from '../../assets/images/dishes/red-bean-pepper-chilli.card.webp';
import img47 from '../../assets/images/dishes/red-bean-pepper-chilli.detail.webp';
import img48 from '../../assets/images/dishes/roasted-cauliflower-wrap.card.webp';
import img49 from '../../assets/images/dishes/roasted-cauliflower-wrap.detail.webp';
import img50 from '../../assets/images/dishes/slow-braised-lamb-bulgur.card.webp';
import img51 from '../../assets/images/dishes/slow-braised-lamb-bulgur.detail.webp';
import img52 from '../../assets/images/dishes/smoky-tofu-kale-bowl.card.webp';
import img53 from '../../assets/images/dishes/smoky-tofu-kale-bowl.detail.webp';
import img54 from '../../assets/images/dishes/spiced-lentil-pumpkin-stew.card.webp';
import img55 from '../../assets/images/dishes/spiced-lentil-pumpkin-stew.detail.webp';
import img56 from '../../assets/images/dishes/sunrise-labneh-sourdough.card.webp';
import img57 from '../../assets/images/dishes/sunrise-labneh-sourdough.detail.webp';
import img58 from '../../assets/images/dishes/tempeh-broccoli-stir-fry.card.webp';
import img59 from '../../assets/images/dishes/tempeh-broccoli-stir-fry.detail.webp';
import img60 from '../../assets/images/dishes/turkey-sweet-potato-hash.card.webp';
import img61 from '../../assets/images/dishes/turkey-sweet-potato-hash.detail.webp';
import img62 from '../../assets/images/for-business/clinic.tile.webp';
import img63 from '../../assets/images/for-business/corporate.tile.webp';
import img64 from '../../assets/images/for-business/gym.tile.webp';
import img65 from '../../assets/images/for-business/hero.hero.webp';
import img66 from '../../assets/images/for-business/wholesale.tile.webp';
import img67 from '../../assets/images/how-it-works/eat.tile.webp';
import img68 from '../../assets/images/how-it-works/plan.tile.webp';
import img69 from '../../assets/images/how-it-works/target.tile.webp';
import img70 from '../../assets/images/how-it-works/tell.tile.webp';
import img71 from '../../assets/images/kitchens/northwind-provisions.card.webp';
import img72 from '../../assets/images/kitchens/northwind-provisions.detail.webp';
import img73 from '../../assets/images/kitchens/olive-terrace-counter.card.webp';
import img74 from '../../assets/images/kitchens/olive-terrace-counter.detail.webp';
import img75 from '../../assets/images/kitchens/riverstone-meal-works.card.webp';
import img76 from '../../assets/images/kitchens/riverstone-meal-works.detail.webp';
import img77 from '../../assets/images/kitchens/saffron-and-sea.card.webp';
import img78 from '../../assets/images/kitchens/saffron-and-sea.detail.webp';
import img79 from '../../assets/images/kitchens/the-daily-pot.card.webp';
import img80 from '../../assets/images/kitchens/the-daily-pot.detail.webp';
import img81 from '../../assets/images/kitchens/verdant-kitchen.card.webp';
import img82 from '../../assets/images/kitchens/verdant-kitchen.detail.webp';
import img83 from '../../assets/images/landing/hero.hero.webp';
import img84 from '../../assets/images/plans/balanced-week.card.webp';
import img85 from '../../assets/images/plans/balanced-week.detail.webp';
import img86 from '../../assets/images/plans/coastal-light.card.webp';
import img87 from '../../assets/images/plans/coastal-light.detail.webp';
import img88 from '../../assets/images/plans/desk-lunch-club.card.webp';
import img89 from '../../assets/images/plans/desk-lunch-club.detail.webp';
import img90 from '../../assets/images/plans/everyday-family-box.card.webp';
import img91 from '../../assets/images/plans/everyday-family-box.detail.webp';
import img92 from '../../assets/images/plans/lean-cut.card.webp';
import img93 from '../../assets/images/plans/lean-cut.detail.webp';
import img94 from '../../assets/images/plans/mediterranean-reset.card.webp';
import img95 from '../../assets/images/plans/mediterranean-reset.detail.webp';
import img96 from '../../assets/images/plans/plant-forward.card.webp';
import img97 from '../../assets/images/plans/plant-forward.detail.webp';
import img98 from '../../assets/images/plans/strength-build.card.webp';
import img99 from '../../assets/images/plans/strength-build.detail.webp';

/** Fixture/marketing image key → bundled WebP asset. */
export const IMAGE_ASSETS: Record<string, ImageRequireSource> = {
    'dietitians/hala-rizk.portrait': img0,
    'dietitians/karim-nassar.portrait': img1,
    'dietitians/layla-haddad.portrait': img2,
    'dietitians/maya-darwish.portrait': img3,
    'dietitians/tarek-shammas.portrait': img4,
    'diets/balanced.hero': img5,
    'diets/dairy-free.hero': img6,
    'diets/family.hero': img7,
    'diets/gluten-free.hero': img8,
    'diets/high-protein.hero': img9,
    'diets/low-carb.hero': img10,
    'diets/mediterranean.hero': img11,
    'diets/muscle-gain.hero': img12,
    'diets/office.hero': img13,
    'diets/pescatarian.hero': img14,
    'diets/plant-based.hero': img15,
    'diets/vegetarian.hero': img16,
    'diets/weight-management.hero': img17,
    'discover/diets.tile': img18,
    'discover/meals.tile': img19,
    'discover/plans.tile': img20,
    'discover/tools.tile': img21,
    'dishes/calamari-rocket-salad.card': img22,
    'dishes/calamari-rocket-salad.detail': img23,
    'dishes/charred-aubergine-chickpea.card': img24,
    'dishes/charred-aubergine-chickpea.detail': img25,
    'dishes/citrus-sea-bass-green-beans.card': img26,
    'dishes/citrus-sea-bass-green-beans.detail': img27,
    'dishes/courgette-walnut-pasta.card': img28,
    'dishes/courgette-walnut-pasta.detail': img29,
    'dishes/garden-omelette-spinach.card': img30,
    'dishes/garden-omelette-spinach.detail': img31,
    'dishes/grilled-halloumi-rocket.card': img32,
    'dishes/grilled-halloumi-rocket.detail': img33,
    'dishes/harbour-prawn-quinoa.card': img34,
    'dishes/harbour-prawn-quinoa.detail': img35,
    'dishes/herbed-chicken-freekeh.card': img36,
    'dishes/herbed-chicken-freekeh.detail': img37,
    'dishes/lemon-tahini-salmon.card': img38,
    'dishes/lemon-tahini-salmon.detail': img39,
    'dishes/mint-yoghurt-chicken-skewers.card': img40,
    'dishes/mint-yoghurt-chicken-skewers.detail': img41,
    'dishes/morning-oats-dates-almonds.card': img42,
    'dishes/morning-oats-dates-almonds.detail': img43,
    'dishes/pistachio-pomegranate-bowl.card': img44,
    'dishes/pistachio-pomegranate-bowl.detail': img45,
    'dishes/red-bean-pepper-chilli.card': img46,
    'dishes/red-bean-pepper-chilli.detail': img47,
    'dishes/roasted-cauliflower-wrap.card': img48,
    'dishes/roasted-cauliflower-wrap.detail': img49,
    'dishes/slow-braised-lamb-bulgur.card': img50,
    'dishes/slow-braised-lamb-bulgur.detail': img51,
    'dishes/smoky-tofu-kale-bowl.card': img52,
    'dishes/smoky-tofu-kale-bowl.detail': img53,
    'dishes/spiced-lentil-pumpkin-stew.card': img54,
    'dishes/spiced-lentil-pumpkin-stew.detail': img55,
    'dishes/sunrise-labneh-sourdough.card': img56,
    'dishes/sunrise-labneh-sourdough.detail': img57,
    'dishes/tempeh-broccoli-stir-fry.card': img58,
    'dishes/tempeh-broccoli-stir-fry.detail': img59,
    'dishes/turkey-sweet-potato-hash.card': img60,
    'dishes/turkey-sweet-potato-hash.detail': img61,
    'for-business/clinic.tile': img62,
    'for-business/corporate.tile': img63,
    'for-business/gym.tile': img64,
    'for-business/hero.hero': img65,
    'for-business/wholesale.tile': img66,
    'how-it-works/eat.tile': img67,
    'how-it-works/plan.tile': img68,
    'how-it-works/target.tile': img69,
    'how-it-works/tell.tile': img70,
    'kitchens/northwind-provisions.card': img71,
    'kitchens/northwind-provisions.detail': img72,
    'kitchens/olive-terrace-counter.card': img73,
    'kitchens/olive-terrace-counter.detail': img74,
    'kitchens/riverstone-meal-works.card': img75,
    'kitchens/riverstone-meal-works.detail': img76,
    'kitchens/saffron-and-sea.card': img77,
    'kitchens/saffron-and-sea.detail': img78,
    'kitchens/the-daily-pot.card': img79,
    'kitchens/the-daily-pot.detail': img80,
    'kitchens/verdant-kitchen.card': img81,
    'kitchens/verdant-kitchen.detail': img82,
    'landing/hero.hero': img83,
    'plans/balanced-week.card': img84,
    'plans/balanced-week.detail': img85,
    'plans/coastal-light.card': img86,
    'plans/coastal-light.detail': img87,
    'plans/desk-lunch-club.card': img88,
    'plans/desk-lunch-club.detail': img89,
    'plans/everyday-family-box.card': img90,
    'plans/everyday-family-box.detail': img91,
    'plans/lean-cut.card': img92,
    'plans/lean-cut.detail': img93,
    'plans/mediterranean-reset.card': img94,
    'plans/mediterranean-reset.detail': img95,
    'plans/plant-forward.card': img96,
    'plans/plant-forward.detail': img97,
    'plans/strength-build.card': img98,
    'plans/strength-build.detail': img99,
};

/** How many families and files the manifest was generated from — used by the drift test. */
export const IMAGE_ASSET_COUNT = 100;
