#!/usr/bin/env node
/**
 * Generates `src/keys.generated.ts` — a typed union of every translation key, derived from the
 * English catalogue (the reference locale).
 *
 * Plural variants collapse to their base key, because that is what `t()` is called with:
 * `notifications.count_one` and `notifications.count_other` both become `notifications.count`.
 *
 * Usage:
 *   node scripts/generate-keys.mjs          # write
 *   node scripts/generate-keys.mjs --check  # fail if the committed file is stale
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import {
    PACKAGE_ROOT,
    PLURAL_SUFFIXES,
    REFERENCE_LOCALE,
    flatten,
    listNamespaces,
    readCatalogue,
    stripPluralSuffix,
} from './catalogue-utils.mjs';

const OUTPUT_PATH = join(PACKAGE_ROOT, 'src', 'keys.generated.ts');

const namespaces = await listNamespaces(REFERENCE_LOCALE);

/** @type {Map<string, string[]>} */
const keysByNamespace = new Map();

for (const namespace of namespaces) {
    const catalogue = await readCatalogue(REFERENCE_LOCALE, namespace);
    const keys = new Set();
    for (const key of flatten(catalogue).keys()) {
        keys.add(stripPluralSuffix(key));
    }
    keysByNamespace.set(namespace, [...keys].sort());
}

const union = (values) =>
    values.length === 0 ? 'never' : values.map((value) => `'${value}'`).join('\n    | ');

const namespaceEntries = namespaces
    .map((namespace) => {
        const keys = keysByNamespace.get(namespace) ?? [];
        return `  readonly ${JSON.stringify(namespace)}:\n    | ${union(keys)};`;
    })
    .join('\n');

const qualifiedKeys = namespaces.flatMap((namespace) =>
    (keysByNamespace.get(namespace) ?? []).map((key) => `${namespace}:${key}`),
);

const runtimeList = qualifiedKeys.map((key) => `  '${key}',`).join('\n');

const total = qualifiedKeys.length;

const contents = `/*
 * AUTOGENERATED by @healthy360/i18n — do not edit by hand.
 * Source: packages/i18n/catalogues/${REFERENCE_LOCALE}/*.json
 * Regenerate: pnpm --filter @healthy360/i18n gen:keys
 *
 * ${total} keys across ${namespaces.length} namespaces. Plural variants (${PLURAL_SUFFIXES.join(
     ', ',
 )})
 * are collapsed to their base key, because that is the key t() is called with.
 */

/** Keys available in each namespace, unqualified. */
export interface NamespaceKeys {
${namespaceEntries}
}

/** Every key in \`namespace:key\` form — the shape an unscoped \`t()\` accepts. */
export type TranslationKey = {
  [N in keyof NamespaceKeys]: \`\${N & string}:\${NamespaceKeys[N]}\`;
}[keyof NamespaceKeys];

export const PLURAL_SUFFIXES = ${JSON.stringify(PLURAL_SUFFIXES)} as const;

/** Runtime list, for parity assertions and development tooling. */
export const TRANSLATION_KEYS: readonly TranslationKey[] = [
${runtimeList}
];

const TRANSLATION_KEY_SET: ReadonlySet<string> = new Set(TRANSLATION_KEYS);

export function isTranslationKey(value: unknown): value is TranslationKey {
  return typeof value === 'string' && TRANSLATION_KEY_SET.has(value);
}
`;

const check = process.argv.includes('--check');

let existing = null;
try {
    existing = await readFile(OUTPUT_PATH, 'utf8');
} catch {
    // First run: the generated file does not exist yet.
}

if (existing === contents) {
    console.log(`unchanged  src/keys.generated.ts (${total} keys)`);
    process.exit(0);
}

if (check) {
    console.error(
        'DRIFT      src/keys.generated.ts is out of date. Run: pnpm --filter @healthy360/i18n gen:keys',
    );
    process.exit(1);
}

await writeFile(OUTPUT_PATH, contents, 'utf8');
console.log(`written    src/keys.generated.ts (${total} keys)`);
