<?php

declare(strict_types=1);

use Healthy360\Identity\Http\Controllers\ConfirmPasswordController;
use Healthy360\Identity\Http\Controllers\ResendEmailVerificationController;
use Healthy360\Identity\Http\Controllers\SignedEmailVerificationController;
use Healthy360\Identity\Http\Controllers\TokenController;
use Healthy360\Identity\Http\Controllers\TwoFactorController;
use Illuminate\Support\Facades\Route;
use Laravel\Fortify\Http\Controllers\AuthenticatedSessionController;
use Laravel\Fortify\Http\Controllers\NewPasswordController;
use Laravel\Fortify\Http\Controllers\PasswordResetLinkController;
use Laravel\Fortify\Http\Controllers\RegisteredUserController;
use Laravel\Fortify\Http\Controllers\TwoFactorAuthenticatedSessionController;

/*
|--------------------------------------------------------------------------
| Healthy360 authentication — /api/v1/auth
|--------------------------------------------------------------------------
|
| Registered by bootstrap/app.php with config('fortify.prefix') and
| config('fortify.middleware'). Fortify's own route file is disabled
| (Fortify::ignoreRoutes()) for three reasons:
|
|  * three stock endpoints answer with bare JSON rather than the Healthy360
|    envelope (two-factor QR code, secret key, recovery codes);
|  * DELETE two-factor-authentication must carry the `step-up` middleware,
|    which Fortify's route file cannot express;
|  * password confirmation must work for bearer tokens, and Fortify's
|    controller writes the confirmation into the session unconditionally.
|
| Everything Fortify does serve correctly is still served by Fortify's own
| controllers, bound to Healthy360 JSON responses in app/Http/Responses.
|
| `guest` middleware is deliberately absent: Laravel's implementation
| redirects an already-authenticated caller, which would put a non-envelope
| body on the wire.
|
*/

$auth = 'auth:sanctum';
$twoFactorLimiter = config('fortify.limiters.two-factor');
$verificationLimiter = config('fortify.limiters.verification');
$forgotPasswordLimiter = config('fortify.limiters.forgot-password');

/*
| Session credentials (first-party origins).
|
| `stateful` rejects a session-less caller with an actionable error instead
| of quietly "succeeding" without issuing a cookie; native clients use
| POST /token below.
*/
Route::post('/register', [RegisteredUserController::class, 'store'])->name('register.store');

Route::post('/login', [AuthenticatedSessionController::class, 'store'])
    ->middleware('stateful')
    ->name('login.store');

Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])
    ->middleware([$auth, 'stateful'])
    ->name('logout');

Route::post('/two-factor-challenge', [TwoFactorAuthenticatedSessionController::class, 'store'])
    ->middleware(array_filter(['stateful', $twoFactorLimiter ? 'throttle:'.$twoFactorLimiter : null]))
    ->name('two-factor.login.store');

/*
| Native credentials: a Sanctum personal access token bound to a device.
*/
Route::post('/token', TokenController::class)->name('token.store');

/*
| Password reset.
*/
Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])
    ->middleware(array_filter([$forgotPasswordLimiter ? 'throttle:'.$forgotPasswordLimiter : null]))
    ->name('password.email');

Route::post('/reset-password', [NewPasswordController::class, 'store'])->name('password.update');

/*
| Email verification. The signed link is generated by Laravel's VerifyEmail
| notification against the `verification.verify` route name, so the name is
| part of the contract.
*/
Route::post('/email/verification-notification', ResendEmailVerificationController::class)
    ->middleware(array_filter([$auth, $verificationLimiter ? 'throttle:'.$verificationLimiter : null]))
    ->name('verification.send');

Route::get('/verify-email/{id}/{hash}', SignedEmailVerificationController::class)
    ->middleware(array_filter(['signed', $verificationLimiter ? 'throttle:'.$verificationLimiter : null]))
    ->name('verification.verify');

/*
| Step-up: recent password confirmation for sensitive actions.
*/
Route::post('/confirm-password', [ConfirmPasswordController::class, 'store'])
    ->middleware($auth)
    ->name('password.confirm.store');

Route::get('/confirmed-password-status', [ConfirmPasswordController::class, 'show'])
    ->middleware($auth)
    ->name('password.confirmation');

/*
| TOTP two-factor authentication.
*/
Route::middleware($auth)->group(function (): void {
    Route::post('/two-factor-authentication', [TwoFactorController::class, 'store'])
        ->name('two-factor.enable');

    Route::post('/confirmed-two-factor-authentication', [TwoFactorController::class, 'confirm'])
        ->name('two-factor.confirm');

    Route::delete('/two-factor-authentication', [TwoFactorController::class, 'destroy'])
        ->middleware('step-up')
        ->name('two-factor.disable');

    Route::get('/two-factor-qr-code', [TwoFactorController::class, 'qrCode'])
        ->name('two-factor.qr-code');

    Route::get('/two-factor-secret-key', [TwoFactorController::class, 'secretKey'])
        ->name('two-factor.secret-key');

    Route::get('/two-factor-recovery-codes', [TwoFactorController::class, 'recoveryCodes'])
        ->name('two-factor.recovery-codes');

    Route::post('/two-factor-recovery-codes', [TwoFactorController::class, 'regenerateRecoveryCodes'])
        ->name('two-factor.regenerate-recovery-codes');
});
