import { createHmac } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import type { APIRequestContext, Locator, Page } from '@playwright/test';
import { expect, test } from '@playwright/test';

/**
 * The one helper module every spec imports.
 *
 * It replaces two: the mock-world helpers that used to live here (personas invented in
 * `packages/api-client/src/mock`, plus a `selectScenario` that swapped worlds at runtime) and the
 * acceptance suite's helpers, which spoke to the real API and are now the only kind there is. The
 * scenario machinery is gone rather than ported — there is one world now, and it is PostgreSQL.
 *
 * ## The world these helpers assume
 *
 * `apps/api/database/seeders/DatabaseSeeder.php`, run against a `local` environment. That is:
 * six kitchens on the marketplace, eight published plans, forty-odd published meals across four of
 * the kitchens, and the demonstration tenants below. Nothing here hard-codes an identifier — every
 * record is reached by *slug*, because slugs are stable across a reseed and UUIDv7 primary keys are
 * regenerated by every one.
 */

/* ── where things are ────────────────────────────────────────────────────────────────────────── */

/** The Laravel API. Matches what `dist-api` was built against (`EXPO_PUBLIC_API_URL`). */
export const API_URL = process.env['EXPO_PUBLIC_API_URL'] ?? 'http://localhost:8080';

/** The static server in front of `dist-api`. Mirrors `BASE_URL` in `playwright.config.ts`. */
export const APP_URL =
    process.env['E2E_BASE_URL'] ?? process.env['BASE_URL'] ?? 'http://localhost:4173';

/**
 * The Laravel log the dev mailer writes rendered messages to.
 *
 * There is no mail server in the local stack, so a verification link is read from here. Resolved
 * from `__dirname` rather than `import.meta.url`: Playwright transpiles these files to CommonJS,
 * where `import.meta` is not available at all. Override with `MAIL_LOG_PATH` for an unusual layout.
 */
export const MAIL_LOG =
    process.env['MAIL_LOG_PATH'] ?? resolve(__dirname, '../../../api/storage/logs/laravel.log');

/* ── who signs in ────────────────────────────────────────────────────────────────────────────── */

/** Seeded demo accounts share one password locally (`DemoTenantSeeder`, `DemoCustomerSeeder`). */
export const DEMO_PASSWORD = 'password';

/**
 * **The kitchen.** `organisation_owner` *and* `kitchen_manager` at Verdant Kitchen, one branch
 * (Al Quoz). Every kitchen-workspace journey signs in as this account, and only as this account:
 * `dietitian@cedar.test` holds a plain `member` role at Verdant and is refused by the catalogue
 * endpoints with `403`, which reads in a spec as a broken screen rather than as the correct answer.
 */
export const KITCHEN_OWNER = 'owner@verdant.test';

/**
 * **The multi-organisation person.** A member at Cedar Clinic *and* at Verdant Kitchen — one
 * identity, two organisations, different roles — so the organisation picker has something to pick
 * between. The Cedar membership is scoped to the Hamra branch by the server.
 */
export const CEDAR_DIETITIAN = 'dietitian@cedar.test';

/** **The clinic owner.** `organisation_owner` at Cedar Clinic, membership not branch-scoped. */
export const CEDAR_OWNER = 'owner@cedar.test';

/**
 * **The corporate buyer.** `organisation_owner` at Acme Wellness, which is the organisation the
 * seeded programme, agreement and negotiated catalogue actually belong to
 * (`B2bProgrammesDemoSeeder`). Cedar Clinic buys nothing from anybody, so the B2B journeys sign in
 * here rather than as the dietitian they used to use in the mock world.
 */
export const CORPORATE_BUYER = 'buyer@acme-wellness.test';

/**
 * **The consumer.** Verified email, activated account, one saved address inside Verdant's Al Quoz
 * delivery zone, one declared allergy (`DemoCustomerSeeder`). No membership anywhere, so the landing
 * resolver sends this account straight to `/customer` rather than to the organisation picker.
 */
export const CONSUMER_EMAIL = 'nour@healthy360.test';

/** **The two-factor account**, and the shared secret it is enrolled with (`DEMO_TOTP_SECRET`). */
export const TWO_FACTOR_EMAIL = 'two-factor@cedar.test';
export const TWO_FACTOR_SECRET = 'JBSWY3DPEHPK3PXP';

/** Organisation slugs, which are also the picker's test identifiers. */
export const VERDANT_SLUG = 'verdant-kitchen';
export const CEDAR_SLUG = 'cedar-clinic';
export const ACME_SLUG = 'acme-wellness';

/* ── what is on the marketplace ──────────────────────────────────────────────────────────────── */

/**
 * The kitchens the **consumer directory** lists, by slug.
 *
 * Six organisations are seeded — `verdant-kitchen` from `DemoTenantSeeder` and five more from
 * `MarketplaceKitchensSeeder` — but `/kitchens` is not a list of kitchens, it is a list of kitchens
 * *a shopper can buy from*: `KitchensScreen` always sends `channels: LISTING_CHANNELS` (`b2c_web`
 * and `marketplace`), so a kitchen with neither never appears. These four have one.
 *
 * Card test identifiers are `kitchen-card-{slug}`.
 */
export const LISTED_KITCHEN_SLUGS = [
    'verdant-kitchen',
    'the-daily-pot',
    'riverstone-meal-works',
    'saffron-and-sea',
] as const;

/**
 * Seeded kitchens the consumer directory must **not** list, and why.
 *
 * `northwind-provisions` sells wholesale and corporate only; `olive-terrace-counter` sells over the
 * counter only. Neither runs a consumer listing channel, so a shopper has no way to order from them
 * and the directory says so by leaving them out. Their absence is asserted rather than assumed —
 * a channel filter that stopped being applied would otherwise show two kitchens nobody can buy from.
 */
export const UNLISTED_KITCHEN_SLUGS = ['northwind-provisions', 'olive-terrace-counter'] as const;

/** The eight published plans (`MarketplacePlansSeeder`). Card ids are `plan-card-{slug}`. */
export const PUBLISHED_PLAN_SLUGS = [
    'balanced-week',
    'plant-forward',
    'desk-lunch-club',
    'coastal-light',
    'mediterranean-reset',
    'everyday-family-box',
    'strength-build',
    'lean-cut',
] as const;

/** The plan every commerce journey configures, and the name it carries. */
export const PLAN_SLUG = 'balanced-week';
export const PLAN_NAME = 'Balanced Week';

/**
 * Why a subscription cannot currently be configured against the seeded API.
 *
 * `GET /marketplace/meal-plans` publishes every commitment with `total_price: null` — a
 * multi-configuration plan has no single plan-level figure, and the server refuses to invent one.
 * `mapDuration` used to drop such durations, which emptied the configurator's third step and made
 * subscriptions unreachable; it now keeps them, and the screens derive the selected variant's
 * total. These skips are therefore a **tripwire**, not an expectation: they fire only if that
 * regression returns, and the sentence below says exactly what broke when they do.
 */
export const NO_PRICED_DURATIONS =
    'The configurator’s duration step rendered no commitment options. Either the plan lost its ' +
    'durations on the wire, or `mapDuration` has gone back to dropping durations whose ' +
    '`total_price` is null (the derived-total fix in plan-mappers/plan-detail/plan-duration-' +
    'selector) — no subscription can be created through the UI while this holds.';

/** A published Verdant meal, hand-authored in `DemoTenantSeeder` rather than ported from a fixture. */
export const MEAL_SLUG = 'grilled-chicken-freekeh';
export const MEAL_NAME = 'Grilled chicken and freekeh';

/* ── is the stack there at all ───────────────────────────────────────────────────────────────── */

/** Where the web build keeps the bearer token (`src/session/storage.ts`). */
const SESSION_TOKEN_KEY = 'h360.session-token';

export interface StackStatus {
    readonly api: boolean;
    readonly mailLog: boolean;
    readonly reason: string;
}

async function reachable(url: string): Promise<boolean> {
    try {
        // Generous on purpose: the Windows Docker stack answers /up in ~5-6s cold (php-fpm over a
        // bind mount), and a probe that times out on a slow-but-alive stack skips the whole suite.
        const response = await fetch(url, { signal: AbortSignal.timeout(15_000) });
        return response.ok;
    } catch {
        return false;
    }
}

async function fileReadable(path: string): Promise<boolean> {
    try {
        await readFile(path);
        return true;
    } catch {
        return false;
    }
}

/**
 * Probes the stack once per file.
 *
 * A missing stack is not a failing test — it is a missing prerequisite — so a spec skips with an
 * instruction instead of timing out five times over. Mail is read from the API's log rather than a
 * mail server, so the "inbox" prerequisite is simply that the log file is readable.
 */
export async function probeStack(): Promise<StackStatus> {
    const [api, mailLog] = await Promise.all([reachable(`${API_URL}/up`), fileReadable(MAIL_LOG)]);

    const missing = [
        api ? null : `the API at ${API_URL}`,
        mailLog ? null : `a readable mail log at ${MAIL_LOG} (the API must have run at least once)`,
    ].filter((entry): entry is string => entry !== null);

    return {
        api,
        mailLog,
        reason:
            missing.length === 0
                ? ''
                : `These specs need ${missing.join(' and ')}. Start it with \`docker compose up -d --wait\`.`,
    };
}

export function skipUnlessStackIsUp(status: StackStatus, mailLogRequired = false): void {
    test.skip(!status.api || (mailLogRequired && !status.mailLog), status.reason);
}

/* ── signing in ──────────────────────────────────────────────────────────────────────────────── */

/**
 * How long a *chain* of round trips is allowed to take, as opposed to a single assertion.
 *
 * The project-wide `expect` timeout is 20 s, which is right for "this element should appear once its
 * data has arrived" — one request. Signing in is not one request: it is `POST /auth/login`, then
 * `GET /me`, then the landing resolver, then whichever screen that picks fetching its own data. On
 * the Windows Docker stack each leg answers in six to nine seconds (php-fpm over a bind mount), so
 * the chain routinely costs thirty and the assertion at the end of it was failing on a stack that
 * was working perfectly. Choosing an organisation is the same shape: `PUT /me/context`, a refetch of
 * `/me`, then the workspace's own reads.
 *
 * Raising the global budget instead would have hidden a genuinely stuck single request behind two
 * minutes of patience everywhere. This is deliberately narrow: it applies to the two helpers that
 * really do wait on several requests, and nowhere else.
 *
 * Two minutes looks extravagant and is not: it is a *ceiling*, paid only when something is wrong.
 * The observed cost of a sign-in on this stack is thirty to forty seconds idle and past seventy-five
 * when two workers are both mid-journey — the API container answers `/up` itself in five to eight
 * seconds — so a budget that merely covered the idle case failed on a stack that was working. On
 * CI's `artisan serve` the whole chain lands in well under a second and this number is never
 * approached.
 */
export const JOURNEY_TIMEOUT = 120_000;

/**
 * Somewhere authenticated, whichever of them this account lands on.
 *
 * Where a person lands is the *server's* decision and it differs per account: a consumer with no
 * membership goes to the customer home, somebody with two memberships and no remembered context
 * goes to the organisation picker, and anybody whose last workspace the API still remembers
 * (`user_profiles.last_organisation_id`) is routed straight past it to the workspace selector. All
 * three are "signed in", so all three are accepted.
 */
export function authenticatedLandmark(page: Page): Locator {
    return page
        .getByTestId('organisation-picker-screen')
        .or(page.getByTestId('workspace-selector-screen'))
        .or(page.getByTestId('branch-picker-screen'))
        .or(page.getByTestId('consumer-home-screen'))
        .first();
}

/**
 * Signs in through the real screen and waits until the session is genuinely established.
 *
 * Two waits, and the second is the one that was missing. The old helper waited for the sign-in
 * screen to be *hidden*, which the router satisfies the instant it starts replacing the route —
 * before the token has been written to storage. A `page.goto` issued immediately afterwards then
 * raced the write and landed on a signed-out screen, which on a slow stack looked exactly like an
 * application bug. So: wait for an authenticated landmark to paint, and then for the credential to
 * actually be in `localStorage`.
 */
export async function signIn(
    page: Page,
    email: string = CONSUMER_EMAIL,
    password: string = DEMO_PASSWORD,
): Promise<void> {
    /*
     * Attempted twice, and only for one specific failure — see `submitSignIn`.
     *
     * A sign-in that lands on the *anonymous* marketplace is not a slow sign-in and no amount of
     * waiting fixes it: the credential was accepted, `router.replace('/')` ran, and the home router
     * then resolved `unauthenticated` because the session had not become authenticated. Nothing in
     * the application retries from there, so the page sits on the public landing for as long as the
     * assertion is willing to wait. It is reproducible on this stack — see the note in
     * `submitSignIn` — and one clean re-attempt is what keeps a local run usable while it stands.
     */
    if (await submitSignIn(page, email, password)) return;
    if (await submitSignIn(page, email, password)) return;

    throw new Error(
        `Signing in as ${email} succeeded but the application settled on the anonymous ` +
            'marketplace landing, twice. The credential was accepted and the home router then ' +
            'resolved `unauthenticated`, which is what happens when the `GET /me` that follows ' +
            'sign-in does not land — the session machine has no retry from that state, so the ' +
            'page stays anonymous with a valid token in storage.',
    );
}

/**
 * One sign-in attempt. `true` when it reached an authenticated landmark.
 *
 * Returns `false` only for the anonymous-landing outcome above. Every other failure throws, because
 * every other failure is worth reporting rather than retrying: a refused credential is a finding, a
 * rate limit is a finding, and a landmark that simply never paints is a timeout with a call log
 * attached.
 */
async function submitSignIn(page: Page, email: string, password: string): Promise<boolean> {
    await page.goto('/sign-in');
    await expect(page.getByTestId('sign-in-screen')).toBeVisible();

    /*
     * Filled *and read back*, which is not belt-and-braces.
     *
     * The export hydrates after its first paint, and `sign-in-screen` is visible before the form
     * behind it is interactive: a `fill` that lands in that window writes into a node React then
     * replaces, and the submit that follows posts an empty form. That produced the most confusing
     * failure in this suite — a sign-in that "timed out" on a page whose email box was blank and
     * whose submit button was enabled and idle. Asserting the value is what makes the fill a fact
     * rather than an attempt.
     */
    const emailInput = page.getByTestId('sign-in-email').locator('input').first();
    const passwordInput = page.getByTestId('sign-in-password').locator('input').first();
    await emailInput.fill(email);
    await passwordInput.fill(password);
    await expect(emailInput).toHaveValue(email);
    await expect(passwordInput).toHaveValue(password);

    await page.getByTestId('sign-in-submit').click();

    /*
     * A refused credential is reported as a refusal rather than as a timeout. Without this, a rate
     * limit or a wrong password reads as "the landmark never appeared", which sends whoever is
     * debugging it to look at the wrong screen entirely.
     */
    /*
     * Three outcomes are waited for at once, because two of them are answers rather than delays.
     *
     * A refused credential is reported as a refusal: without this, a rate limit or a wrong password
     * reads as "the landmark never appeared", which sends whoever is debugging it to the wrong
     * screen entirely. And `landing-screen` — the *anonymous* marketplace — is the outcome
     * described above: an accepted credential whose session never became authenticated. No account
     * in this suite legitimately lands there, so seeing it is a result, not a wait.
     */
    const landmark = authenticatedLandmark(page);
    const refusal = page.getByTestId('sign-in-error');
    const anonymous = page.getByTestId('landing-screen');
    await expect(landmark.or(refusal).or(anonymous).first()).toBeVisible({
        timeout: JOURNEY_TIMEOUT,
    });

    if ((await refusal.count()) > 0) {
        throw new Error(`Signing in as ${email} was refused: ${await refusal.innerText()}`);
    }
    if ((await landmark.count()) === 0) return false;

    await expect(landmark).toBeVisible({ timeout: JOURNEY_TIMEOUT });
    await expect
        .poll(
            async () =>
                page.evaluate((key) => globalThis.localStorage.getItem(key), SESSION_TOKEN_KEY),
            {
                message: 'the application should have persisted a bearer token',
                timeout: JOURNEY_TIMEOUT,
            },
        )
        .not.toBeNull();

    return true;
}

/** Signs in and asserts the credential was refused, without navigating anywhere. */
export async function signInExpectingRefusal(
    page: Page,
    email: string,
    password: string,
): Promise<void> {
    await page.goto('/sign-in');
    await expect(page.getByTestId('sign-in-screen')).toBeVisible();
    await page.getByTestId('sign-in-email').locator('input').first().fill(email);
    await page.getByTestId('sign-in-password').locator('input').first().fill(password);
    await page.getByTestId('sign-in-submit').click();
    await expect(page.getByTestId('sign-in-error')).toBeVisible();
    await expect(page.getByTestId('sign-in-screen')).toBeVisible();
}

/** The bearer token the running application is holding, read from its own storage. */
export async function readSessionToken(page: Page): Promise<string> {
    const token = await page.evaluate(
        (key) => globalThis.localStorage.getItem(key),
        SESSION_TOKEN_KEY,
    );
    expect(token, 'the application should have stored a bearer token').not.toBeNull();
    return token as string;
}

/* ── choosing a workspace ────────────────────────────────────────────────────────────────────── */

/**
 * Picks an organisation and lands on the workspace selector.
 *
 * The picker is *navigated to* rather than assumed to be where the sign-in landed, and that is a
 * property of the real backend rather than a convenience: the API remembers the last workspace on
 * the profile, so the second run of any spec would otherwise be routed straight past the screen it
 * is about. Navigating makes every one of them idempotent without weakening it — the memberships
 * being asserted are still the ones PostgreSQL holds.
 *
 * There is no branch step. `/me` reports a membership's branch as a single scoped id, so
 * `membershipRequiresBranchSelection` (`src/session/machine.ts`) is never true against this API and
 * `PUT /me/context` applies the scoped branch itself. The branch picker is therefore unreachable
 * here; it is exercised by `src/screens/screens.test.tsx` instead.
 */
export async function openOrganisationPicker(page: Page): Promise<void> {
    await page.goto('/select-organisation');
    await expect(page.getByTestId('organisation-picker-screen')).toBeVisible({
        timeout: JOURNEY_TIMEOUT,
    });
}

/**
 * The name the workspace badge renders for each organisation this suite signs into.
 *
 * Needed because {@link selectOrganisation} has to be able to assert *which* workspace it ended up
 * in even when no choice was offered — see below — and the only thing on screen at that point is the
 * organisation's display name.
 */
const ORGANISATION_NAMES: Readonly<Record<string, string>> = {
    [VERDANT_SLUG]: 'Verdant Kitchen',
    [CEDAR_SLUG]: 'Cedar Clinic',
    [ACME_SLUG]: 'Acme Wellness',
};

export async function selectOrganisation(page: Page, slug: string): Promise<void> {
    const name = ORGANISATION_NAMES[slug];
    if (name === undefined) throw new Error(`No display name recorded for "${slug}".`);

    await page.goto('/select-organisation');

    const picker = page.getByTestId('organisation-picker-screen');
    const workspace = page.getByTestId('workspace-selector-screen');
    await expect(picker.or(workspace).first()).toBeVisible({ timeout: JOURNEY_TIMEOUT });

    /*
     * The picker only *offers* a choice when there is one to make.
     *
     * `organisation-picker-screen.tsx` auto-selects a person's only selectable membership and
     * replaces the route — it renders `organisation-picker-autoskip` for a moment and then the
     * workspace. Three of this suite's four staff personas hold exactly one membership
     * (`owner@verdant.test`, `owner@cedar.test`, `buyer@acme-wellness.test`), so for them there is
     * no `organisation-{slug}` control to press and waiting for one is waiting forever. Only
     * `dietitian@cedar.test` belongs to two organisations and therefore actually sees the list.
     *
     * Either way the assertion at the end is the same and is the one that matters: the workspace
     * this helper leaves the page in belongs to the organisation that was asked for.
     */
    if ((await page.getByTestId(`organisation-${slug}`).count()) > 0) {
        await page.getByTestId(`organisation-${slug}`).click();
    }

    await expect(workspace).toBeVisible({ timeout: JOURNEY_TIMEOUT });
    await expect(page.getByTestId('workspace-organisation')).toContainText(name, {
        timeout: JOURNEY_TIMEOUT,
    });
}

/** Verdant Kitchen, where `owner@verdant.test` holds `kitchen_manager`. */
export async function selectVerdantKitchenContext(page: Page): Promise<void> {
    await selectOrganisation(page, VERDANT_SLUG);
}

/** Cedar Clinic. The dietitian's membership is scoped to Hamra, which the server applies itself. */
export async function selectCedarContext(page: Page): Promise<void> {
    await selectOrganisation(page, CEDAR_SLUG);
}

/** Acme Wellness — the buyer organisation the corporate programme belongs to. */
export async function selectAcmeContext(page: Page): Promise<void> {
    await selectOrganisation(page, ACME_SLUG);
}

/* ── talking to the API directly ─────────────────────────────────────────────────────────────── */

export interface ApiCallOptions {
    readonly token?: string | undefined;
    readonly headers?: Record<string, string> | undefined;
    readonly data?: unknown;
}

/**
 * A direct call to the API from the browser context, bypassing the UI.
 *
 * Used only for the things a UI cannot express: following a signed verification link, probing a
 * context the application would never claim, resolving an identifier the screens address by slug,
 * and confirming that a revoked token is really dead.
 */
export async function apiRequest(
    request: APIRequestContext,
    method: 'get' | 'post' | 'put' | 'patch' | 'delete',
    path: string,
    options: ApiCallOptions = {},
) {
    const headers: Record<string, string> = {
        Accept: 'application/json',
        'X-Client-Request-Id': `e2e-${String(Date.now())}`,
        ...(options.token === undefined ? {} : { Authorization: `Bearer ${options.token}` }),
        ...options.headers,
    };

    const url = path.startsWith('http') ? path : `${API_URL}${path}`;
    return request[method](url, {
        headers,
        ...(options.data === undefined ? {} : { data: options.data }),
    });
}

/** Exchanges credentials for a second, independent bearer token bound to its own device. */
export async function issueToken(
    request: APIRequestContext,
    email: string,
    deviceName: string,
    platform: 'web' | 'ios' | 'android' = 'android',
): Promise<{ token: string; deviceId: string }> {
    const response = await apiRequest(request, 'post', '/api/v1/auth/token', {
        data: { email, password: DEMO_PASSWORD, device_name: deviceName, platform },
    });
    expect(response.status(), await response.text()).toBe(201);

    const body = (await response.json()) as {
        data: { token: string; device: { id: string } };
    };
    return { token: body.data.token, deviceId: body.data.device.id };
}

/** The signed-in user's own identifier, straight from `/me`. */
export async function readUserId(request: APIRequestContext, token: string): Promise<string> {
    const response = await apiRequest(request, 'get', '/api/v1/me', { token });
    expect(response.status(), await response.text()).toBe(200);
    const body = (await response.json()) as { data: { user: { id: string } } };
    return body.data.user.id;
}

/* ── reading the mail the stack "sent" ───────────────────────────────────────────────────────── */

/**
 * The newest verification link the API has logged for a given needle.
 *
 * With no mail server, the rendered message is appended to the Laravel log, so this reads that file
 * instead of polling an inbox. It is polled rather than awaited on a hook because the mail is queued
 * and the queue worker is a separate process. Each entry is the full MIME message, quoted-printable
 * encoded.
 *
 * **The needle is the user's identifier, not their address**, and that is this stack's doing rather
 * than a preference: the mail logger redacts recipients (`To: a***@healthy360.test`), so correlating
 * by address matches nothing at all. The signed URL embeds the user id — `/verify-email/{id}/{hash}`
 * — which is both unambiguous and impossible to redact without breaking the link, so that is what
 * the entries are matched on. Any string may be passed; the id is simply the one that works here.
 */
export async function fetchVerificationLink(needle: string, attempts = 60): Promise<string> {
    for (let attempt = 0; attempt < attempts; attempt += 1) {
        let raw: string;
        try {
            raw = await readFile(MAIL_LOG, 'utf8');
        } catch {
            raw = '';
        }

        // Laravel log entries begin with a `[timestamp]` prefix; split so each block is one message.
        const entries = raw.split(/(?=^\[\d{4}-\d\d-\d\d[ T])/m);
        for (let index = entries.length - 1; index >= 0; index -= 1) {
            const decoded = decodeQuotedPrintable(entries[index] ?? '');
            if (!decoded.includes(needle)) continue;
            const link = extractVerificationLink(decoded);
            if (link !== null) return link;
        }

        await new Promise((settle) => setTimeout(settle, 500));
    }

    throw new Error(
        `No verification mail mentioning ${needle} was logged within ${String(attempts * 500)}ms ` +
            `(${MAIL_LOG}).`,
    );
}

/**
 * Undo the quoted-printable encoding the mail logger writes: soft line breaks (`=` at end of line)
 * are removed and `=XX` escapes decoded, so a signed URL split across lines becomes whole again.
 */
function decodeQuotedPrintable(body: string): string {
    return body
        .replace(/=\r?\n/g, '')
        .replace(/=([0-9A-Fa-f]{2})/g, (_, hex: string) => String.fromCharCode(parseInt(hex, 16)));
}

/**
 * The signed link out of the mail body.
 *
 * The HTML part contains the same URL with `&amp;` entities and, in the plain-text part, wrapped in
 * markdown brackets — so the match is trimmed of trailing punctuation and the entities decoded.
 */
export function extractVerificationLink(body: string): string | null {
    const match = /https?:\/\/[^\s"'<>]*verify-email[^\s"'<>)\]]*/.exec(body);
    if (match === null) return null;
    return match[0].replace(/&amp;/g, '&').replace(/[).,]+$/, '');
}

/* ── two-factor ──────────────────────────────────────────────────────────────────────────────── */

/** Base32 (RFC 4648, no padding) → bytes. Twenty lines, and it saves a dependency. */
function decodeBase32(secret: string): Buffer {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
    let bits = '';
    for (const character of secret.replace(/=+$/, '').toUpperCase()) {
        const value = alphabet.indexOf(character);
        if (value === -1) throw new Error(`"${character}" is not a base32 digit.`);
        bits += value.toString(2).padStart(5, '0');
    }

    const bytes: number[] = [];
    for (let offset = 0; offset + 8 <= bits.length; offset += 8) {
        bytes.push(Number.parseInt(bits.slice(offset, offset + 8), 2));
    }
    return Buffer.from(bytes);
}

/**
 * A TOTP code for the seeded shared secret (RFC 6238: HMAC-SHA1, 30-second step, six digits).
 *
 * Implemented here rather than taken from a package because it is fifteen lines of `node:crypto`
 * and the alternative is a runtime dependency in a repository that has none for this — and because
 * a test that generates its own code proves the server's clock and the client's agree, which a
 * stubbed code would not.
 */
export function totpCode(secret: string = TWO_FACTOR_SECRET, at: number = Date.now()): string {
    const counter = Math.floor(at / 1000 / 30);
    const message = Buffer.alloc(8);
    message.writeBigUInt64BE(BigInt(counter));

    const digest = createHmac('sha1', decodeBase32(secret)).update(message).digest();
    const offset = (digest[digest.length - 1] as number) & 0x0f;
    const binary =
        (((digest[offset] as number) & 0x7f) << 24) |
        (((digest[offset + 1] as number) & 0xff) << 16) |
        (((digest[offset + 2] as number) & 0xff) << 8) |
        ((digest[offset + 3] as number) & 0xff);

    return String(binary % 1_000_000).padStart(6, '0');
}

/* ── writing to the account ──────────────────────────────────────────────────────────────────── */

/**
 * Put one address in the signed-in account's book, through the two screens that own it.
 *
 * Checkout and the subscription record both take a delivery address by *identifier* (D-084) — the
 * zone, the window and the fee resolve from a saved entry — so neither offers a form to type into.
 * The seeded consumer starts with one saved address in Verdant's Al Quoz zone, so every journey in
 * this suite uses that one and nothing calls this helper today.
 *
 * It is kept, unused, because it is the only route to a *second* address and because deleting it
 * would hide a finding: against this stack the editor at `/customer/account/addresses/new` never
 * rendered its fields — `address-editor-label` was still absent after seven and a half minutes,
 * with the screen's chrome painted around nothing. That is worth fixing rather than forgetting, and
 * the journey that needed two addresses says so where it used to call this.
 *
 * Expects the page to already be on `/customer/account/addresses`, and leaves it there with the new
 * entry in the list. Driven entirely by test identifier, so it is direction- and locale-agnostic.
 */
export async function saveAddress(page: Page, label: string, line1: string): Promise<void> {
    await expect(page.getByTestId('addresses-screen')).toBeVisible();
    await page.getByTestId('addresses-screen-add').click();
    await expect(page.getByTestId('address-editor')).toBeVisible();

    await page.getByTestId('address-editor-label').locator('input').first().fill(label);
    // The area is a foreign key into the platform's service areas, so it is chosen, never typed.
    await page.getByTestId('address-editor-area-trigger').click();
    await page.locator('[data-testid^="address-editor-area-option-"]').first().click();
    await page.getByTestId('address-editor-line1').locator('input').first().fill(line1);
    await page.getByTestId('address-editor-save').click();

    // The save reached the server rather than merely the form: the list is showing again.
    await expect(page.getByTestId('addresses-screen-list')).toBeVisible();
}

/**
 * Empty the signed-in account's basket, so a journey starts from a state it can reason about.
 *
 * The basket is a real, persisted record now: a run that placed no order leaves its lines behind and
 * the next run would price a basket it did not fill. Expects to be on `/customer/cart`.
 */
export async function emptyBasket(page: Page): Promise<void> {
    await expect(page.getByTestId('cart-screen')).toBeVisible();

    const removes = page.locator('[data-testid$="-remove"]');

    for (let attempt = 0; attempt < 12; attempt += 1) {
        if ((await page.getByTestId('cart-empty').count()) > 0) return;

        const before = await removes.count();
        if (before === 0) return;

        /*
         * Enabled *then* clicked, and then waited on by count.
         *
         * Every control on a basket line is disabled while a mutation is in flight
         * (`busy={setQuantity.isPending || removeItem.isPending}` in `cart-screen.tsx`), which on
         * this stack is several seconds. A loop that pressed "remove" again immediately met a
         * disabled button, and Playwright's click retries it until the element is *enabled* — but
         * the re-render replaces the node, so the retry restarts on a detached element and the
         * whole thing spins until the test times out. That is what wedged the first run of
         * `web-write` for seven and a half minutes on one basket.
         *
         * Waiting for the row *count* to drop is the honest completion signal: it is the thing the
         * removal is for, and it cannot be satisfied by a button that merely became clickable again.
         */
        const first = removes.first();
        await expect(first).toBeEnabled();
        await first.click();
        await expect.poll(async () => removes.count()).toBeLessThan(before);
    }
}
