/*
 * AUTOGENERATED by @healthy360/i18n — do not edit by hand.
 * Source: packages/i18n/catalogues/en/*.json
 * Regenerate: pnpm --filter @healthy360/i18n gen:keys
 *
 * 394 keys across 14 namespaces. Plural variants (zero, one, two, few, many, other)
 * are collapsed to their base key, because that is the key t() is called with.
 */

/** Keys available in each namespace, unqualified. */
export interface NamespaceKeys {
  readonly "access":
    | 'area.auth'
    | 'area.clinic'
    | 'area.corporate'
    | 'area.customer'
    | 'area.dietitian'
    | 'area.driver'
    | 'area.insurance'
    | 'area.kds'
    | 'area.kitchen'
    | 'area.partner'
    | 'area.patient'
    | 'area.platform-admin'
    | 'area.pos'
    | 'area.public'
    | 'denial.email_unverified.body'
    | 'denial.email_unverified.title'
    | 'denial.entitlement_missing.body'
    | 'denial.entitlement_missing.title'
    | 'denial.mode_excluded.body'
    | 'denial.mode_excluded.title'
    | 'denial.no_branch_context.body'
    | 'denial.no_branch_context.title'
    | 'denial.no_organisation_context.body'
    | 'denial.no_organisation_context.title'
    | 'denial.permission_missing.body'
    | 'denial.permission_missing.title'
    | 'denial.unauthenticated.body'
    | 'denial.unauthenticated.title'
    | 'forbidden.backToWorkspace'
    | 'forbidden.missingLabel'
    | 'forbidden.reasonLabel'
    | 'forbidden.signInAgain'
    | 'forbidden.switchOrganisation'
    | 'forbidden.title'
    | 'mockMode.badge'
    | 'mockMode.description'
    | 'notFound.body'
    | 'notFound.home'
    | 'notFound.title'
    | 'pending.body'
    | 'pending.title'
    | 'workspaceSelector.current'
    | 'workspaceSelector.empty'
    | 'workspaceSelector.emptyBody'
    | 'workspaceSelector.open'
    | 'workspaceSelector.subtitle'
    | 'workspaceSelector.title';
  readonly "auth":
    | 'branchPicker.empty'
    | 'branchPicker.groupLabel'
    | 'branchPicker.onlyOne'
    | 'branchPicker.openLabel'
    | 'branchPicker.subtitle'
    | 'branchPicker.title'
    | 'devices.current'
    | 'devices.empty'
    | 'devices.emptyBody'
    | 'devices.lastUsed'
    | 'devices.neverUsed'
    | 'devices.platform.android'
    | 'devices.platform.ios'
    | 'devices.platform.web'
    | 'devices.revoke'
    | 'devices.revokeBody'
    | 'devices.revokeConfirm'
    | 'devices.revokeLabel'
    | 'devices.revokeTitle'
    | 'devices.revoked'
    | 'devices.subtitle'
    | 'devices.title'
    | 'forgotPassword.backToSignIn'
    | 'forgotPassword.emailLabel'
    | 'forgotPassword.sentBody'
    | 'forgotPassword.sentTitle'
    | 'forgotPassword.submit'
    | 'forgotPassword.subtitle'
    | 'forgotPassword.title'
    | 'login.emailLabel'
    | 'login.emailPlaceholder'
    | 'login.failed'
    | 'login.forgotLink'
    | 'login.passwordLabel'
    | 'login.rateLimited'
    | 'login.registerLink'
    | 'login.registerPrompt'
    | 'login.rememberLabel'
    | 'login.submit'
    | 'login.subtitle'
    | 'login.title'
    | 'login.twoFactor.back'
    | 'login.twoFactor.codeHint'
    | 'login.twoFactor.codeLabel'
    | 'login.twoFactor.recoveryHint'
    | 'login.twoFactor.recoveryLabel'
    | 'login.twoFactor.submit'
    | 'login.twoFactor.subtitle'
    | 'login.twoFactor.title'
    | 'login.twoFactor.useCode'
    | 'login.twoFactor.useRecovery'
    | 'organisationPicker.branchCount'
    | 'organisationPicker.empty'
    | 'organisationPicker.emptyBody'
    | 'organisationPicker.noBranches'
    | 'organisationPicker.onlyOne'
    | 'organisationPicker.openLabel'
    | 'organisationPicker.pending'
    | 'organisationPicker.roleLabel'
    | 'organisationPicker.subtitle'
    | 'organisationPicker.suspended'
    | 'organisationPicker.title'
    | 'profile.account'
    | 'profile.branch'
    | 'profile.consents'
    | 'profile.consentsNone'
    | 'profile.context'
    | 'profile.displayName'
    | 'profile.email'
    | 'profile.entitlements'
    | 'profile.locale'
    | 'profile.memberSince'
    | 'profile.memberships'
    | 'profile.noBranch'
    | 'profile.noContext'
    | 'profile.none'
    | 'profile.organisation'
    | 'profile.permissions'
    | 'profile.roles'
    | 'profile.subtitle'
    | 'profile.timeZone'
    | 'profile.title'
    | 'profile.twoFactor'
    | 'profile.twoFactorDisabled'
    | 'profile.twoFactorEnabled'
    | 'register.acceptPrivacy'
    | 'register.acceptTerms'
    | 'register.emailLabel'
    | 'register.loginLink'
    | 'register.loginPrompt'
    | 'register.nameLabel'
    | 'register.passwordConfirmationLabel'
    | 'register.passwordHint'
    | 'register.passwordLabel'
    | 'register.privacyLink'
    | 'register.submit'
    | 'register.subtitle'
    | 'register.termsLink'
    | 'register.title'
    | 'resetPassword.invalidToken'
    | 'resetPassword.missingLink'
    | 'resetPassword.missingLinkBody'
    | 'resetPassword.passwordConfirmationLabel'
    | 'resetPassword.passwordLabel'
    | 'resetPassword.requestNew'
    | 'resetPassword.submit'
    | 'resetPassword.subtitle'
    | 'resetPassword.successBody'
    | 'resetPassword.successTitle'
    | 'resetPassword.title'
    | 'stepUp.body'
    | 'stepUp.confirmed'
    | 'stepUp.passwordLabel'
    | 'stepUp.submit'
    | 'stepUp.title'
    | 'verifyEmail.body'
    | 'verifyEmail.checkAgain'
    | 'verifyEmail.continue'
    | 'verifyEmail.cooldown'
    | 'verifyEmail.pendingBody'
    | 'verifyEmail.pendingTitle'
    | 'verifyEmail.resend'
    | 'verifyEmail.resent'
    | 'verifyEmail.title'
    | 'verifyEmail.verifiedBody'
    | 'verifyEmail.verifiedTitle'
    | 'verifyEmail.wrongAddress'
    | 'workspace.devices'
    | 'workspace.profile'
    | 'workspace.subtitle'
    | 'workspace.switchBranch'
    | 'workspace.switchOrganisation'
    | 'workspace.title';
  readonly "business":
    | 'title';
  readonly "catalogue":
    | 'title';
  readonly "commerce":
    | 'title';
  readonly "common":
    | 'action.back'
    | 'action.cancel'
    | 'action.change'
    | 'action.close'
    | 'action.confirm'
    | 'action.continue'
    | 'action.dismiss'
    | 'action.done'
    | 'action.goBack'
    | 'action.refresh'
    | 'action.resend'
    | 'action.retry'
    | 'action.save'
    | 'action.select'
    | 'action.signIn'
    | 'action.signOut'
    | 'action.signUp'
    | 'app.name'
    | 'app.tagline'
    | 'dev.mockBadge'
    | 'dev.mockDescription'
    | 'dev.mockScenario'
    | 'dev.switchScenario'
    | 'dev.switchScenarioHint'
    | 'direction.ltr'
    | 'direction.rtl'
    | 'locale.arabic'
    | 'locale.changed'
    | 'locale.english'
    | 'locale.label'
    | 'locale.reloadLater'
    | 'locale.reloadNow'
    | 'locale.reloadRequiredBody'
    | 'locale.reloadRequiredTitle'
    | 'nav.devices'
    | 'nav.overview'
    | 'nav.profile'
    | 'nav.showcase'
    | 'nav.workspace'
    | 'network.backOnline'
    | 'network.offlineBody'
    | 'network.offlineTitle'
    | 'network.reconnectingBody'
    | 'network.reconnectingTitle'
    | 'notifications.count'
    | 'state.empty'
    | 'state.loading'
    | 'state.restoringSession'
    | 'state.saving'
    | 'theme.dark'
    | 'theme.label'
    | 'theme.light'
    | 'theme.system';
  readonly "designSystem":
    | 'breadcrumbs.label'
    | 'chip.remove'
    | 'controls.currentDirection'
    | 'controls.currentLocale'
    | 'controls.currentTheme'
    | 'controls.toggleLocale'
    | 'controls.toggleTheme'
    | 'dateField.day'
    | 'dateField.month'
    | 'dateField.year'
    | 'emptyState.prototypeBadge'
    | 'emptyState.prototypeBody'
    | 'numberStepper.decrease'
    | 'numberStepper.increase'
    | 'passwordInput.hide'
    | 'passwordInput.show'
    | 'rangeFilter.inverted'
    | 'rangeFilter.max'
    | 'rangeFilter.min'
    | 'rating.count'
    | 'rating.summary'
    | 'select.placeholder'
    | 'shell.openNavigation'
    | 'shell.primaryNavigation'
    | 'shell.skipToContent'
    | 'showcase.accordionBody'
    | 'showcase.accordionOne'
    | 'showcase.accordionTwo'
    | 'showcase.actionSheetDestructive'
    | 'showcase.actionSheetPrimary'
    | 'showcase.actionSheetSecondary'
    | 'showcase.actionSheetTitle'
    | 'showcase.amountLabel'
    | 'showcase.avatarName'
    | 'showcase.breadcrumbCurrent'
    | 'showcase.breadcrumbHome'
    | 'showcase.breadcrumbSection'
    | 'showcase.calendarLabel'
    | 'showcase.calloutBody'
    | 'showcase.calloutTitle'
    | 'showcase.chipFilter'
    | 'showcase.chipRemovable'
    | 'showcase.dateLabel'
    | 'showcase.dialogBody'
    | 'showcase.dialogTitle'
    | 'showcase.drawerTitle'
    | 'showcase.meterLabel'
    | 'showcase.motionFade'
    | 'showcase.motionNumber'
    | 'showcase.motionSlideBottom'
    | 'showcase.motionSlideStart'
    | 'showcase.openActionSheet'
    | 'showcase.openDialog'
    | 'showcase.openDrawer'
    | 'showcase.openDrawerEnd'
    | 'showcase.placeholderLabel'
    | 'showcase.popoverBody'
    | 'showcase.popoverTitle'
    | 'showcase.popoverTrigger'
    | 'showcase.rangeLabel'
    | 'showcase.ratingLabel'
    | 'showcase.replay'
    | 'showcase.ringCaption'
    | 'showcase.ringLabel'
    | 'showcase.sampleError'
    | 'showcase.sampleHint'
    | 'showcase.sampleLabel'
    | 'showcase.sampleOption'
    | 'showcase.sections.actions'
    | 'showcase.sections.content'
    | 'showcase.sections.data'
    | 'showcase.sections.dates'
    | 'showcase.sections.filters'
    | 'showcase.sections.forms'
    | 'showcase.sections.motion'
    | 'showcase.sections.navigation'
    | 'showcase.sections.overlays'
    | 'showcase.sections.shell'
    | 'showcase.sections.status'
    | 'showcase.sections.typography'
    | 'showcase.showToast'
    | 'showcase.stepperLabel'
    | 'showcase.stepperStep'
    | 'showcase.subtitle'
    | 'showcase.tabDelivery'
    | 'showcase.tabNutrition'
    | 'showcase.tabOverview'
    | 'showcase.tableCaption'
    | 'showcase.tableColumnAmount'
    | 'showcase.tableColumnName'
    | 'showcase.tableColumnTarget'
    | 'showcase.tabsLabel'
    | 'showcase.title'
    | 'showcase.toastMessage'
    | 'spike.colour.description'
    | 'spike.elevation.description'
    | 'spike.logical.description'
    | 'spike.logical.leading'
    | 'spike.logical.marker'
    | 'spike.logical.trailing'
    | 'spike.nutrition.description'
    | 'spike.sample.arabic'
    | 'spike.sample.digits'
    | 'spike.sample.latin'
    | 'spike.sections.colour'
    | 'spike.sections.elevation'
    | 'spike.sections.logical'
    | 'spike.sections.nutrition'
    | 'spike.sections.spacing'
    | 'spike.sections.typography'
    | 'spike.spacing.description'
    | 'spike.subtitle'
    | 'spike.title'
    | 'spike.typography.description'
    | 'stepper.progress'
    | 'swatch.contrast'
    | 'table.empty';
  readonly "errors":
    | 'failure.auth_email_unverified'
    | 'failure.auth_invalid_credentials'
    | 'failure.auth_step_up_required'
    | 'failure.auth_two_factor_required'
    | 'failure.auth_unauthenticated'
    | 'failure.context_branch_out_of_scope'
    | 'failure.context_organisation_forbidden'
    | 'failure.context_organisation_required'
    | 'failure.network'
    | 'failure.prototype_not_implemented'
    | 'failure.rate_limit_exceeded'
    | 'failure.server'
    | 'failure.validation_failed'
    | 'generic.body'
    | 'generic.reference'
    | 'generic.retry'
    | 'generic.title'
    | 'http.forbidden'
    | 'http.notFound'
    | 'http.rateLimited'
    | 'http.serverError'
    | 'http.unauthorised'
    | 'http.unprocessable'
    | 'network.offline'
    | 'network.timeout'
    | 'network.unreachable'
    | 'validation.accept_privacy'
    | 'validation.accept_terms'
    | 'validation.email'
    | 'validation.identifier'
    | 'validation.max_length'
    | 'validation.min_length'
    | 'validation.password_min_length'
    | 'validation.password_mismatch'
    | 'validation.required';
  readonly "marketplace":
    | 'title';
  readonly "nutrition":
    | 'title';
  readonly "onboarding":
    | 'title';
  readonly "planner":
    | 'title';
  readonly "professional":
    | 'title';
  readonly "virtualDietitian":
    | 'title';
}

/** Every key in `namespace:key` form — the shape an unscoped `t()` accepts. */
export type TranslationKey = {
  [N in keyof NamespaceKeys]: `${N & string}:${NamespaceKeys[N]}`;
}[keyof NamespaceKeys];

export const PLURAL_SUFFIXES = ["zero","one","two","few","many","other"] as const;

/** Runtime list, for parity assertions and development tooling. */
export const TRANSLATION_KEYS: readonly TranslationKey[] = [
  'access:area.auth',
  'access:area.clinic',
  'access:area.corporate',
  'access:area.customer',
  'access:area.dietitian',
  'access:area.driver',
  'access:area.insurance',
  'access:area.kds',
  'access:area.kitchen',
  'access:area.partner',
  'access:area.patient',
  'access:area.platform-admin',
  'access:area.pos',
  'access:area.public',
  'access:denial.email_unverified.body',
  'access:denial.email_unverified.title',
  'access:denial.entitlement_missing.body',
  'access:denial.entitlement_missing.title',
  'access:denial.mode_excluded.body',
  'access:denial.mode_excluded.title',
  'access:denial.no_branch_context.body',
  'access:denial.no_branch_context.title',
  'access:denial.no_organisation_context.body',
  'access:denial.no_organisation_context.title',
  'access:denial.permission_missing.body',
  'access:denial.permission_missing.title',
  'access:denial.unauthenticated.body',
  'access:denial.unauthenticated.title',
  'access:forbidden.backToWorkspace',
  'access:forbidden.missingLabel',
  'access:forbidden.reasonLabel',
  'access:forbidden.signInAgain',
  'access:forbidden.switchOrganisation',
  'access:forbidden.title',
  'access:mockMode.badge',
  'access:mockMode.description',
  'access:notFound.body',
  'access:notFound.home',
  'access:notFound.title',
  'access:pending.body',
  'access:pending.title',
  'access:workspaceSelector.current',
  'access:workspaceSelector.empty',
  'access:workspaceSelector.emptyBody',
  'access:workspaceSelector.open',
  'access:workspaceSelector.subtitle',
  'access:workspaceSelector.title',
  'auth:branchPicker.empty',
  'auth:branchPicker.groupLabel',
  'auth:branchPicker.onlyOne',
  'auth:branchPicker.openLabel',
  'auth:branchPicker.subtitle',
  'auth:branchPicker.title',
  'auth:devices.current',
  'auth:devices.empty',
  'auth:devices.emptyBody',
  'auth:devices.lastUsed',
  'auth:devices.neverUsed',
  'auth:devices.platform.android',
  'auth:devices.platform.ios',
  'auth:devices.platform.web',
  'auth:devices.revoke',
  'auth:devices.revokeBody',
  'auth:devices.revokeConfirm',
  'auth:devices.revokeLabel',
  'auth:devices.revokeTitle',
  'auth:devices.revoked',
  'auth:devices.subtitle',
  'auth:devices.title',
  'auth:forgotPassword.backToSignIn',
  'auth:forgotPassword.emailLabel',
  'auth:forgotPassword.sentBody',
  'auth:forgotPassword.sentTitle',
  'auth:forgotPassword.submit',
  'auth:forgotPassword.subtitle',
  'auth:forgotPassword.title',
  'auth:login.emailLabel',
  'auth:login.emailPlaceholder',
  'auth:login.failed',
  'auth:login.forgotLink',
  'auth:login.passwordLabel',
  'auth:login.rateLimited',
  'auth:login.registerLink',
  'auth:login.registerPrompt',
  'auth:login.rememberLabel',
  'auth:login.submit',
  'auth:login.subtitle',
  'auth:login.title',
  'auth:login.twoFactor.back',
  'auth:login.twoFactor.codeHint',
  'auth:login.twoFactor.codeLabel',
  'auth:login.twoFactor.recoveryHint',
  'auth:login.twoFactor.recoveryLabel',
  'auth:login.twoFactor.submit',
  'auth:login.twoFactor.subtitle',
  'auth:login.twoFactor.title',
  'auth:login.twoFactor.useCode',
  'auth:login.twoFactor.useRecovery',
  'auth:organisationPicker.branchCount',
  'auth:organisationPicker.empty',
  'auth:organisationPicker.emptyBody',
  'auth:organisationPicker.noBranches',
  'auth:organisationPicker.onlyOne',
  'auth:organisationPicker.openLabel',
  'auth:organisationPicker.pending',
  'auth:organisationPicker.roleLabel',
  'auth:organisationPicker.subtitle',
  'auth:organisationPicker.suspended',
  'auth:organisationPicker.title',
  'auth:profile.account',
  'auth:profile.branch',
  'auth:profile.consents',
  'auth:profile.consentsNone',
  'auth:profile.context',
  'auth:profile.displayName',
  'auth:profile.email',
  'auth:profile.entitlements',
  'auth:profile.locale',
  'auth:profile.memberSince',
  'auth:profile.memberships',
  'auth:profile.noBranch',
  'auth:profile.noContext',
  'auth:profile.none',
  'auth:profile.organisation',
  'auth:profile.permissions',
  'auth:profile.roles',
  'auth:profile.subtitle',
  'auth:profile.timeZone',
  'auth:profile.title',
  'auth:profile.twoFactor',
  'auth:profile.twoFactorDisabled',
  'auth:profile.twoFactorEnabled',
  'auth:register.acceptPrivacy',
  'auth:register.acceptTerms',
  'auth:register.emailLabel',
  'auth:register.loginLink',
  'auth:register.loginPrompt',
  'auth:register.nameLabel',
  'auth:register.passwordConfirmationLabel',
  'auth:register.passwordHint',
  'auth:register.passwordLabel',
  'auth:register.privacyLink',
  'auth:register.submit',
  'auth:register.subtitle',
  'auth:register.termsLink',
  'auth:register.title',
  'auth:resetPassword.invalidToken',
  'auth:resetPassword.missingLink',
  'auth:resetPassword.missingLinkBody',
  'auth:resetPassword.passwordConfirmationLabel',
  'auth:resetPassword.passwordLabel',
  'auth:resetPassword.requestNew',
  'auth:resetPassword.submit',
  'auth:resetPassword.subtitle',
  'auth:resetPassword.successBody',
  'auth:resetPassword.successTitle',
  'auth:resetPassword.title',
  'auth:stepUp.body',
  'auth:stepUp.confirmed',
  'auth:stepUp.passwordLabel',
  'auth:stepUp.submit',
  'auth:stepUp.title',
  'auth:verifyEmail.body',
  'auth:verifyEmail.checkAgain',
  'auth:verifyEmail.continue',
  'auth:verifyEmail.cooldown',
  'auth:verifyEmail.pendingBody',
  'auth:verifyEmail.pendingTitle',
  'auth:verifyEmail.resend',
  'auth:verifyEmail.resent',
  'auth:verifyEmail.title',
  'auth:verifyEmail.verifiedBody',
  'auth:verifyEmail.verifiedTitle',
  'auth:verifyEmail.wrongAddress',
  'auth:workspace.devices',
  'auth:workspace.profile',
  'auth:workspace.subtitle',
  'auth:workspace.switchBranch',
  'auth:workspace.switchOrganisation',
  'auth:workspace.title',
  'business:title',
  'catalogue:title',
  'commerce:title',
  'common:action.back',
  'common:action.cancel',
  'common:action.change',
  'common:action.close',
  'common:action.confirm',
  'common:action.continue',
  'common:action.dismiss',
  'common:action.done',
  'common:action.goBack',
  'common:action.refresh',
  'common:action.resend',
  'common:action.retry',
  'common:action.save',
  'common:action.select',
  'common:action.signIn',
  'common:action.signOut',
  'common:action.signUp',
  'common:app.name',
  'common:app.tagline',
  'common:dev.mockBadge',
  'common:dev.mockDescription',
  'common:dev.mockScenario',
  'common:dev.switchScenario',
  'common:dev.switchScenarioHint',
  'common:direction.ltr',
  'common:direction.rtl',
  'common:locale.arabic',
  'common:locale.changed',
  'common:locale.english',
  'common:locale.label',
  'common:locale.reloadLater',
  'common:locale.reloadNow',
  'common:locale.reloadRequiredBody',
  'common:locale.reloadRequiredTitle',
  'common:nav.devices',
  'common:nav.overview',
  'common:nav.profile',
  'common:nav.showcase',
  'common:nav.workspace',
  'common:network.backOnline',
  'common:network.offlineBody',
  'common:network.offlineTitle',
  'common:network.reconnectingBody',
  'common:network.reconnectingTitle',
  'common:notifications.count',
  'common:state.empty',
  'common:state.loading',
  'common:state.restoringSession',
  'common:state.saving',
  'common:theme.dark',
  'common:theme.label',
  'common:theme.light',
  'common:theme.system',
  'designSystem:breadcrumbs.label',
  'designSystem:chip.remove',
  'designSystem:controls.currentDirection',
  'designSystem:controls.currentLocale',
  'designSystem:controls.currentTheme',
  'designSystem:controls.toggleLocale',
  'designSystem:controls.toggleTheme',
  'designSystem:dateField.day',
  'designSystem:dateField.month',
  'designSystem:dateField.year',
  'designSystem:emptyState.prototypeBadge',
  'designSystem:emptyState.prototypeBody',
  'designSystem:numberStepper.decrease',
  'designSystem:numberStepper.increase',
  'designSystem:passwordInput.hide',
  'designSystem:passwordInput.show',
  'designSystem:rangeFilter.inverted',
  'designSystem:rangeFilter.max',
  'designSystem:rangeFilter.min',
  'designSystem:rating.count',
  'designSystem:rating.summary',
  'designSystem:select.placeholder',
  'designSystem:shell.openNavigation',
  'designSystem:shell.primaryNavigation',
  'designSystem:shell.skipToContent',
  'designSystem:showcase.accordionBody',
  'designSystem:showcase.accordionOne',
  'designSystem:showcase.accordionTwo',
  'designSystem:showcase.actionSheetDestructive',
  'designSystem:showcase.actionSheetPrimary',
  'designSystem:showcase.actionSheetSecondary',
  'designSystem:showcase.actionSheetTitle',
  'designSystem:showcase.amountLabel',
  'designSystem:showcase.avatarName',
  'designSystem:showcase.breadcrumbCurrent',
  'designSystem:showcase.breadcrumbHome',
  'designSystem:showcase.breadcrumbSection',
  'designSystem:showcase.calendarLabel',
  'designSystem:showcase.calloutBody',
  'designSystem:showcase.calloutTitle',
  'designSystem:showcase.chipFilter',
  'designSystem:showcase.chipRemovable',
  'designSystem:showcase.dateLabel',
  'designSystem:showcase.dialogBody',
  'designSystem:showcase.dialogTitle',
  'designSystem:showcase.drawerTitle',
  'designSystem:showcase.meterLabel',
  'designSystem:showcase.motionFade',
  'designSystem:showcase.motionNumber',
  'designSystem:showcase.motionSlideBottom',
  'designSystem:showcase.motionSlideStart',
  'designSystem:showcase.openActionSheet',
  'designSystem:showcase.openDialog',
  'designSystem:showcase.openDrawer',
  'designSystem:showcase.openDrawerEnd',
  'designSystem:showcase.placeholderLabel',
  'designSystem:showcase.popoverBody',
  'designSystem:showcase.popoverTitle',
  'designSystem:showcase.popoverTrigger',
  'designSystem:showcase.rangeLabel',
  'designSystem:showcase.ratingLabel',
  'designSystem:showcase.replay',
  'designSystem:showcase.ringCaption',
  'designSystem:showcase.ringLabel',
  'designSystem:showcase.sampleError',
  'designSystem:showcase.sampleHint',
  'designSystem:showcase.sampleLabel',
  'designSystem:showcase.sampleOption',
  'designSystem:showcase.sections.actions',
  'designSystem:showcase.sections.content',
  'designSystem:showcase.sections.data',
  'designSystem:showcase.sections.dates',
  'designSystem:showcase.sections.filters',
  'designSystem:showcase.sections.forms',
  'designSystem:showcase.sections.motion',
  'designSystem:showcase.sections.navigation',
  'designSystem:showcase.sections.overlays',
  'designSystem:showcase.sections.shell',
  'designSystem:showcase.sections.status',
  'designSystem:showcase.sections.typography',
  'designSystem:showcase.showToast',
  'designSystem:showcase.stepperLabel',
  'designSystem:showcase.stepperStep',
  'designSystem:showcase.subtitle',
  'designSystem:showcase.tabDelivery',
  'designSystem:showcase.tabNutrition',
  'designSystem:showcase.tabOverview',
  'designSystem:showcase.tableCaption',
  'designSystem:showcase.tableColumnAmount',
  'designSystem:showcase.tableColumnName',
  'designSystem:showcase.tableColumnTarget',
  'designSystem:showcase.tabsLabel',
  'designSystem:showcase.title',
  'designSystem:showcase.toastMessage',
  'designSystem:spike.colour.description',
  'designSystem:spike.elevation.description',
  'designSystem:spike.logical.description',
  'designSystem:spike.logical.leading',
  'designSystem:spike.logical.marker',
  'designSystem:spike.logical.trailing',
  'designSystem:spike.nutrition.description',
  'designSystem:spike.sample.arabic',
  'designSystem:spike.sample.digits',
  'designSystem:spike.sample.latin',
  'designSystem:spike.sections.colour',
  'designSystem:spike.sections.elevation',
  'designSystem:spike.sections.logical',
  'designSystem:spike.sections.nutrition',
  'designSystem:spike.sections.spacing',
  'designSystem:spike.sections.typography',
  'designSystem:spike.spacing.description',
  'designSystem:spike.subtitle',
  'designSystem:spike.title',
  'designSystem:spike.typography.description',
  'designSystem:stepper.progress',
  'designSystem:swatch.contrast',
  'designSystem:table.empty',
  'errors:failure.auth_email_unverified',
  'errors:failure.auth_invalid_credentials',
  'errors:failure.auth_step_up_required',
  'errors:failure.auth_two_factor_required',
  'errors:failure.auth_unauthenticated',
  'errors:failure.context_branch_out_of_scope',
  'errors:failure.context_organisation_forbidden',
  'errors:failure.context_organisation_required',
  'errors:failure.network',
  'errors:failure.prototype_not_implemented',
  'errors:failure.rate_limit_exceeded',
  'errors:failure.server',
  'errors:failure.validation_failed',
  'errors:generic.body',
  'errors:generic.reference',
  'errors:generic.retry',
  'errors:generic.title',
  'errors:http.forbidden',
  'errors:http.notFound',
  'errors:http.rateLimited',
  'errors:http.serverError',
  'errors:http.unauthorised',
  'errors:http.unprocessable',
  'errors:network.offline',
  'errors:network.timeout',
  'errors:network.unreachable',
  'errors:validation.accept_privacy',
  'errors:validation.accept_terms',
  'errors:validation.email',
  'errors:validation.identifier',
  'errors:validation.max_length',
  'errors:validation.min_length',
  'errors:validation.password_min_length',
  'errors:validation.password_mismatch',
  'errors:validation.required',
  'marketplace:title',
  'nutrition:title',
  'onboarding:title',
  'planner:title',
  'professional:title',
  'virtualDietitian:title',
];

const TRANSLATION_KEY_SET: ReadonlySet<string> = new Set(TRANSLATION_KEYS);

export function isTranslationKey(value: unknown): value is TranslationKey {
  return typeof value === 'string' && TRANSLATION_KEY_SET.has(value);
}
