/*
 * AUTOGENERATED by @healthy360/i18n — do not edit by hand.
 * Source: packages/i18n/catalogues/en/*.json
 * Regenerate: pnpm --filter @healthy360/i18n gen:keys
 *
 * 688 keys across 14 namespaces. Plural variants (zero, one, two, few, many, other)
 * are collapsed to their base key, because that is the key t() is called with.
 */

/** Keys available in each namespace, unqualified. */
export interface NamespaceKeys {
  readonly "access":
    | 'area.auth'
    | 'area.clinic'
    | 'area.corporate'
    | 'area.customer'
    | 'area.dietitian'
    | 'area.driver'
    | 'area.insurance'
    | 'area.kds'
    | 'area.kitchen'
    | 'area.partner'
    | 'area.patient'
    | 'area.platform-admin'
    | 'area.pos'
    | 'area.public'
    | 'denial.email_unverified.body'
    | 'denial.email_unverified.title'
    | 'denial.entitlement_missing.body'
    | 'denial.entitlement_missing.title'
    | 'denial.mode_excluded.body'
    | 'denial.mode_excluded.title'
    | 'denial.no_branch_context.body'
    | 'denial.no_branch_context.title'
    | 'denial.no_organisation_context.body'
    | 'denial.no_organisation_context.title'
    | 'denial.permission_missing.body'
    | 'denial.permission_missing.title'
    | 'denial.unauthenticated.body'
    | 'denial.unauthenticated.title'
    | 'forbidden.backToWorkspace'
    | 'forbidden.missingLabel'
    | 'forbidden.reasonLabel'
    | 'forbidden.signInAgain'
    | 'forbidden.switchOrganisation'
    | 'forbidden.title'
    | 'mockMode.badge'
    | 'mockMode.description'
    | 'notFound.body'
    | 'notFound.home'
    | 'notFound.title'
    | 'pending.body'
    | 'pending.title'
    | 'workspaceSelector.current'
    | 'workspaceSelector.empty'
    | 'workspaceSelector.emptyBody'
    | 'workspaceSelector.open'
    | 'workspaceSelector.subtitle'
    | 'workspaceSelector.title';
  readonly "auth":
    | 'branchPicker.empty'
    | 'branchPicker.groupLabel'
    | 'branchPicker.onlyOne'
    | 'branchPicker.openLabel'
    | 'branchPicker.subtitle'
    | 'branchPicker.title'
    | 'devices.current'
    | 'devices.empty'
    | 'devices.emptyBody'
    | 'devices.lastUsed'
    | 'devices.neverUsed'
    | 'devices.platform.android'
    | 'devices.platform.ios'
    | 'devices.platform.web'
    | 'devices.revoke'
    | 'devices.revokeBody'
    | 'devices.revokeConfirm'
    | 'devices.revokeLabel'
    | 'devices.revokeTitle'
    | 'devices.revoked'
    | 'devices.subtitle'
    | 'devices.title'
    | 'forgotPassword.backToSignIn'
    | 'forgotPassword.emailLabel'
    | 'forgotPassword.sentBody'
    | 'forgotPassword.sentTitle'
    | 'forgotPassword.submit'
    | 'forgotPassword.subtitle'
    | 'forgotPassword.title'
    | 'login.emailLabel'
    | 'login.emailPlaceholder'
    | 'login.failed'
    | 'login.forgotLink'
    | 'login.passwordLabel'
    | 'login.rateLimited'
    | 'login.registerLink'
    | 'login.registerPrompt'
    | 'login.rememberLabel'
    | 'login.submit'
    | 'login.subtitle'
    | 'login.title'
    | 'login.twoFactor.back'
    | 'login.twoFactor.codeHint'
    | 'login.twoFactor.codeLabel'
    | 'login.twoFactor.recoveryHint'
    | 'login.twoFactor.recoveryLabel'
    | 'login.twoFactor.submit'
    | 'login.twoFactor.subtitle'
    | 'login.twoFactor.title'
    | 'login.twoFactor.useCode'
    | 'login.twoFactor.useRecovery'
    | 'organisationPicker.branchCount'
    | 'organisationPicker.empty'
    | 'organisationPicker.emptyBody'
    | 'organisationPicker.noBranches'
    | 'organisationPicker.onlyOne'
    | 'organisationPicker.openLabel'
    | 'organisationPicker.pending'
    | 'organisationPicker.roleLabel'
    | 'organisationPicker.subtitle'
    | 'organisationPicker.suspended'
    | 'organisationPicker.title'
    | 'profile.account'
    | 'profile.branch'
    | 'profile.consents'
    | 'profile.consentsNone'
    | 'profile.context'
    | 'profile.displayName'
    | 'profile.email'
    | 'profile.entitlements'
    | 'profile.locale'
    | 'profile.memberSince'
    | 'profile.memberships'
    | 'profile.noBranch'
    | 'profile.noContext'
    | 'profile.none'
    | 'profile.organisation'
    | 'profile.permissions'
    | 'profile.roles'
    | 'profile.subtitle'
    | 'profile.timeZone'
    | 'profile.title'
    | 'profile.twoFactor'
    | 'profile.twoFactorDisabled'
    | 'profile.twoFactorEnabled'
    | 'register.acceptPrivacy'
    | 'register.acceptTerms'
    | 'register.emailLabel'
    | 'register.loginLink'
    | 'register.loginPrompt'
    | 'register.nameLabel'
    | 'register.passwordConfirmationLabel'
    | 'register.passwordHint'
    | 'register.passwordLabel'
    | 'register.privacyLink'
    | 'register.submit'
    | 'register.subtitle'
    | 'register.termsLink'
    | 'register.title'
    | 'resetPassword.invalidToken'
    | 'resetPassword.missingLink'
    | 'resetPassword.missingLinkBody'
    | 'resetPassword.passwordConfirmationLabel'
    | 'resetPassword.passwordLabel'
    | 'resetPassword.requestNew'
    | 'resetPassword.submit'
    | 'resetPassword.subtitle'
    | 'resetPassword.successBody'
    | 'resetPassword.successTitle'
    | 'resetPassword.title'
    | 'stepUp.body'
    | 'stepUp.confirmed'
    | 'stepUp.passwordLabel'
    | 'stepUp.submit'
    | 'stepUp.title'
    | 'verifyEmail.body'
    | 'verifyEmail.checkAgain'
    | 'verifyEmail.continue'
    | 'verifyEmail.cooldown'
    | 'verifyEmail.pendingBody'
    | 'verifyEmail.pendingTitle'
    | 'verifyEmail.resend'
    | 'verifyEmail.resent'
    | 'verifyEmail.title'
    | 'verifyEmail.verifiedBody'
    | 'verifyEmail.verifiedTitle'
    | 'verifyEmail.wrongAddress'
    | 'workspace.devices'
    | 'workspace.profile'
    | 'workspace.subtitle'
    | 'workspace.switchBranch'
    | 'workspace.switchOrganisation'
    | 'workspace.title';
  readonly "business":
    | 'title';
  readonly "catalogue":
    | 'title';
  readonly "commerce":
    | 'title';
  readonly "common":
    | 'action.back'
    | 'action.cancel'
    | 'action.change'
    | 'action.close'
    | 'action.confirm'
    | 'action.continue'
    | 'action.dismiss'
    | 'action.done'
    | 'action.goBack'
    | 'action.refresh'
    | 'action.resend'
    | 'action.retry'
    | 'action.save'
    | 'action.select'
    | 'action.signIn'
    | 'action.signOut'
    | 'action.signUp'
    | 'app.name'
    | 'app.tagline'
    | 'dev.mockBadge'
    | 'dev.mockDescription'
    | 'dev.mockScenario'
    | 'dev.switchScenario'
    | 'dev.switchScenarioHint'
    | 'direction.ltr'
    | 'direction.rtl'
    | 'locale.arabic'
    | 'locale.changed'
    | 'locale.english'
    | 'locale.label'
    | 'locale.reloadLater'
    | 'locale.reloadNow'
    | 'locale.reloadRequiredBody'
    | 'locale.reloadRequiredTitle'
    | 'nav.devices'
    | 'nav.overview'
    | 'nav.profile'
    | 'nav.showcase'
    | 'nav.workspace'
    | 'network.backOnline'
    | 'network.offlineBody'
    | 'network.offlineTitle'
    | 'network.reconnectingBody'
    | 'network.reconnectingTitle'
    | 'notifications.count'
    | 'state.empty'
    | 'state.loading'
    | 'state.restoringSession'
    | 'state.saving'
    | 'theme.dark'
    | 'theme.label'
    | 'theme.light'
    | 'theme.system';
  readonly "designSystem":
    | 'breadcrumbs.label'
    | 'chip.remove'
    | 'controls.currentDirection'
    | 'controls.currentLocale'
    | 'controls.currentTheme'
    | 'controls.toggleLocale'
    | 'controls.toggleTheme'
    | 'dateField.day'
    | 'dateField.month'
    | 'dateField.year'
    | 'emptyState.prototypeBadge'
    | 'emptyState.prototypeBody'
    | 'numberStepper.decrease'
    | 'numberStepper.increase'
    | 'passwordInput.hide'
    | 'passwordInput.show'
    | 'rangeFilter.inverted'
    | 'rangeFilter.max'
    | 'rangeFilter.min'
    | 'rating.count'
    | 'rating.summary'
    | 'select.placeholder'
    | 'shell.openNavigation'
    | 'shell.primaryNavigation'
    | 'shell.skipToContent'
    | 'showcase.accordionBody'
    | 'showcase.accordionOne'
    | 'showcase.accordionTwo'
    | 'showcase.actionSheetDestructive'
    | 'showcase.actionSheetPrimary'
    | 'showcase.actionSheetSecondary'
    | 'showcase.actionSheetTitle'
    | 'showcase.amountLabel'
    | 'showcase.avatarName'
    | 'showcase.breadcrumbCurrent'
    | 'showcase.breadcrumbHome'
    | 'showcase.breadcrumbSection'
    | 'showcase.calendarLabel'
    | 'showcase.calloutBody'
    | 'showcase.calloutTitle'
    | 'showcase.chipFilter'
    | 'showcase.chipRemovable'
    | 'showcase.dateLabel'
    | 'showcase.dialogBody'
    | 'showcase.dialogTitle'
    | 'showcase.drawerTitle'
    | 'showcase.meterLabel'
    | 'showcase.motionFade'
    | 'showcase.motionNumber'
    | 'showcase.motionSlideBottom'
    | 'showcase.motionSlideStart'
    | 'showcase.openActionSheet'
    | 'showcase.openDialog'
    | 'showcase.openDrawer'
    | 'showcase.openDrawerEnd'
    | 'showcase.placeholderLabel'
    | 'showcase.popoverBody'
    | 'showcase.popoverTitle'
    | 'showcase.popoverTrigger'
    | 'showcase.rangeLabel'
    | 'showcase.ratingLabel'
    | 'showcase.replay'
    | 'showcase.ringCaption'
    | 'showcase.ringLabel'
    | 'showcase.sampleError'
    | 'showcase.sampleHint'
    | 'showcase.sampleLabel'
    | 'showcase.sampleOption'
    | 'showcase.sections.actions'
    | 'showcase.sections.content'
    | 'showcase.sections.data'
    | 'showcase.sections.dates'
    | 'showcase.sections.filters'
    | 'showcase.sections.forms'
    | 'showcase.sections.motion'
    | 'showcase.sections.navigation'
    | 'showcase.sections.overlays'
    | 'showcase.sections.shell'
    | 'showcase.sections.status'
    | 'showcase.sections.typography'
    | 'showcase.showToast'
    | 'showcase.stepperLabel'
    | 'showcase.stepperStep'
    | 'showcase.subtitle'
    | 'showcase.tabDelivery'
    | 'showcase.tabNutrition'
    | 'showcase.tabOverview'
    | 'showcase.tableCaption'
    | 'showcase.tableColumnAmount'
    | 'showcase.tableColumnName'
    | 'showcase.tableColumnTarget'
    | 'showcase.tabsLabel'
    | 'showcase.title'
    | 'showcase.toastMessage'
    | 'spike.colour.description'
    | 'spike.elevation.description'
    | 'spike.logical.description'
    | 'spike.logical.leading'
    | 'spike.logical.marker'
    | 'spike.logical.trailing'
    | 'spike.nutrition.description'
    | 'spike.sample.arabic'
    | 'spike.sample.digits'
    | 'spike.sample.latin'
    | 'spike.sections.colour'
    | 'spike.sections.elevation'
    | 'spike.sections.logical'
    | 'spike.sections.nutrition'
    | 'spike.sections.spacing'
    | 'spike.sections.typography'
    | 'spike.spacing.description'
    | 'spike.subtitle'
    | 'spike.title'
    | 'spike.typography.description'
    | 'stepper.progress'
    | 'swatch.contrast'
    | 'table.empty';
  readonly "errors":
    | 'failure.auth_email_unverified'
    | 'failure.auth_invalid_credentials'
    | 'failure.auth_step_up_required'
    | 'failure.auth_two_factor_required'
    | 'failure.auth_unauthenticated'
    | 'failure.context_branch_out_of_scope'
    | 'failure.context_organisation_forbidden'
    | 'failure.context_organisation_required'
    | 'failure.network'
    | 'failure.prototype_not_implemented'
    | 'failure.rate_limit_exceeded'
    | 'failure.server'
    | 'failure.validation_failed'
    | 'generic.body'
    | 'generic.reference'
    | 'generic.retry'
    | 'generic.title'
    | 'http.forbidden'
    | 'http.notFound'
    | 'http.rateLimited'
    | 'http.serverError'
    | 'http.unauthorised'
    | 'http.unprocessable'
    | 'network.offline'
    | 'network.timeout'
    | 'network.unreachable'
    | 'validation.accept_privacy'
    | 'validation.accept_terms'
    | 'validation.email'
    | 'validation.identifier'
    | 'validation.max_length'
    | 'validation.min_length'
    | 'validation.password_min_length'
    | 'validation.password_mismatch'
    | 'validation.required';
  readonly "marketplace":
    | 'allergens.celery'
    | 'allergens.crustaceans'
    | 'allergens.egg'
    | 'allergens.fish'
    | 'allergens.gluten'
    | 'allergens.lupin'
    | 'allergens.milk'
    | 'allergens.mollusc'
    | 'allergens.mustard'
    | 'allergens.peanut'
    | 'allergens.sesame'
    | 'allergens.soy'
    | 'allergens.sulphites'
    | 'allergens.tree_nut'
    | 'brand.homeLabel'
    | 'brand.name'
    | 'brand.tagline'
    | 'channels.b2b'
    | 'channels.b2c'
    | 'channels.corporate'
    | 'channels.delivery'
    | 'channels.marketplace'
    | 'channels.pickup'
    | 'channels.pos'
    | 'channels.subscription'
    | 'common.listSeparator'
    | 'consumer.greeting'
    | 'consumer.greetingAnonymous'
    | 'consumer.nav.cart'
    | 'consumer.nav.cartWithCount'
    | 'consumer.nav.discover'
    | 'consumer.nav.home'
    | 'consumer.nav.nutrition'
    | 'consumer.nav.planner'
    | 'consumer.nav.profile'
    | 'consumer.nav.subscriptions'
    | 'consumer.nav.virtualDietitian'
    | 'consumer.nutrition.emptyBody'
    | 'consumer.nutrition.emptyTitle'
    | 'consumer.nutrition.title'
    | 'consumer.nutrition.whyThisTarget'
    | 'consumer.onboarding.body'
    | 'consumer.onboarding.start'
    | 'consumer.onboarding.title'
    | 'consumer.resume.body'
    | 'consumer.resume.continue'
    | 'consumer.resume.dismiss'
    | 'consumer.resume.title'
    | 'consumer.subscription.emptyBody'
    | 'consumer.subscription.emptyTitle'
    | 'consumer.subscription.manage'
    | 'consumer.subscription.nextDelivery'
    | 'consumer.subscription.noNextDelivery'
    | 'consumer.subscription.title'
    | 'consumer.subscription.weeklyPrice'
    | 'consumer.subtitle'
    | 'consumer.title'
    | 'consumer.today.emptyBody'
    | 'consumer.today.emptyTitle'
    | 'consumer.today.forDate'
    | 'consumer.today.forToday'
    | 'consumer.today.locked'
    | 'consumer.today.openPlanner'
    | 'consumer.today.title'
    | 'dietitians.accepting'
    | 'dietitians.browseOthers'
    | 'dietitians.cardLabel'
    | 'dietitians.consultationBody'
    | 'dietitians.consultationTitle'
    | 'dietitians.credentialsTitle'
    | 'dietitians.emptyBody'
    | 'dietitians.emptyTitle'
    | 'dietitians.loading'
    | 'dietitians.localeArabic'
    | 'dietitians.localeEnglish'
    | 'dietitians.notAccepting'
    | 'dietitians.notAcceptingBody'
    | 'dietitians.notFoundBody'
    | 'dietitians.notFoundTitle'
    | 'dietitians.ratingLabel'
    | 'dietitians.requestConsultation'
    | 'dietitians.searchLabel'
    | 'dietitians.searchPlaceholder'
    | 'dietitians.seeAll'
    | 'dietitians.speaks'
    | 'dietitians.specialismsTitle'
    | 'dietitians.subtitle'
    | 'dietitians.syntheticBody'
    | 'dietitians.syntheticCredentials'
    | 'dietitians.syntheticTitle'
    | 'dietitians.title'
    | 'diets.dairy_free'
    | 'diets.gluten_free'
    | 'diets.halal_friendly'
    | 'diets.high_protein'
    | 'diets.keto'
    | 'diets.low_carb'
    | 'diets.mediterranean'
    | 'diets.nut_free'
    | 'diets.omnivore'
    | 'diets.pescatarian'
    | 'diets.vegan'
    | 'diets.vegetarian'
    | 'discover.comingBody'
    | 'discover.comingTitle'
    | 'discover.dietitiansBody'
    | 'discover.dietitiansTitle'
    | 'discover.family.diets'
    | 'discover.family.meals'
    | 'discover.family.plans'
    | 'discover.family.tools'
    | 'discover.familyBody.diets'
    | 'discover.familyBody.meals'
    | 'discover.familyBody.plans'
    | 'discover.familyBody.tools'
    | 'discover.kitchensBody'
    | 'discover.kitchensTitle'
    | 'discover.searchLabel'
    | 'discover.searchPlaceholder'
    | 'discover.searchSubmit'
    | 'discover.subtitle'
    | 'discover.title'
    | 'filters.availability'
    | 'filters.clear'
    | 'filters.cuisine'
    | 'filters.howToGetIt'
    | 'filters.mealType'
    | 'filters.resultCount'
    | 'filters.specialism'
    | 'footer.about'
    | 'footer.legalPrototype'
    | 'forBusiness.capability.deliverySchedule'
    | 'forBusiness.capability.eligibility'
    | 'forBusiness.capability.leadTime'
    | 'forBusiness.capability.minimumOrder'
    | 'forBusiness.capability.recurringOrders'
    | 'forBusiness.capability.volumeTiers'
    | 'forBusiness.enquiryBody'
    | 'forBusiness.enquiryTitle'
    | 'forBusiness.pricingBody'
    | 'forBusiness.pricingTitle'
    | 'forBusiness.programme.clinic.body'
    | 'forBusiness.programme.clinic.title'
    | 'forBusiness.programme.corporate.body'
    | 'forBusiness.programme.corporate.title'
    | 'forBusiness.programme.gym.body'
    | 'forBusiness.programme.gym.title'
    | 'forBusiness.programme.wholesale.body'
    | 'forBusiness.programme.wholesale.title'
    | 'forBusiness.programmesBody'
    | 'forBusiness.programmesTitle'
    | 'forBusiness.prototypeNotice'
    | 'forBusiness.requestQuotation'
    | 'forBusiness.subtitle'
    | 'forBusiness.termsBody'
    | 'forBusiness.termsTitle'
    | 'forBusiness.title'
    | 'howItWorks.meetDietitians'
    | 'howItWorks.nextBody'
    | 'howItWorks.nextTitle'
    | 'howItWorks.step.eat.body'
    | 'howItWorks.step.eat.title'
    | 'howItWorks.step.plan.body'
    | 'howItWorks.step.plan.title'
    | 'howItWorks.step.target.body'
    | 'howItWorks.step.target.title'
    | 'howItWorks.step.tell.body'
    | 'howItWorks.step.tell.title'
    | 'howItWorks.subtitle'
    | 'howItWorks.title'
    | 'kitchen.branchArea'
    | 'kitchen.branchesTitle'
    | 'kitchen.closedOn'
    | 'kitchen.deliveryZones'
    | 'kitchen.loading'
    | 'kitchen.menuBody'
    | 'kitchen.menuTitle'
    | 'kitchen.noBranches'
    | 'kitchen.noDeliveryZones'
    | 'kitchen.notFoundBody'
    | 'kitchen.notFoundTitle'
    | 'kitchen.openBetween'
    | 'kitchen.openingHours'
    | 'kitchen.orderCutOff'
    | 'kitchen.viewMenu'
    | 'kitchen.zoneFee'
    | 'kitchen.zoneMinimum'
    | 'kitchen.zoneMinutes'
    | 'kitchens.cardLabel'
    | 'kitchens.deliversTo'
    | 'kitchens.deliversToTimed'
    | 'kitchens.emptyBody'
    | 'kitchens.emptyTitle'
    | 'kitchens.imageLabel'
    | 'kitchens.notRatedYet'
    | 'kitchens.ratingLabel'
    | 'kitchens.searchLabel'
    | 'kitchens.searchPlaceholder'
    | 'kitchens.subtitle'
    | 'kitchens.title'
    | 'kitchens.verified'
    | 'landing.authBody'
    | 'landing.authTitle'
    | 'landing.browseKitchens'
    | 'landing.featuredKitchens'
    | 'landing.featuredKitchensBody'
    | 'landing.forBusinessTeaserBody'
    | 'landing.forBusinessTeaserTitle'
    | 'landing.heroBody'
    | 'landing.heroTitle'
    | 'landing.howItWorks'
    | 'landing.howItWorksTeaserBody'
    | 'landing.howItWorksTeaserTitle'
    | 'landing.seeAllKitchens'
    | 'landing.value.kitchens.body'
    | 'landing.value.kitchens.title'
    | 'landing.value.plan.body'
    | 'landing.value.plan.title'
    | 'landing.value.review.body'
    | 'landing.value.review.title'
    | 'landing.valueTitle'
    | 'levels.excessive'
    | 'levels.good'
    | 'levels.high'
    | 'levels.moderate'
    | 'levels.optimal'
    | 'mealTypes.breakfast'
    | 'mealTypes.dinner'
    | 'mealTypes.lunch'
    | 'mealTypes.snack'
    | 'medicalDisclaimer.body'
    | 'medicalDisclaimer.title'
    | 'menu.allergensTitle'
    | 'menu.cardLabel'
    | 'menu.containsAllergens'
    | 'menu.detailTitle'
    | 'menu.emptyBody'
    | 'menu.emptyTitle'
    | 'menu.fullDetailsBody'
    | 'menu.fullDetailsTitle'
    | 'menu.imageLabel'
    | 'menu.noDeclaredAllergens'
    | 'menu.perServing'
    | 'menu.preparationMinutes'
    | 'menu.searchLabel'
    | 'menu.searchPlaceholder'
    | 'menu.subtitle'
    | 'menu.title'
    | 'menu.titleFor'
    | 'nav.dietitians'
    | 'nav.discover'
    | 'nav.forBusiness'
    | 'nav.home'
    | 'nav.howItWorks'
    | 'nav.kitchens'
    | 'nav.meals'
    | 'nav.plannedNotice'
    | 'nav.plannedSuffix'
    | 'nav.plans'
    | 'nav.register'
    | 'nav.signIn'
    | 'nav.skipToContent'
    | 'nutrients.carbohydrate'
    | 'nutrients.energy'
    | 'nutrients.fat'
    | 'nutrients.fibre'
    | 'nutrients.protein'
    | 'nutrients.saturated_fat'
    | 'nutrients.sodium'
    | 'nutrients.sugars'
    | 'nutrition.carbohydrate'
    | 'nutrition.energy'
    | 'nutrition.fat'
    | 'nutrition.protein'
    | 'nutrition.source'
    | 'prototype.badge'
    | 'prototype.hint'
    | 'prototype.notBuilt'
    | 'prototype.noticeBody'
    | 'prototype.noticeTitle'
    | 'resume.thisPage'
    | 'subscriptionStates.active'
    | 'subscriptionStates.cancelled'
    | 'subscriptionStates.draft'
    | 'subscriptionStates.expired'
    | 'subscriptionStates.paused'
    | 'subscriptionStates.skipped_today'
    | 'title'
    | 'weekday.friday'
    | 'weekday.monday'
    | 'weekday.saturday'
    | 'weekday.sunday'
    | 'weekday.thursday'
    | 'weekday.tuesday'
    | 'weekday.wednesday';
  readonly "nutrition":
    | 'title';
  readonly "onboarding":
    | 'title';
  readonly "planner":
    | 'title';
  readonly "professional":
    | 'title';
  readonly "virtualDietitian":
    | 'title';
}

/** Every key in `namespace:key` form — the shape an unscoped `t()` accepts. */
export type TranslationKey = {
  [N in keyof NamespaceKeys]: `${N & string}:${NamespaceKeys[N]}`;
}[keyof NamespaceKeys];

export const PLURAL_SUFFIXES = ["zero","one","two","few","many","other"] as const;

/** Runtime list, for parity assertions and development tooling. */
export const TRANSLATION_KEYS: readonly TranslationKey[] = [
  'access:area.auth',
  'access:area.clinic',
  'access:area.corporate',
  'access:area.customer',
  'access:area.dietitian',
  'access:area.driver',
  'access:area.insurance',
  'access:area.kds',
  'access:area.kitchen',
  'access:area.partner',
  'access:area.patient',
  'access:area.platform-admin',
  'access:area.pos',
  'access:area.public',
  'access:denial.email_unverified.body',
  'access:denial.email_unverified.title',
  'access:denial.entitlement_missing.body',
  'access:denial.entitlement_missing.title',
  'access:denial.mode_excluded.body',
  'access:denial.mode_excluded.title',
  'access:denial.no_branch_context.body',
  'access:denial.no_branch_context.title',
  'access:denial.no_organisation_context.body',
  'access:denial.no_organisation_context.title',
  'access:denial.permission_missing.body',
  'access:denial.permission_missing.title',
  'access:denial.unauthenticated.body',
  'access:denial.unauthenticated.title',
  'access:forbidden.backToWorkspace',
  'access:forbidden.missingLabel',
  'access:forbidden.reasonLabel',
  'access:forbidden.signInAgain',
  'access:forbidden.switchOrganisation',
  'access:forbidden.title',
  'access:mockMode.badge',
  'access:mockMode.description',
  'access:notFound.body',
  'access:notFound.home',
  'access:notFound.title',
  'access:pending.body',
  'access:pending.title',
  'access:workspaceSelector.current',
  'access:workspaceSelector.empty',
  'access:workspaceSelector.emptyBody',
  'access:workspaceSelector.open',
  'access:workspaceSelector.subtitle',
  'access:workspaceSelector.title',
  'auth:branchPicker.empty',
  'auth:branchPicker.groupLabel',
  'auth:branchPicker.onlyOne',
  'auth:branchPicker.openLabel',
  'auth:branchPicker.subtitle',
  'auth:branchPicker.title',
  'auth:devices.current',
  'auth:devices.empty',
  'auth:devices.emptyBody',
  'auth:devices.lastUsed',
  'auth:devices.neverUsed',
  'auth:devices.platform.android',
  'auth:devices.platform.ios',
  'auth:devices.platform.web',
  'auth:devices.revoke',
  'auth:devices.revokeBody',
  'auth:devices.revokeConfirm',
  'auth:devices.revokeLabel',
  'auth:devices.revokeTitle',
  'auth:devices.revoked',
  'auth:devices.subtitle',
  'auth:devices.title',
  'auth:forgotPassword.backToSignIn',
  'auth:forgotPassword.emailLabel',
  'auth:forgotPassword.sentBody',
  'auth:forgotPassword.sentTitle',
  'auth:forgotPassword.submit',
  'auth:forgotPassword.subtitle',
  'auth:forgotPassword.title',
  'auth:login.emailLabel',
  'auth:login.emailPlaceholder',
  'auth:login.failed',
  'auth:login.forgotLink',
  'auth:login.passwordLabel',
  'auth:login.rateLimited',
  'auth:login.registerLink',
  'auth:login.registerPrompt',
  'auth:login.rememberLabel',
  'auth:login.submit',
  'auth:login.subtitle',
  'auth:login.title',
  'auth:login.twoFactor.back',
  'auth:login.twoFactor.codeHint',
  'auth:login.twoFactor.codeLabel',
  'auth:login.twoFactor.recoveryHint',
  'auth:login.twoFactor.recoveryLabel',
  'auth:login.twoFactor.submit',
  'auth:login.twoFactor.subtitle',
  'auth:login.twoFactor.title',
  'auth:login.twoFactor.useCode',
  'auth:login.twoFactor.useRecovery',
  'auth:organisationPicker.branchCount',
  'auth:organisationPicker.empty',
  'auth:organisationPicker.emptyBody',
  'auth:organisationPicker.noBranches',
  'auth:organisationPicker.onlyOne',
  'auth:organisationPicker.openLabel',
  'auth:organisationPicker.pending',
  'auth:organisationPicker.roleLabel',
  'auth:organisationPicker.subtitle',
  'auth:organisationPicker.suspended',
  'auth:organisationPicker.title',
  'auth:profile.account',
  'auth:profile.branch',
  'auth:profile.consents',
  'auth:profile.consentsNone',
  'auth:profile.context',
  'auth:profile.displayName',
  'auth:profile.email',
  'auth:profile.entitlements',
  'auth:profile.locale',
  'auth:profile.memberSince',
  'auth:profile.memberships',
  'auth:profile.noBranch',
  'auth:profile.noContext',
  'auth:profile.none',
  'auth:profile.organisation',
  'auth:profile.permissions',
  'auth:profile.roles',
  'auth:profile.subtitle',
  'auth:profile.timeZone',
  'auth:profile.title',
  'auth:profile.twoFactor',
  'auth:profile.twoFactorDisabled',
  'auth:profile.twoFactorEnabled',
  'auth:register.acceptPrivacy',
  'auth:register.acceptTerms',
  'auth:register.emailLabel',
  'auth:register.loginLink',
  'auth:register.loginPrompt',
  'auth:register.nameLabel',
  'auth:register.passwordConfirmationLabel',
  'auth:register.passwordHint',
  'auth:register.passwordLabel',
  'auth:register.privacyLink',
  'auth:register.submit',
  'auth:register.subtitle',
  'auth:register.termsLink',
  'auth:register.title',
  'auth:resetPassword.invalidToken',
  'auth:resetPassword.missingLink',
  'auth:resetPassword.missingLinkBody',
  'auth:resetPassword.passwordConfirmationLabel',
  'auth:resetPassword.passwordLabel',
  'auth:resetPassword.requestNew',
  'auth:resetPassword.submit',
  'auth:resetPassword.subtitle',
  'auth:resetPassword.successBody',
  'auth:resetPassword.successTitle',
  'auth:resetPassword.title',
  'auth:stepUp.body',
  'auth:stepUp.confirmed',
  'auth:stepUp.passwordLabel',
  'auth:stepUp.submit',
  'auth:stepUp.title',
  'auth:verifyEmail.body',
  'auth:verifyEmail.checkAgain',
  'auth:verifyEmail.continue',
  'auth:verifyEmail.cooldown',
  'auth:verifyEmail.pendingBody',
  'auth:verifyEmail.pendingTitle',
  'auth:verifyEmail.resend',
  'auth:verifyEmail.resent',
  'auth:verifyEmail.title',
  'auth:verifyEmail.verifiedBody',
  'auth:verifyEmail.verifiedTitle',
  'auth:verifyEmail.wrongAddress',
  'auth:workspace.devices',
  'auth:workspace.profile',
  'auth:workspace.subtitle',
  'auth:workspace.switchBranch',
  'auth:workspace.switchOrganisation',
  'auth:workspace.title',
  'business:title',
  'catalogue:title',
  'commerce:title',
  'common:action.back',
  'common:action.cancel',
  'common:action.change',
  'common:action.close',
  'common:action.confirm',
  'common:action.continue',
  'common:action.dismiss',
  'common:action.done',
  'common:action.goBack',
  'common:action.refresh',
  'common:action.resend',
  'common:action.retry',
  'common:action.save',
  'common:action.select',
  'common:action.signIn',
  'common:action.signOut',
  'common:action.signUp',
  'common:app.name',
  'common:app.tagline',
  'common:dev.mockBadge',
  'common:dev.mockDescription',
  'common:dev.mockScenario',
  'common:dev.switchScenario',
  'common:dev.switchScenarioHint',
  'common:direction.ltr',
  'common:direction.rtl',
  'common:locale.arabic',
  'common:locale.changed',
  'common:locale.english',
  'common:locale.label',
  'common:locale.reloadLater',
  'common:locale.reloadNow',
  'common:locale.reloadRequiredBody',
  'common:locale.reloadRequiredTitle',
  'common:nav.devices',
  'common:nav.overview',
  'common:nav.profile',
  'common:nav.showcase',
  'common:nav.workspace',
  'common:network.backOnline',
  'common:network.offlineBody',
  'common:network.offlineTitle',
  'common:network.reconnectingBody',
  'common:network.reconnectingTitle',
  'common:notifications.count',
  'common:state.empty',
  'common:state.loading',
  'common:state.restoringSession',
  'common:state.saving',
  'common:theme.dark',
  'common:theme.label',
  'common:theme.light',
  'common:theme.system',
  'designSystem:breadcrumbs.label',
  'designSystem:chip.remove',
  'designSystem:controls.currentDirection',
  'designSystem:controls.currentLocale',
  'designSystem:controls.currentTheme',
  'designSystem:controls.toggleLocale',
  'designSystem:controls.toggleTheme',
  'designSystem:dateField.day',
  'designSystem:dateField.month',
  'designSystem:dateField.year',
  'designSystem:emptyState.prototypeBadge',
  'designSystem:emptyState.prototypeBody',
  'designSystem:numberStepper.decrease',
  'designSystem:numberStepper.increase',
  'designSystem:passwordInput.hide',
  'designSystem:passwordInput.show',
  'designSystem:rangeFilter.inverted',
  'designSystem:rangeFilter.max',
  'designSystem:rangeFilter.min',
  'designSystem:rating.count',
  'designSystem:rating.summary',
  'designSystem:select.placeholder',
  'designSystem:shell.openNavigation',
  'designSystem:shell.primaryNavigation',
  'designSystem:shell.skipToContent',
  'designSystem:showcase.accordionBody',
  'designSystem:showcase.accordionOne',
  'designSystem:showcase.accordionTwo',
  'designSystem:showcase.actionSheetDestructive',
  'designSystem:showcase.actionSheetPrimary',
  'designSystem:showcase.actionSheetSecondary',
  'designSystem:showcase.actionSheetTitle',
  'designSystem:showcase.amountLabel',
  'designSystem:showcase.avatarName',
  'designSystem:showcase.breadcrumbCurrent',
  'designSystem:showcase.breadcrumbHome',
  'designSystem:showcase.breadcrumbSection',
  'designSystem:showcase.calendarLabel',
  'designSystem:showcase.calloutBody',
  'designSystem:showcase.calloutTitle',
  'designSystem:showcase.chipFilter',
  'designSystem:showcase.chipRemovable',
  'designSystem:showcase.dateLabel',
  'designSystem:showcase.dialogBody',
  'designSystem:showcase.dialogTitle',
  'designSystem:showcase.drawerTitle',
  'designSystem:showcase.meterLabel',
  'designSystem:showcase.motionFade',
  'designSystem:showcase.motionNumber',
  'designSystem:showcase.motionSlideBottom',
  'designSystem:showcase.motionSlideStart',
  'designSystem:showcase.openActionSheet',
  'designSystem:showcase.openDialog',
  'designSystem:showcase.openDrawer',
  'designSystem:showcase.openDrawerEnd',
  'designSystem:showcase.placeholderLabel',
  'designSystem:showcase.popoverBody',
  'designSystem:showcase.popoverTitle',
  'designSystem:showcase.popoverTrigger',
  'designSystem:showcase.rangeLabel',
  'designSystem:showcase.ratingLabel',
  'designSystem:showcase.replay',
  'designSystem:showcase.ringCaption',
  'designSystem:showcase.ringLabel',
  'designSystem:showcase.sampleError',
  'designSystem:showcase.sampleHint',
  'designSystem:showcase.sampleLabel',
  'designSystem:showcase.sampleOption',
  'designSystem:showcase.sections.actions',
  'designSystem:showcase.sections.content',
  'designSystem:showcase.sections.data',
  'designSystem:showcase.sections.dates',
  'designSystem:showcase.sections.filters',
  'designSystem:showcase.sections.forms',
  'designSystem:showcase.sections.motion',
  'designSystem:showcase.sections.navigation',
  'designSystem:showcase.sections.overlays',
  'designSystem:showcase.sections.shell',
  'designSystem:showcase.sections.status',
  'designSystem:showcase.sections.typography',
  'designSystem:showcase.showToast',
  'designSystem:showcase.stepperLabel',
  'designSystem:showcase.stepperStep',
  'designSystem:showcase.subtitle',
  'designSystem:showcase.tabDelivery',
  'designSystem:showcase.tabNutrition',
  'designSystem:showcase.tabOverview',
  'designSystem:showcase.tableCaption',
  'designSystem:showcase.tableColumnAmount',
  'designSystem:showcase.tableColumnName',
  'designSystem:showcase.tableColumnTarget',
  'designSystem:showcase.tabsLabel',
  'designSystem:showcase.title',
  'designSystem:showcase.toastMessage',
  'designSystem:spike.colour.description',
  'designSystem:spike.elevation.description',
  'designSystem:spike.logical.description',
  'designSystem:spike.logical.leading',
  'designSystem:spike.logical.marker',
  'designSystem:spike.logical.trailing',
  'designSystem:spike.nutrition.description',
  'designSystem:spike.sample.arabic',
  'designSystem:spike.sample.digits',
  'designSystem:spike.sample.latin',
  'designSystem:spike.sections.colour',
  'designSystem:spike.sections.elevation',
  'designSystem:spike.sections.logical',
  'designSystem:spike.sections.nutrition',
  'designSystem:spike.sections.spacing',
  'designSystem:spike.sections.typography',
  'designSystem:spike.spacing.description',
  'designSystem:spike.subtitle',
  'designSystem:spike.title',
  'designSystem:spike.typography.description',
  'designSystem:stepper.progress',
  'designSystem:swatch.contrast',
  'designSystem:table.empty',
  'errors:failure.auth_email_unverified',
  'errors:failure.auth_invalid_credentials',
  'errors:failure.auth_step_up_required',
  'errors:failure.auth_two_factor_required',
  'errors:failure.auth_unauthenticated',
  'errors:failure.context_branch_out_of_scope',
  'errors:failure.context_organisation_forbidden',
  'errors:failure.context_organisation_required',
  'errors:failure.network',
  'errors:failure.prototype_not_implemented',
  'errors:failure.rate_limit_exceeded',
  'errors:failure.server',
  'errors:failure.validation_failed',
  'errors:generic.body',
  'errors:generic.reference',
  'errors:generic.retry',
  'errors:generic.title',
  'errors:http.forbidden',
  'errors:http.notFound',
  'errors:http.rateLimited',
  'errors:http.serverError',
  'errors:http.unauthorised',
  'errors:http.unprocessable',
  'errors:network.offline',
  'errors:network.timeout',
  'errors:network.unreachable',
  'errors:validation.accept_privacy',
  'errors:validation.accept_terms',
  'errors:validation.email',
  'errors:validation.identifier',
  'errors:validation.max_length',
  'errors:validation.min_length',
  'errors:validation.password_min_length',
  'errors:validation.password_mismatch',
  'errors:validation.required',
  'marketplace:allergens.celery',
  'marketplace:allergens.crustaceans',
  'marketplace:allergens.egg',
  'marketplace:allergens.fish',
  'marketplace:allergens.gluten',
  'marketplace:allergens.lupin',
  'marketplace:allergens.milk',
  'marketplace:allergens.mollusc',
  'marketplace:allergens.mustard',
  'marketplace:allergens.peanut',
  'marketplace:allergens.sesame',
  'marketplace:allergens.soy',
  'marketplace:allergens.sulphites',
  'marketplace:allergens.tree_nut',
  'marketplace:brand.homeLabel',
  'marketplace:brand.name',
  'marketplace:brand.tagline',
  'marketplace:channels.b2b',
  'marketplace:channels.b2c',
  'marketplace:channels.corporate',
  'marketplace:channels.delivery',
  'marketplace:channels.marketplace',
  'marketplace:channels.pickup',
  'marketplace:channels.pos',
  'marketplace:channels.subscription',
  'marketplace:common.listSeparator',
  'marketplace:consumer.greeting',
  'marketplace:consumer.greetingAnonymous',
  'marketplace:consumer.nav.cart',
  'marketplace:consumer.nav.cartWithCount',
  'marketplace:consumer.nav.discover',
  'marketplace:consumer.nav.home',
  'marketplace:consumer.nav.nutrition',
  'marketplace:consumer.nav.planner',
  'marketplace:consumer.nav.profile',
  'marketplace:consumer.nav.subscriptions',
  'marketplace:consumer.nav.virtualDietitian',
  'marketplace:consumer.nutrition.emptyBody',
  'marketplace:consumer.nutrition.emptyTitle',
  'marketplace:consumer.nutrition.title',
  'marketplace:consumer.nutrition.whyThisTarget',
  'marketplace:consumer.onboarding.body',
  'marketplace:consumer.onboarding.start',
  'marketplace:consumer.onboarding.title',
  'marketplace:consumer.resume.body',
  'marketplace:consumer.resume.continue',
  'marketplace:consumer.resume.dismiss',
  'marketplace:consumer.resume.title',
  'marketplace:consumer.subscription.emptyBody',
  'marketplace:consumer.subscription.emptyTitle',
  'marketplace:consumer.subscription.manage',
  'marketplace:consumer.subscription.nextDelivery',
  'marketplace:consumer.subscription.noNextDelivery',
  'marketplace:consumer.subscription.title',
  'marketplace:consumer.subscription.weeklyPrice',
  'marketplace:consumer.subtitle',
  'marketplace:consumer.title',
  'marketplace:consumer.today.emptyBody',
  'marketplace:consumer.today.emptyTitle',
  'marketplace:consumer.today.forDate',
  'marketplace:consumer.today.forToday',
  'marketplace:consumer.today.locked',
  'marketplace:consumer.today.openPlanner',
  'marketplace:consumer.today.title',
  'marketplace:dietitians.accepting',
  'marketplace:dietitians.browseOthers',
  'marketplace:dietitians.cardLabel',
  'marketplace:dietitians.consultationBody',
  'marketplace:dietitians.consultationTitle',
  'marketplace:dietitians.credentialsTitle',
  'marketplace:dietitians.emptyBody',
  'marketplace:dietitians.emptyTitle',
  'marketplace:dietitians.loading',
  'marketplace:dietitians.localeArabic',
  'marketplace:dietitians.localeEnglish',
  'marketplace:dietitians.notAccepting',
  'marketplace:dietitians.notAcceptingBody',
  'marketplace:dietitians.notFoundBody',
  'marketplace:dietitians.notFoundTitle',
  'marketplace:dietitians.ratingLabel',
  'marketplace:dietitians.requestConsultation',
  'marketplace:dietitians.searchLabel',
  'marketplace:dietitians.searchPlaceholder',
  'marketplace:dietitians.seeAll',
  'marketplace:dietitians.speaks',
  'marketplace:dietitians.specialismsTitle',
  'marketplace:dietitians.subtitle',
  'marketplace:dietitians.syntheticBody',
  'marketplace:dietitians.syntheticCredentials',
  'marketplace:dietitians.syntheticTitle',
  'marketplace:dietitians.title',
  'marketplace:diets.dairy_free',
  'marketplace:diets.gluten_free',
  'marketplace:diets.halal_friendly',
  'marketplace:diets.high_protein',
  'marketplace:diets.keto',
  'marketplace:diets.low_carb',
  'marketplace:diets.mediterranean',
  'marketplace:diets.nut_free',
  'marketplace:diets.omnivore',
  'marketplace:diets.pescatarian',
  'marketplace:diets.vegan',
  'marketplace:diets.vegetarian',
  'marketplace:discover.comingBody',
  'marketplace:discover.comingTitle',
  'marketplace:discover.dietitiansBody',
  'marketplace:discover.dietitiansTitle',
  'marketplace:discover.family.diets',
  'marketplace:discover.family.meals',
  'marketplace:discover.family.plans',
  'marketplace:discover.family.tools',
  'marketplace:discover.familyBody.diets',
  'marketplace:discover.familyBody.meals',
  'marketplace:discover.familyBody.plans',
  'marketplace:discover.familyBody.tools',
  'marketplace:discover.kitchensBody',
  'marketplace:discover.kitchensTitle',
  'marketplace:discover.searchLabel',
  'marketplace:discover.searchPlaceholder',
  'marketplace:discover.searchSubmit',
  'marketplace:discover.subtitle',
  'marketplace:discover.title',
  'marketplace:filters.availability',
  'marketplace:filters.clear',
  'marketplace:filters.cuisine',
  'marketplace:filters.howToGetIt',
  'marketplace:filters.mealType',
  'marketplace:filters.resultCount',
  'marketplace:filters.specialism',
  'marketplace:footer.about',
  'marketplace:footer.legalPrototype',
  'marketplace:forBusiness.capability.deliverySchedule',
  'marketplace:forBusiness.capability.eligibility',
  'marketplace:forBusiness.capability.leadTime',
  'marketplace:forBusiness.capability.minimumOrder',
  'marketplace:forBusiness.capability.recurringOrders',
  'marketplace:forBusiness.capability.volumeTiers',
  'marketplace:forBusiness.enquiryBody',
  'marketplace:forBusiness.enquiryTitle',
  'marketplace:forBusiness.pricingBody',
  'marketplace:forBusiness.pricingTitle',
  'marketplace:forBusiness.programme.clinic.body',
  'marketplace:forBusiness.programme.clinic.title',
  'marketplace:forBusiness.programme.corporate.body',
  'marketplace:forBusiness.programme.corporate.title',
  'marketplace:forBusiness.programme.gym.body',
  'marketplace:forBusiness.programme.gym.title',
  'marketplace:forBusiness.programme.wholesale.body',
  'marketplace:forBusiness.programme.wholesale.title',
  'marketplace:forBusiness.programmesBody',
  'marketplace:forBusiness.programmesTitle',
  'marketplace:forBusiness.prototypeNotice',
  'marketplace:forBusiness.requestQuotation',
  'marketplace:forBusiness.subtitle',
  'marketplace:forBusiness.termsBody',
  'marketplace:forBusiness.termsTitle',
  'marketplace:forBusiness.title',
  'marketplace:howItWorks.meetDietitians',
  'marketplace:howItWorks.nextBody',
  'marketplace:howItWorks.nextTitle',
  'marketplace:howItWorks.step.eat.body',
  'marketplace:howItWorks.step.eat.title',
  'marketplace:howItWorks.step.plan.body',
  'marketplace:howItWorks.step.plan.title',
  'marketplace:howItWorks.step.target.body',
  'marketplace:howItWorks.step.target.title',
  'marketplace:howItWorks.step.tell.body',
  'marketplace:howItWorks.step.tell.title',
  'marketplace:howItWorks.subtitle',
  'marketplace:howItWorks.title',
  'marketplace:kitchen.branchArea',
  'marketplace:kitchen.branchesTitle',
  'marketplace:kitchen.closedOn',
  'marketplace:kitchen.deliveryZones',
  'marketplace:kitchen.loading',
  'marketplace:kitchen.menuBody',
  'marketplace:kitchen.menuTitle',
  'marketplace:kitchen.noBranches',
  'marketplace:kitchen.noDeliveryZones',
  'marketplace:kitchen.notFoundBody',
  'marketplace:kitchen.notFoundTitle',
  'marketplace:kitchen.openBetween',
  'marketplace:kitchen.openingHours',
  'marketplace:kitchen.orderCutOff',
  'marketplace:kitchen.viewMenu',
  'marketplace:kitchen.zoneFee',
  'marketplace:kitchen.zoneMinimum',
  'marketplace:kitchen.zoneMinutes',
  'marketplace:kitchens.cardLabel',
  'marketplace:kitchens.deliversTo',
  'marketplace:kitchens.deliversToTimed',
  'marketplace:kitchens.emptyBody',
  'marketplace:kitchens.emptyTitle',
  'marketplace:kitchens.imageLabel',
  'marketplace:kitchens.notRatedYet',
  'marketplace:kitchens.ratingLabel',
  'marketplace:kitchens.searchLabel',
  'marketplace:kitchens.searchPlaceholder',
  'marketplace:kitchens.subtitle',
  'marketplace:kitchens.title',
  'marketplace:kitchens.verified',
  'marketplace:landing.authBody',
  'marketplace:landing.authTitle',
  'marketplace:landing.browseKitchens',
  'marketplace:landing.featuredKitchens',
  'marketplace:landing.featuredKitchensBody',
  'marketplace:landing.forBusinessTeaserBody',
  'marketplace:landing.forBusinessTeaserTitle',
  'marketplace:landing.heroBody',
  'marketplace:landing.heroTitle',
  'marketplace:landing.howItWorks',
  'marketplace:landing.howItWorksTeaserBody',
  'marketplace:landing.howItWorksTeaserTitle',
  'marketplace:landing.seeAllKitchens',
  'marketplace:landing.value.kitchens.body',
  'marketplace:landing.value.kitchens.title',
  'marketplace:landing.value.plan.body',
  'marketplace:landing.value.plan.title',
  'marketplace:landing.value.review.body',
  'marketplace:landing.value.review.title',
  'marketplace:landing.valueTitle',
  'marketplace:levels.excessive',
  'marketplace:levels.good',
  'marketplace:levels.high',
  'marketplace:levels.moderate',
  'marketplace:levels.optimal',
  'marketplace:mealTypes.breakfast',
  'marketplace:mealTypes.dinner',
  'marketplace:mealTypes.lunch',
  'marketplace:mealTypes.snack',
  'marketplace:medicalDisclaimer.body',
  'marketplace:medicalDisclaimer.title',
  'marketplace:menu.allergensTitle',
  'marketplace:menu.cardLabel',
  'marketplace:menu.containsAllergens',
  'marketplace:menu.detailTitle',
  'marketplace:menu.emptyBody',
  'marketplace:menu.emptyTitle',
  'marketplace:menu.fullDetailsBody',
  'marketplace:menu.fullDetailsTitle',
  'marketplace:menu.imageLabel',
  'marketplace:menu.noDeclaredAllergens',
  'marketplace:menu.perServing',
  'marketplace:menu.preparationMinutes',
  'marketplace:menu.searchLabel',
  'marketplace:menu.searchPlaceholder',
  'marketplace:menu.subtitle',
  'marketplace:menu.title',
  'marketplace:menu.titleFor',
  'marketplace:nav.dietitians',
  'marketplace:nav.discover',
  'marketplace:nav.forBusiness',
  'marketplace:nav.home',
  'marketplace:nav.howItWorks',
  'marketplace:nav.kitchens',
  'marketplace:nav.meals',
  'marketplace:nav.plannedNotice',
  'marketplace:nav.plannedSuffix',
  'marketplace:nav.plans',
  'marketplace:nav.register',
  'marketplace:nav.signIn',
  'marketplace:nav.skipToContent',
  'marketplace:nutrients.carbohydrate',
  'marketplace:nutrients.energy',
  'marketplace:nutrients.fat',
  'marketplace:nutrients.fibre',
  'marketplace:nutrients.protein',
  'marketplace:nutrients.saturated_fat',
  'marketplace:nutrients.sodium',
  'marketplace:nutrients.sugars',
  'marketplace:nutrition.carbohydrate',
  'marketplace:nutrition.energy',
  'marketplace:nutrition.fat',
  'marketplace:nutrition.protein',
  'marketplace:nutrition.source',
  'marketplace:prototype.badge',
  'marketplace:prototype.hint',
  'marketplace:prototype.notBuilt',
  'marketplace:prototype.noticeBody',
  'marketplace:prototype.noticeTitle',
  'marketplace:resume.thisPage',
  'marketplace:subscriptionStates.active',
  'marketplace:subscriptionStates.cancelled',
  'marketplace:subscriptionStates.draft',
  'marketplace:subscriptionStates.expired',
  'marketplace:subscriptionStates.paused',
  'marketplace:subscriptionStates.skipped_today',
  'marketplace:title',
  'marketplace:weekday.friday',
  'marketplace:weekday.monday',
  'marketplace:weekday.saturday',
  'marketplace:weekday.sunday',
  'marketplace:weekday.thursday',
  'marketplace:weekday.tuesday',
  'marketplace:weekday.wednesday',
  'nutrition:title',
  'onboarding:title',
  'planner:title',
  'professional:title',
  'virtualDietitian:title',
];

const TRANSLATION_KEY_SET: ReadonlySet<string> = new Set(TRANSLATION_KEYS);

export function isTranslationKey(value: unknown): value is TranslationKey {
  return typeof value === 'string' && TRANSLATION_KEY_SET.has(value);
}
