/*
 * AUTOGENERATED by @healthy360/i18n — do not edit by hand.
 * Source: packages/i18n/catalogues/en/*.json
 * Regenerate: pnpm --filter @healthy360/i18n gen:keys
 *
 * 168 keys across 5 namespaces. Plural variants (zero, one, two, few, many, other)
 * are collapsed to their base key, because that is the key t() is called with.
 */

/** Keys available in each namespace, unqualified. */
export interface NamespaceKeys {
  readonly "access":
    | 'denial.email_unverified.body'
    | 'denial.email_unverified.title'
    | 'denial.entitlement_missing.body'
    | 'denial.entitlement_missing.title'
    | 'denial.mode_excluded.body'
    | 'denial.mode_excluded.title'
    | 'denial.no_branch_context.body'
    | 'denial.no_branch_context.title'
    | 'denial.no_organisation_context.body'
    | 'denial.no_organisation_context.title'
    | 'denial.permission_missing.body'
    | 'denial.permission_missing.title'
    | 'denial.unauthenticated.body'
    | 'denial.unauthenticated.title'
    | 'forbidden.backToWorkspace'
    | 'forbidden.reasonLabel'
    | 'forbidden.signInAgain'
    | 'forbidden.title'
    | 'mockMode.badge'
    | 'mockMode.description'
    | 'notFound.body'
    | 'notFound.home'
    | 'notFound.title'
    | 'pending.body'
    | 'pending.title';
  readonly "auth":
    | 'branchPicker.empty'
    | 'branchPicker.subtitle'
    | 'branchPicker.title'
    | 'forgotPassword.sentBody'
    | 'forgotPassword.sentTitle'
    | 'forgotPassword.submit'
    | 'forgotPassword.subtitle'
    | 'forgotPassword.title'
    | 'login.emailLabel'
    | 'login.emailPlaceholder'
    | 'login.failed'
    | 'login.forgotLink'
    | 'login.passwordLabel'
    | 'login.registerLink'
    | 'login.registerPrompt'
    | 'login.rememberLabel'
    | 'login.submit'
    | 'login.subtitle'
    | 'login.title'
    | 'organisationPicker.branchCount'
    | 'organisationPicker.empty'
    | 'organisationPicker.emptyBody'
    | 'organisationPicker.pending'
    | 'organisationPicker.subtitle'
    | 'organisationPicker.suspended'
    | 'organisationPicker.title'
    | 'register.acceptPrivacy'
    | 'register.acceptTerms'
    | 'register.emailLabel'
    | 'register.loginLink'
    | 'register.loginPrompt'
    | 'register.nameLabel'
    | 'register.passwordConfirmationLabel'
    | 'register.passwordHint'
    | 'register.passwordLabel'
    | 'register.submit'
    | 'register.subtitle'
    | 'register.title'
    | 'resetPassword.invalidToken'
    | 'resetPassword.passwordConfirmationLabel'
    | 'resetPassword.passwordLabel'
    | 'resetPassword.submit'
    | 'resetPassword.subtitle'
    | 'resetPassword.successBody'
    | 'resetPassword.successTitle'
    | 'resetPassword.title'
    | 'verifyEmail.body'
    | 'verifyEmail.checkAgain'
    | 'verifyEmail.resend'
    | 'verifyEmail.resent'
    | 'verifyEmail.title'
    | 'verifyEmail.wrongAddress'
    | 'workspace.devices'
    | 'workspace.profile'
    | 'workspace.subtitle'
    | 'workspace.switchBranch'
    | 'workspace.switchOrganisation'
    | 'workspace.title';
  readonly "common":
    | 'action.back'
    | 'action.cancel'
    | 'action.change'
    | 'action.close'
    | 'action.continue'
    | 'action.refresh'
    | 'action.resend'
    | 'action.retry'
    | 'action.save'
    | 'action.select'
    | 'action.signIn'
    | 'action.signOut'
    | 'action.signUp'
    | 'app.name'
    | 'app.tagline'
    | 'direction.ltr'
    | 'direction.rtl'
    | 'locale.arabic'
    | 'locale.changed'
    | 'locale.english'
    | 'locale.label'
    | 'locale.reloadLater'
    | 'locale.reloadNow'
    | 'locale.reloadRequiredBody'
    | 'locale.reloadRequiredTitle'
    | 'network.backOnline'
    | 'network.offlineBody'
    | 'network.offlineTitle'
    | 'notifications.count'
    | 'state.empty'
    | 'state.loading'
    | 'state.restoringSession'
    | 'state.saving'
    | 'theme.dark'
    | 'theme.label'
    | 'theme.light'
    | 'theme.system';
  readonly "designSystem":
    | 'controls.currentDirection'
    | 'controls.currentLocale'
    | 'controls.currentTheme'
    | 'controls.toggleLocale'
    | 'controls.toggleTheme'
    | 'spike.colour.description'
    | 'spike.elevation.description'
    | 'spike.logical.description'
    | 'spike.logical.leading'
    | 'spike.logical.marker'
    | 'spike.logical.trailing'
    | 'spike.nutrition.description'
    | 'spike.sample.arabic'
    | 'spike.sample.digits'
    | 'spike.sample.latin'
    | 'spike.sections.colour'
    | 'spike.sections.elevation'
    | 'spike.sections.logical'
    | 'spike.sections.nutrition'
    | 'spike.sections.spacing'
    | 'spike.sections.typography'
    | 'spike.spacing.description'
    | 'spike.subtitle'
    | 'spike.title'
    | 'spike.typography.description'
    | 'swatch.contrast';
  readonly "errors":
    | 'generic.body'
    | 'generic.reference'
    | 'generic.retry'
    | 'generic.title'
    | 'http.forbidden'
    | 'http.notFound'
    | 'http.rateLimited'
    | 'http.serverError'
    | 'http.unauthorised'
    | 'http.unprocessable'
    | 'network.offline'
    | 'network.timeout'
    | 'network.unreachable'
    | 'validation.accept_privacy'
    | 'validation.accept_terms'
    | 'validation.email'
    | 'validation.identifier'
    | 'validation.max_length'
    | 'validation.min_length'
    | 'validation.password_min_length'
    | 'validation.password_mismatch'
    | 'validation.required';
}

/** Every key in `namespace:key` form — the shape an unscoped `t()` accepts. */
export type TranslationKey = {
  [N in keyof NamespaceKeys]: `${N & string}:${NamespaceKeys[N]}`;
}[keyof NamespaceKeys];

export const PLURAL_SUFFIXES = ["zero","one","two","few","many","other"] as const;

/** Runtime list, for parity assertions and development tooling. */
export const TRANSLATION_KEYS: readonly TranslationKey[] = [
  'access:denial.email_unverified.body',
  'access:denial.email_unverified.title',
  'access:denial.entitlement_missing.body',
  'access:denial.entitlement_missing.title',
  'access:denial.mode_excluded.body',
  'access:denial.mode_excluded.title',
  'access:denial.no_branch_context.body',
  'access:denial.no_branch_context.title',
  'access:denial.no_organisation_context.body',
  'access:denial.no_organisation_context.title',
  'access:denial.permission_missing.body',
  'access:denial.permission_missing.title',
  'access:denial.unauthenticated.body',
  'access:denial.unauthenticated.title',
  'access:forbidden.backToWorkspace',
  'access:forbidden.reasonLabel',
  'access:forbidden.signInAgain',
  'access:forbidden.title',
  'access:mockMode.badge',
  'access:mockMode.description',
  'access:notFound.body',
  'access:notFound.home',
  'access:notFound.title',
  'access:pending.body',
  'access:pending.title',
  'auth:branchPicker.empty',
  'auth:branchPicker.subtitle',
  'auth:branchPicker.title',
  'auth:forgotPassword.sentBody',
  'auth:forgotPassword.sentTitle',
  'auth:forgotPassword.submit',
  'auth:forgotPassword.subtitle',
  'auth:forgotPassword.title',
  'auth:login.emailLabel',
  'auth:login.emailPlaceholder',
  'auth:login.failed',
  'auth:login.forgotLink',
  'auth:login.passwordLabel',
  'auth:login.registerLink',
  'auth:login.registerPrompt',
  'auth:login.rememberLabel',
  'auth:login.submit',
  'auth:login.subtitle',
  'auth:login.title',
  'auth:organisationPicker.branchCount',
  'auth:organisationPicker.empty',
  'auth:organisationPicker.emptyBody',
  'auth:organisationPicker.pending',
  'auth:organisationPicker.subtitle',
  'auth:organisationPicker.suspended',
  'auth:organisationPicker.title',
  'auth:register.acceptPrivacy',
  'auth:register.acceptTerms',
  'auth:register.emailLabel',
  'auth:register.loginLink',
  'auth:register.loginPrompt',
  'auth:register.nameLabel',
  'auth:register.passwordConfirmationLabel',
  'auth:register.passwordHint',
  'auth:register.passwordLabel',
  'auth:register.submit',
  'auth:register.subtitle',
  'auth:register.title',
  'auth:resetPassword.invalidToken',
  'auth:resetPassword.passwordConfirmationLabel',
  'auth:resetPassword.passwordLabel',
  'auth:resetPassword.submit',
  'auth:resetPassword.subtitle',
  'auth:resetPassword.successBody',
  'auth:resetPassword.successTitle',
  'auth:resetPassword.title',
  'auth:verifyEmail.body',
  'auth:verifyEmail.checkAgain',
  'auth:verifyEmail.resend',
  'auth:verifyEmail.resent',
  'auth:verifyEmail.title',
  'auth:verifyEmail.wrongAddress',
  'auth:workspace.devices',
  'auth:workspace.profile',
  'auth:workspace.subtitle',
  'auth:workspace.switchBranch',
  'auth:workspace.switchOrganisation',
  'auth:workspace.title',
  'common:action.back',
  'common:action.cancel',
  'common:action.change',
  'common:action.close',
  'common:action.continue',
  'common:action.refresh',
  'common:action.resend',
  'common:action.retry',
  'common:action.save',
  'common:action.select',
  'common:action.signIn',
  'common:action.signOut',
  'common:action.signUp',
  'common:app.name',
  'common:app.tagline',
  'common:direction.ltr',
  'common:direction.rtl',
  'common:locale.arabic',
  'common:locale.changed',
  'common:locale.english',
  'common:locale.label',
  'common:locale.reloadLater',
  'common:locale.reloadNow',
  'common:locale.reloadRequiredBody',
  'common:locale.reloadRequiredTitle',
  'common:network.backOnline',
  'common:network.offlineBody',
  'common:network.offlineTitle',
  'common:notifications.count',
  'common:state.empty',
  'common:state.loading',
  'common:state.restoringSession',
  'common:state.saving',
  'common:theme.dark',
  'common:theme.label',
  'common:theme.light',
  'common:theme.system',
  'designSystem:controls.currentDirection',
  'designSystem:controls.currentLocale',
  'designSystem:controls.currentTheme',
  'designSystem:controls.toggleLocale',
  'designSystem:controls.toggleTheme',
  'designSystem:spike.colour.description',
  'designSystem:spike.elevation.description',
  'designSystem:spike.logical.description',
  'designSystem:spike.logical.leading',
  'designSystem:spike.logical.marker',
  'designSystem:spike.logical.trailing',
  'designSystem:spike.nutrition.description',
  'designSystem:spike.sample.arabic',
  'designSystem:spike.sample.digits',
  'designSystem:spike.sample.latin',
  'designSystem:spike.sections.colour',
  'designSystem:spike.sections.elevation',
  'designSystem:spike.sections.logical',
  'designSystem:spike.sections.nutrition',
  'designSystem:spike.sections.spacing',
  'designSystem:spike.sections.typography',
  'designSystem:spike.spacing.description',
  'designSystem:spike.subtitle',
  'designSystem:spike.title',
  'designSystem:spike.typography.description',
  'designSystem:swatch.contrast',
  'errors:generic.body',
  'errors:generic.reference',
  'errors:generic.retry',
  'errors:generic.title',
  'errors:http.forbidden',
  'errors:http.notFound',
  'errors:http.rateLimited',
  'errors:http.serverError',
  'errors:http.unauthorised',
  'errors:http.unprocessable',
  'errors:network.offline',
  'errors:network.timeout',
  'errors:network.unreachable',
  'errors:validation.accept_privacy',
  'errors:validation.accept_terms',
  'errors:validation.email',
  'errors:validation.identifier',
  'errors:validation.max_length',
  'errors:validation.min_length',
  'errors:validation.password_min_length',
  'errors:validation.password_mismatch',
  'errors:validation.required',
];

const TRANSLATION_KEY_SET: ReadonlySet<string> = new Set(TRANSLATION_KEYS);

export function isTranslationKey(value: unknown): value is TranslationKey {
  return typeof value === 'string' && TRANSLATION_KEY_SET.has(value);
}
