<?php

declare(strict_types=1);

namespace Healthy360\Catalogues\Models;

use Carbon\CarbonImmutable;
use Healthy360\Catalogues\Database\Factories\CatalogueItemPackVariantFactory;
use Healthy360\Catalogues\Enums\PackFormat;
use Healthy360\ReferenceData\Models\MeasurementUnit;
use Healthy360\Support\Attributes\Classified;
use Healthy360\Support\Enums\DataClassification;
use Healthy360\Support\Models\BaseModel;
use Healthy360\Tenancy\Concerns\BelongsToOrganisation;
use Healthy360\Tenancy\Contracts\OrganisationScoped;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * The physical detail of a pack. The variant identifier is the primary key —
 * a pack *is* the variant, seen from the warehouse — so the key is neither
 * incrementing nor generated by this model.
 *
 * @property string $catalogue_item_variant_id
 * @property string $organisation_id
 * @property string $pack_quantity
 * @property string $pack_unit_id
 * @property int|null $pack_piece_count
 * @property PackFormat|null $pack_format
 * @property int|null $net_weight_grams
 * @property CarbonImmutable|null $created_at
 * @property CarbonImmutable|null $updated_at
 */
#[Classified(DataClassification::Public, 'pack_quantity', 'pack_piece_count', 'pack_format', 'net_weight_grams')]
class CatalogueItemPackVariant extends BaseModel implements OrganisationScoped
{
    use BelongsToOrganisation;

    /** @use HasFactory<CatalogueItemPackVariantFactory> */
    use HasFactory;

    /** @var string */
    protected $primaryKey = 'catalogue_item_variant_id';

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'pack_quantity' => 'decimal:4',
            'pack_format' => PackFormat::class,
            'pack_piece_count' => 'integer',
            'net_weight_grams' => 'integer',
        ];
    }

    /**
     * @return BelongsTo<CatalogueItemVariant, $this>
     */
    public function variant(): BelongsTo
    {
        return $this->belongsTo(CatalogueItemVariant::class, 'catalogue_item_variant_id');
    }

    /**
     * @return BelongsTo<MeasurementUnit, $this>
     */
    public function unit(): BelongsTo
    {
        return $this->belongsTo(MeasurementUnit::class, 'pack_unit_id');
    }
}
