export {
    CORE_NUTRIENT_DEFINITIONS,
    ENERGY_PER_GRAM,
    KILOJOULES_PER_KILOCALORIE,
    MACRO_NUTRIENT_IDS,
    MEASURE_UNITS,
    NUTRIENT_GROUPS,
    NUTRIENT_UNITS,
    NUTRITION_BASES,
    NUTRITION_SOURCE_KINDS,
    NUTRITION_VALUE_KINDS,
    TARGET_DIRECTIONS,
    amountValue,
    coreNutrientDefinition,
    findAmount,
    isMacroNutrientId,
    isMeasureUnit,
    isNutrientGroup,
    isNutrientUnit,
    isNutritionBasis,
    isNutritionSourceKind,
    isNutritionValueKind,
    isTargetDirection,
} from './model.ts';
export type {
    DailyNutritionSummary,
    IngredientQuantity,
    IsoDate,
    MacroNutrientId,
    MacroTarget,
    MealNutrition,
    MeasureUnit,
    NutrientAmount,
    NutrientDefinition,
    NutrientGroup,
    NutrientTarget,
    NutrientUnit,
    NutritionBasis,
    NutritionCalculation,
    NutritionFacts,
    NutritionSource,
    NutritionSourceKind,
    NutritionValueKind,
    RecipeNutrition,
    Serving,
    TargetDirection,
    ToleranceRange,
    WeeklyNutritionSummary,
} from './model.ts';

export {
    DEFAULT_NUTRIENT_PRECISION,
    NutrientUnitMismatchError,
    NutritionAggregationError,
    ROUNDING_POLICY,
    ingredientContribution,
    mealNutritionFromServing,
    mergeSources,
    normaliseToPer100g,
    precisionFor,
    recipeNutritionFromIngredients,
    roundFacts,
    roundTo,
    scaleFacts,
    sumCosts,
    sumFacts,
    summariseDay,
    summariseWeek,
} from './aggregate.ts';
export type {
    DailySummaryInput,
    DerivationOptions,
    MealNutritionInput,
    RecipeNutritionInput,
    ScaleOptions,
    SumOptions,
    WeeklySummaryInput,
} from './aggregate.ts';

export {
    DEFAULT_LEVEL_BAND,
    NUTRITION_LEVELS,
    nutritionLevelForAmount,
    nutritionLevelForRatio,
    nutritionLevelRank,
    readNutritionLevels,
    worstNutritionLevel,
} from './level.ts';
export type { LevelOptions, NutrientLevelReading, NutritionLevel } from './level.ts';
